export declare type AAID<T = unknown> = { aaid: T }
export declare type About<T = unknown> = { about: T }
export declare type AccessKey<T = unknown> = { accessKey: T }
export declare type AccessKeyId<T = unknown> = { accessKeyId: T }
export declare type AccessKeyName<T = unknown> = { accessKeyName: T }
export declare type AccessPoint<T = unknown> = { accessPoint: T }
export declare type AccessToken<T = unknown> = { accessToken: T }
export declare type Account<T = unknown> = { account: T }
export declare type AccountId<T = unknown> = { accountId: T }
export declare type AccountIds<T = unknown> = { accountIds: T }
export declare type Accounts<T = unknown> = { accounts: T }
export declare type Action<T = unknown> = { action: T }
export declare type Ad<T = unknown> = { ad: T }
export declare type AdGroup<T = unknown> = { adgroup: T }
export declare type AdGroupId<T = unknown> = { adgroupId: T }
export declare type AdGroupIds<T = unknown> = { adgroupIds: T }
export declare type AdGroupName<T = unknown> = { adgroupName: T }
export declare type AdId<T = unknown> = { adId: T }
export declare type AdIds<T = unknown> = { adIds: T }
export declare type AdName<T = unknown> = { adName: T }
export declare type Add<T = unknown> = { add: T }
export declare type Address<T = unknown> = { address: T }
export declare type Addresses<T = unknown> = { addresses: T }
export declare type Adgroups<T = unknown> = { adgroups: T }
export declare type Admin<T = unknown> = { admin: T }
export declare type AdminId<T = unknown> = { adminId: T }
export declare type AdminIds<T = unknown> = { adminIds: T }
export declare type Admins<T = unknown> = { admins: T }
export declare type Ads<T = unknown> = { ads: T }
export declare type Adset<T = unknown> = { adset: T }
export declare type AdsetId<T = unknown> = { adsetId: T }
export declare type AdsetIds<T = unknown> = { adsetIds: T }
export declare type AdsetName<T = unknown> = { adsetName: T }
export declare type Advertiser<T = unknown> = { advertiser: T }
export declare type AdvertiserId<T = unknown> = { advertiserId: T }
export declare type AdvertiserIds<T = unknown> = { advertiserIds: T }
export declare type Advertisers<T = unknown> = { advertisers: T }
export declare type Age<T = unknown> = { age: T }
export declare type AgeGroup<T = unknown> = { ageGroup: T }
export declare type Albom<T = unknown> = { albom: T }
export declare type AlbomId<T = unknown> = { albomId: T }
export declare type AlbomIds<T = unknown> = { albomIds: T }
export declare type AlbomName<T = unknown> = { albomName: T }
export declare type Alboms<T = unknown> = { alboms: T }
export declare type Alg<T = unknown> = { alg: T }
export declare type Alias<T = unknown> = { alias: T }
export declare type Align<T = unknown> = { align: T }
export declare type Amount<T = unknown> = { amount: T }
export declare type Android<T = unknown> = { android: T }
export declare type Answer<T = unknown> = { answer: T }
export declare type AnswerId<T = unknown> = { answerId: T }
export declare type AnswerIds<T = unknown> = { answerIds: T }
export declare type Answers<T = unknown> = { answers: T }
export declare type Api<T = unknown> = { api: T }
export declare type ApiKey<T = unknown> = { apiKey: T }
export declare type ApiUrl<T = unknown> = { apiUrl: T }
export declare type App<T = unknown> = { app: T }
export declare type AppId<T = unknown> = { appId: T }
export declare type AppIds<T = unknown> = { appIds: T }
export declare type Apple<T = unknown> = { apple: T }
export declare type Application<T = unknown> = { application: T }
export declare type ApplicationId<T = unknown> = { applicationId: T }
export declare type ApplicationIds<T = unknown> = { applicationIds: T }
export declare type Applications<T = unknown> = { applications: T }
export declare type Apps<T = unknown> = { apps: T }
export declare type AppslyerId<T = unknown> = { appsflyerId: T }
export declare type Arg<T = unknown> = { arg: T }
export declare type Args<T = unknown> = { args: T }
export declare type Asset<T = unknown> = { asset: T }
export declare type AssetHash<T = unknown> = { assetHash: T }
export declare type AssetId<T = unknown> = { assetId: T }
export declare type AssetIds<T = unknown> = { assetIds: T }
export declare type AssetName<T = unknown> = { assetName: T }
export declare type Assets<T = unknown> = { assets: T }
export declare type Attribute<T = unknown> = { attribute: T }
export declare type AttributeId<T = unknown> = { attributeId: T }
export declare type AttributeIds<T = unknown> = { attributeIds: T }
export declare type Attributes<T = unknown> = { attributes: T }
export declare type Auth<T = unknown> = { auth: T }
export declare type AuthProvider<T = unknown> = { authProvider: T }
export declare type Authorized<T = unknown> = { authorized: T }
export declare type Auto<T = unknown> = { auto: T }
export declare type AutoLoad<T = unknown> = { autoLoad: T }
export declare type AutoRun<T = unknown> = { autoRun: T }
export declare type Aws<T = unknown> = { aws: T }
export declare type BID<T = unknown> = { bid: T }
export declare type Background<T = unknown> = { background: T }
export declare type BackgroundColor<T = unknown> = { backgroundColor: T }
export declare type Badge<T = unknown> = { badge: T }
export declare type BadgeId<T = unknown> = { badgeId: T }
export declare type BadgeIds<T = unknown> = { badgeIds: T }
export declare type Badges<T = unknown> = { badges: T }
export declare type BaseUrl<T = unknown> = { baseUrl: T }
export declare type Block<T = unknown> = { block: T }
export declare type BlockId<T = unknown> = { blockId: T }
export declare type BlockIds<T = unknown> = { blockIds: T }
export declare type Blocked<T = unknown> = { blocked: T }
export declare type Blocks<T = unknown> = { blocks: T }
export declare type Body<T = unknown> = { body: T }
export declare type Border<T = unknown> = { border: T }
export declare type Bottom<T = unknown> = { bottom: T }
export declare type Bucket<T = unknown> = { bucket: T }
export declare type BucketId<T = unknown> = { bucketId: T }
export declare type BucketIds<T = unknown> = { bucketIds: T }
export declare type BucketName<T = unknown> = { bucketName: T }
export declare type BucketUrl<T = unknown> = { bucketUrl: T }
export declare type Buckets<T = unknown> = { buckets: T }
export declare type Budget<T = unknown> = { budget: T }
export declare type Buffer<T = unknown> = { buffer: T }
export declare type Builder<T = unknown> = { builder: T }
export declare type Bundle<T = unknown> = { bundle: T }
export declare type BundleId<T = unknown> = { bundleId: T }
export declare type BundleIds<T = unknown> = { bundleIds: T }
export declare type Bundles<T = unknown> = { bundles: T }
export declare type Cache<T = unknown> = { cache: T }
export declare type CacheId<T = unknown> = { cacheId: T }
export declare type CacheIds<T = unknown> = { cacheIds: T }
export declare type Callback<T = unknown> = { callback: T }
export declare type Campaign<T = unknown> = { campaign: T }
export declare type CampaignId<T = unknown> = { campaignId: T }
export declare type CampaignIds<T = unknown> = { campaignIds: T }
export declare type CampaignName<T = unknown> = { campaignName: T }
export declare type CampaignNames<T = unknown> = { campaignNames: T }
export declare type Campaigns<T = unknown> = { campaigns: T }
export declare type Cancel<T = unknown> = { cancel: T }
export declare type Canceled<T = unknown> = { canceled: T }
export declare type Card<T = unknown> = { card: T }
export declare type CardId<T = unknown> = { cardId: T }
export declare type CardIds<T = unknown> = { cardIds: T }
export declare type Cards<T = unknown> = { cards: T }
export declare type Cascade<T = unknown> = { cascade: T }
export declare type Categories<T = unknown> = { categories: T }
export declare type Category<T = unknown> = { category: T }
export declare type CategoryId<T = unknown> = { categoryId: T }
export declare type CategoryIds<T = unknown> = { categoryIds: T }
export declare type CategoryName<T = unknown> = { categoryName: T }
export declare type Cert<T = unknown> = { cert: T }
export declare type Certificate<T = unknown> = { certificate: T }
export declare type CertificateId<T = unknown> = { certificatId: T }
export declare type CertificateIds<T = unknown> = { certificatIds: T }
export declare type Certificates<T = unknown> = { certificates: T }
export declare type Channel<T = unknown> = { channel: T }
export declare type ChannelId<T = unknown> = { channelId: T }
export declare type ChannelIds<T = unknown> = { channelIds: T }
export declare type ChannelName<T = unknown> = { channelName: T }
export declare type Channels<T = unknown> = { channels: T }
export declare type ChargedAt<T = unknown> = { chargedAt: T }
export declare type Chunk<T = unknown> = { chunk: T }
export declare type ChunkId<T = unknown> = { chunkId: T }
export declare type ChunkIds<T = unknown> = { chunkIds: T }
export declare type ChunkSize<T = unknown> = { chunkSize: T }
export declare type Chunks<T = unknown> = { chunks: T }
export declare type City<T = unknown> = { city: T }
export declare type Class<T = unknown> = { class: T }
export declare type ClassId<T = unknown> = { classId: T }
export declare type ClassIds<T = unknown> = { classIds: T }
export declare type Classes<T = unknown> = { classes: T }
export declare type ClickId<T = unknown> = { clickId: T }
export declare type ClickIds<T = unknown> = { clickIds: T }
export declare type Clicks<T = unknown> = { clicks: T }
export declare type Client<T = unknown> = { client: T }
export declare type ClientId<T = unknown> = { clientId: T }
export declare type ClientIds<T = unknown> = { clientIds: T }
export declare type Clients<T = unknown> = { clients: T }
export declare type Cluster<T = unknown> = { cluster: T }
export declare type ClusterId<T = unknown> = { clusterId: T }
export declare type ClusterIds<T = unknown> = { clusterIds: T }
export declare type ClusterMode<T = unknown> = { clusterMode: T }
export declare type Clusters<T = unknown> = { clusters: T }
export declare type Code<T = unknown> = { code: T }
export declare type Codes<T = unknown> = { codes: T }
export declare type Collection<T = unknown> = { collection: T }
export declare type CollectionId<T = unknown> = { collectionId: T }
export declare type CollectionIds<T = unknown> = { collectionIds: T }
export declare type CollectionName<T = unknown> = { collectionName: T }
export declare type Collections<T = unknown> = { collections: T }
export declare type Color<T = unknown> = { color: T }
export declare type Colors<T = unknown> = { colors: T }
export declare type Column<T = unknown> = { column: T }
export declare type ColumnId<T = unknown> = { columnId: T }
export declare type ColumnIds<T = unknown> = { columnIds: T }
export declare type ColumnName<T = unknown> = { columnName: T }
export declare type Columns<T = unknown> = { columns: T }
export declare type Comment<T = unknown> = { comment: T }
export declare type CommentId<T = unknown> = { commentId: T }
export declare type CommentIds<T = unknown> = { commentIds: T }
export declare type Comments<T = unknown> = { comments: T }
export declare type CompletedAt<T = unknown> = { completedAt: T }
export declare type Compressed<T = unknown> = { compressed: T }
export declare type Config<T = unknown> = { config: T }
export declare type ConfigId<T = unknown> = { configId: T }
export declare type ConfigIds<T = unknown> = { configIds: T }
export declare type ConfigName<T = unknown> = { configName: T }
export declare type ConfigPath<T = unknown> = { configPath: T }
export declare type ConfigUrl<T = unknown> = { configUrl: T }
export declare type Configs<T = unknown> = { configs: T }
export declare type Constant<T = unknown> = { constant: T }
export declare type Constraint<T = unknown> = { constraint: T }
export declare type Constraints<T = unknown> = { constraints: T }
export declare type Constructor<T = unknown> = { constructor: T }
export declare type Consumer<T = unknown> = { consumer: T }
export declare type ConsumerId<T = unknown> = { consumerId: T }
export declare type ConsumerIds<T = unknown> = { consumerIds: T }
export declare type Consumers<T = unknown> = { consumers: T }
export declare type Content<T = unknown> = { content: T }
export declare type Context<T = unknown> = { context: T }
export declare type Controller<T = unknown> = { controller: T }
export declare type Controllers<T = unknown> = { controllers: T }
export declare type Cors<T = unknown> = { cors: T }
export declare type Cost<T = unknown> = { cost: T }
export declare type Count<T = unknown> = { count: T }
export declare type Country<T = unknown> = { country: T }
export declare type CountryCode<T = unknown> = { countryCode: T }
export declare type Create<T = unknown> = { create: T }
export declare type CreatedAt<T = unknown> = { createdAt: T }
export declare type Creative<T = unknown> = { creative: T }
export declare type CreativeId<T = unknown> = { creativeId: T }
export declare type CreativeIds<T = unknown> = { creativeIds: T }
export declare type CreativeName<T = unknown> = { creativeName: T }
export declare type Creatives<T = unknown> = { creatives: T }
export declare type Credentials<T = unknown> = { credentials: T }
export declare type Csv<T = unknown> = { csv: T }
export declare type Currencies<T = unknown> = { currencies: T }
export declare type Currency<T = unknown> = { currency: T }
export declare type CurrencyCode<T = unknown> = { currencyCode: T }
export declare type Cursor<T = unknown> = { cursor: T }
export declare type Customer<T = unknown> = { customer: T }
export declare type CustomerEmail<T = unknown> = { customerEmail: T }
export declare type CustomerId<T = unknown> = { customerId: T }
export declare type CustomerIds<T = unknown> = { customerIds: T }
export declare type Customers<T = unknown> = { customers: T }
export declare type Data<T = unknown> = { data: T }
export declare type Database<T = unknown> = { database: T }
export declare type DatabaseHost<T = unknown> = { databaseHost: T }
export declare type DatabaseName<T = unknown> = { databaseName: T }
export declare type DatabasePort<T = unknown> = { databasePort: T }
export declare type DatabaseUrl<T = unknown> = { databaseUrl: T }
export declare type Databases<T = unknown> = { databases: T }
export declare type Date<T = unknown> = { date: T }
export declare type Dates<T = unknown> = { dates: T }
export declare type Day<T = unknown> = { day: T }
export declare type Days<T = unknown> = { days: T }
export declare type DeadLetter<T = unknown> = { deadLetter: T }
export declare type DeadLetters<T = unknown> = { deadLetters: T }
export declare type Debug<T = unknown> = { debug: T }
export declare type Decrement<T = unknown> = { decrement: T }
export declare type Default<T = unknown> = { default: T }
export declare type DefaultId<T = unknown> = { defaultId: T }
export declare type DefaultIds<T = unknown> = { defaultIds: T }
export declare type Defaults<T = unknown> = { defaults: T }
export declare type Delay<T = unknown> = { delay: T }
export declare type DelayMs<T = unknown> = { delayMs: T }
export declare type DelaySec<T = unknown> = { delaySec: T }
export declare type Delete<T = unknown> = { delete: T }
export declare type DeletedAt<T = unknown> = { deletedAt: T }
export declare type Dependences<T = unknown> = { dependences: T }
export declare type Depends<T = unknown> = { depends: T }
export declare type DependsOn<T = unknown> = { dependsOn: T }
export declare type Depth<T = unknown> = { depth: T }
export declare type Description<T = unknown> = { description: T }
export declare type DescriptionId<T = unknown> = { descriptionId: T }
export declare type DescriptionIds<T = unknown> = { descriptionIds: T }
export declare type Descriptions<T = unknown> = { descriptions: T }
export declare type Detail<T = unknown> = { detail: T }
export declare type DetailId<T = unknown> = { detailId: T }
export declare type DetailIds<T = unknown> = { detailIds: T }
export declare type Details<T = unknown> = { details: T }
export declare type Developer<T = unknown> = { developer: T }
export declare type DeveloperId<T = unknown> = { developerId: T }
export declare type DeveloperIds<T = unknown> = { developerIds: T }
export declare type Developers<T = unknown> = { developers: T }
export declare type Device<T = unknown> = { device: T }
export declare type DeviceId<T = unknown> = { deviceId: T }
export declare type DeviceIds<T = unknown> = { deviceIds: T }
export declare type Devices<T = unknown> = { devices: T }
export declare type Directories<T = unknown> = { directories: T }
export declare type Directory<T = unknown> = { directory: T }
export declare type DirectoryName<T = unknown> = { directoryName: T }
export declare type DirectoryPath<T = unknown> = { directoryPath: T }
export declare type Disabled<T = unknown> = { disabled: T }
export declare type Discount<T = unknown> = { discount: T }
export declare type DiscountId<T = unknown> = { discountId: T }
export declare type DiscountIds<T = unknown> = { discountIds: T }
export declare type Discounts<T = unknown> = { discounts: T }
export declare type Display<T = unknown> = { display: T }
export declare type Docs<T = unknown> = { docs: T }
export declare type Document<T = unknown> = { document: T }
export declare type DocumentId<T = unknown> = { documentId: T }
export declare type DocumentIds<T = unknown> = { documentIds: T }
export declare type Documents<T = unknown> = { documents: T }
export declare type Domain<T = unknown> = { domain: T }
export declare type DomainId<T = unknown> = { domainId: T }
export declare type DomainIds<T = unknown> = { domainIds: T }
export declare type DomainName<T = unknown> = { domainName: T }
export declare type DomainUrl<T = unknown> = { domainUrl: T }
export declare type Domains<T = unknown> = { domains: T }
export declare type Dto<T = unknown> = { dto: T }
export declare type Dtos<T = unknown> = { dtos: T }
export declare type Duplicate<T = unknown> = { duplicate: T }
export declare type DuplicateId<T = unknown> = { duplicateId: T }
export declare type DuplicateIds<T = unknown> = { duplicateIds: T }
export declare type DuplicateName<T = unknown> = { duplicateName: T }
export declare type Duplicates<T = unknown> = { duplicates: T }
export declare type Duration<T = unknown> = { duration: T }
export declare type Element<T = unknown> = { element: T }
export declare type ElementId<T = unknown> = { elementId: T }
export declare type ElementIds<T = unknown> = { elementIds: T }
export declare type Elements<T = unknown> = { elements: T }
export declare type Email<T = unknown> = { email: T }
export declare type Employee<T = unknown> = { employee: T }
export declare type EmployeeId<T = unknown> = { employeeId: T }
export declare type EmployeeIds<T = unknown> = { employeeIds: T }
export declare type Employees<T = unknown> = { employees: T }
export declare type Employer<T = unknown> = { employer: T }
export declare type EmployerId<T = unknown> = { employerId: T }
export declare type EmployerIds<T = unknown> = { employerIds: T }
export declare type Employers<T = unknown> = { employers: T }
export declare type Enabled<T = unknown> = { enabled: T }
export declare type Encoded<T = unknown> = { encoded: T }
export declare type Encoding<T = unknown> = { encoding: T }
export declare type EndDate<T = unknown> = { endDate: T }
export declare type EndTime<T = unknown> = { endTime: T }
export declare type Endpoint<T = unknown> = { endpoint: T }
export declare type Endpoints<T = unknown> = { endpoints: T }
export declare type Entities<T = unknown> = { entities: T }
export declare type Entity<T = unknown> = { entity: T }
export declare type EntityId<T = unknown> = { entityId: T }
export declare type EntityIds<T = unknown> = { entityIds: T }
export declare type Entries<T = unknown> = { entries: T }
export declare type Entry<T = unknown> = { entry: T }
export declare type EntryId<T = unknown> = { entryId: T }
export declare type EntryIds<T = unknown> = { entryIds: T }
export declare type Enum<T = unknown> = { enum: T }
export declare type Env<T = unknown> = { env: T }
export declare type EnvFilePath<T = unknown> = { envFilePath: T }
export declare type EnvKeys<T = unknown> = { envKeys: T }
export declare type Envar<T = unknown> = { envar: T }
export declare type Envars<T = unknown> = { envars: T }
export declare type Equals<T = unknown> = { equals: T }
export declare type Error<T = unknown> = { error: T }
export declare type Errors<T = unknown> = { errors: T }
export declare type Event<T = unknown> = { event: T }
export declare type EventId<T = unknown> = { eventId: T }
export declare type EventIds<T = unknown> = { eventIds: T }
export declare type EventName<T = unknown> = { eventName: T }
export declare type EventProperties<T = unknown> = { eventProperties: T }
export declare type EventTime<T = unknown> = { eventTime: T }
export declare type EventType<T = unknown> = { eventType: T }
export declare type Events<T = unknown> = { events: T }
export declare type Exact<T = unknown> = { exact: T }
export declare type Example<T = unknown> = { example: T }
export declare type ExampleId<T = unknown> = { exampleId: T }
export declare type ExampleIds<T = unknown> = { exampleIds: T }
export declare type ExamplePath<T = unknown> = { examplePath: T }
export declare type ExampleUrl<T = unknown> = { exampleUrl: T }
export declare type Examples<T = unknown> = { examples: T }
export declare type Exclude<T = unknown> = { exclude: T }
export declare type ExcludePath<T = unknown> = { excludePath: T }
export declare type ExcludePaths<T = unknown> = { excludePaths: T }
export declare type Exists<T = unknown> = { exists: T }
export declare type ExpireAt<T = unknown> = { expireAt: T }
export declare type Expires<T = unknown> = { expires: T }
export declare type Export<T = unknown> = { export: T }
export declare type Exports<T = unknown> = { exports: T }
export declare type ExposedHeaders<T = unknown> = { exposedHeaders: T }
export declare type Extention<T = unknown> = { extention: T }
export declare type Extentions<T = unknown> = { extentions: T }
export declare type External<T = unknown> = { external: T }
export declare type ExternalId<T = unknown> = { externalId: T }
export declare type ExternalIds<T = unknown> = { externalIds: T }
export declare type Externals<T = unknown> = { externals: T }
export declare type Factory<T = unknown> = { factory: T }
export declare type Fail<T = unknown> = { fail: T }
export declare type Failed<T = unknown> = { failed: T }
export declare type Failure<T = unknown> = { failure: T }
export declare type Field<T = unknown> = { field: T }
export declare type FieldId<T = unknown> = { fieldId: T }
export declare type FieldIds<T = unknown> = { fieldIds: T }
export declare type FieldName<T = unknown> = { fieldName: T }
export declare type Fields<T = unknown> = { fields: T }
export declare type File<T = unknown> = { file: T }
export declare type FileId<T = unknown> = { fileId: T }
export declare type FileIds<T = unknown> = { fileIds: T }
export declare type FileName<T = unknown> = { fileName: T }
export declare type FilePath<T = unknown> = { filePath: T }
export declare type FileSize<T = unknown> = { fileSize: T }
export declare type Files<T = unknown> = { files: T }
export declare type Filter<T = unknown> = { filter: T }
export declare type FilterId<T = unknown> = { filterId: T }
export declare type FilterIds<T = unknown> = { filterIds: T }
export declare type Filters<T = unknown> = { filters: T }
export declare type FinishedAt<T = unknown> = { finishedAt: T }
export declare type FirstName<T = unknown> = { firstName: T }
export declare type Folder<T = unknown> = { folder: T }
export declare type FolderId<T = unknown> = { folderId: T }
export declare type FolderIds<T = unknown> = { folderIds: T }
export declare type FolderPath<T = unknown> = { folderPath: T }
export declare type Folders<T = unknown> = { folders: T }
export declare type Font<T = unknown> = { font: T }
export declare type FontFamily<T = unknown> = { fontFamily: T }
export declare type FontId<T = unknown> = { fontId: T }
export declare type FontIds<T = unknown> = { fontIds: T }
export declare type FontName<T = unknown> = { fontName: T }
export declare type FontPath<T = unknown> = { fontPath: T }
export declare type FontUrl<T = unknown> = { fontUrl: T }
export declare type Fonts<T = unknown> = { fonts: T }
export declare type Force<T = unknown> = { force: T }
export declare type Form<T = unknown> = { form: T }
export declare type FormId<T = unknown> = { formId: T }
export declare type FormIds<T = unknown> = { formIds: T }
export declare type Format<T = unknown> = { format: T }
export declare type Formats<T = unknown> = { formats: T }
export declare type Forms<T = unknown> = { forms: T }
export declare type FromDate<T = unknown> = { fromDate: T }
export declare type FullName<T = unknown> = { fullName: T }
export declare type GID<T = unknown> = { gid: T }
export declare type GUID<T = unknown> = { guid: T }
export declare type Game<T = unknown> = { game: T }
export declare type GameId<T = unknown> = { gameId: T }
export declare type GameIds<T = unknown> = { gameIds: T }
export declare type Games<T = unknown> = { games: T }
export declare type Gender<T = unknown> = { gender: T }
export declare type Git<T = unknown> = { git: T }
export declare type Gitignore<T = unknown> = { gitignore: T }
export declare type Group<T = unknown> = { group: T }
export declare type GroupId<T = unknown> = { groupId: T }
export declare type GroupIds<T = unknown> = { groupIds: T }
export declare type GroupName<T = unknown> = { groupName: T }
export declare type Groups<T = unknown> = { groups: T }
export declare type Hash<T = unknown> = { hash: T }
export declare type Header<T = unknown> = { header: T }
export declare type Headers<T = unknown> = { headers: T }
export declare type HeadersTimeout<T = unknown> = { headersTimeout: T }
export declare type Height<T = unknown> = { height: T }
export declare type Hidden<T = unknown> = { hidden: T }
export declare type Home<T = unknown> = { home: T }
export declare type Homepage<T = unknown> = { homepage: T }
export declare type Hour<T = unknown> = { hour: T }
export declare type Hours<T = unknown> = { hours: T }
export declare type Html<T = unknown> = { html: T }
export declare type HttpOptions<T = unknown> = { httpOptions: T }
export declare type ID<T = unknown> = { id: T }
export declare type IDFA<T = unknown> = { idfa: T }
export declare type IDFV<T = unknown> = { idfv: T }
export declare type IOS<T = unknown> = { ios: T }
export declare type Icon<T = unknown> = { icon: T }
export declare type IconId<T = unknown> = { iconId: T }
export declare type IconIds<T = unknown> = { iconIds: T }
export declare type IconPath<T = unknown> = { iconPath: T }
export declare type IconUrl<T = unknown> = { iconUrl: T }
export declare type Icons<T = unknown> = { icons: T }
export declare type Image<T = unknown> = { image: T }
export declare type ImageId<T = unknown> = { imageId: T }
export declare type ImageIds<T = unknown> = { imageIds: T }
export declare type ImageName<T = unknown> = { imageName: T }
export declare type ImagePath<T = unknown> = { imagePath: T }
export declare type ImageUrl<T = unknown> = { imageUrl: T }
export declare type Images<T = unknown> = { images: T }
export declare type Import<T = unknown> = { import: T }
export declare type Imports<T = unknown> = { imports: T }
export declare type Impressions<T = unknown> = { impressions: T }
export declare type IncludePath<T = unknown> = { includePath: T }
export declare type IncludePaths<T = unknown> = { includePaths: T }
export declare type Increment<T = unknown> = { increment: T }
export declare type Index<T = unknown> = { index: T }
export declare type Info<T = unknown> = { info: T }
export declare type Inject<T = unknown> = { inject: T }
export declare type Insert<T = unknown> = { insert: T }
export declare type Insights<T = unknown> = { insights: T }
export declare type Installs<T = unknown> = { installs: T }
export declare type Internal<T = unknown> = { internal: T }
export declare type InternalId<T = unknown> = { internalId: T }
export declare type InternalIds<T = unknown> = { internalIds: T }
export declare type Internals<T = unknown> = { internals: T }
export declare type Invoice<T = unknown> = { invoice: T }
export declare type InvoiceId<T = unknown> = { invoiceId: T }
export declare type InvoiceIds<T = unknown> = { invoiceIds: T }
export declare type InvoiceStatus<T = unknown> = { invoiceStatus: T }
export declare type IpAddress<T = unknown> = { ipAddress: T }
export declare type IsDebug<T = unknown> = { isDebug: T }
export declare type IsDirty<T = unknown> = { isDirty: T }
export declare type IsEnable<T = unknown> = { isenable: T }
export declare type IsNullable<T = unknown> = { isNullable: T }
export declare type IsProduction<T = unknown> = { isproduction: T }
export declare type IsTrial<T = unknown> = { istrial: T }
export declare type Iso<T = unknown> = { iso: T }
export declare type Iss<T = unknown> = { iss: T }
export declare type Issue<T = unknown> = { issue: T }
export declare type IssueId<T = unknown> = { issueId: T }
export declare type IssueIds<T = unknown> = { issueIds: T }
export declare type Issuer<T = unknown> = { issuer: T }
export declare type Issues<T = unknown> = { issues: T }
export declare type Item<T = unknown> = { item: T }
export declare type ItemId<T = unknown> = { itemId: T }
export declare type ItemIds<T = unknown> = { itemIds: T }
export declare type ItemName<T = unknown> = { itemName: T }
export declare type Items<T = unknown> = { items: T }
export declare type Job<T = unknown> = { job: T }
export declare type JobId<T = unknown> = { jobId: T }
export declare type JobIds<T = unknown> = { jobIds: T }
export declare type Jobs<T = unknown> = { jobs: T }
export declare type Json<T = unknown> = { json: T }
export declare type KID<T = unknown> = { kid: T }
export declare type KeepAliveTimeout<T = unknown> = { keepAliveTimeout: T }
export declare type Key<T = unknown> = { key: T }
export declare type KeyId<T = unknown> = { keyId: T }
export declare type KeyIds<T = unknown> = { keyIds: T }
export declare type KeyName<T = unknown> = { keyName: T }
export declare type Keys<T = unknown> = { keys: T }
export declare type Keyword<T = unknown> = { keyword: T }
export declare type Keywords<T = unknown> = { keywords: T }
export declare type Kind<T = unknown> = { kind: T }
export declare type Lable<T = unknown> = { lable: T }
export declare type Language<T = unknown> = { language: T }
export declare type Languages<T = unknown> = { languages: T }
export declare type LastName<T = unknown> = { lastName: T }
export declare type Left<T = unknown> = { left: T }
export declare type Length<T = unknown> = { length: T }
export declare type Letter<T = unknown> = { letter: T }
export declare type LetterId<T = unknown> = { letterId: T }
export declare type LetterIds<T = unknown> = { letterIds: T }
export declare type Letters<T = unknown> = { letters: T }
export declare type Level<T = unknown> = { level: T }
export declare type LevelId<T = unknown> = { levelId: T }
export declare type LevelIds<T = unknown> = { levelIds: T }
export declare type Levels<T = unknown> = { levels: T }
export declare type License<T = unknown> = { license: T }
export declare type Limit<T = unknown> = { limit: T }
export declare type Limited<T = unknown> = { limited: T }
export declare type Link<T = unknown> = { link: T }
export declare type Links<T = unknown> = { links: T }
export declare type List<T = unknown> = { list: T }
export declare type ListId<T = unknown> = { listId: T }
export declare type ListIds<T = unknown> = { listIds: T }
export declare type Listener<T = unknown> = { listener: T }
export declare type ListenerId<T = unknown> = { listenerId: T }
export declare type ListenerIds<T = unknown> = { listenerIds: T }
export declare type Listeners<T = unknown> = { listeners: T }
export declare type Lists<T = unknown> = { lists: T }
export declare type Load<T = unknown> = { load: T }
export declare type Local<T = unknown> = { local: T }
export declare type LocalEnv<T = unknown> = { localEnv: T }
export declare type Location<T = unknown> = { location: T }
export declare type LocationId<T = unknown> = { locationId: T }
export declare type LocationIds<T = unknown> = { locationIds: T }
export declare type LocationName<T = unknown> = { locationName: T }
export declare type Locations<T = unknown> = { locations: T }
export declare type Log<T = unknown> = { log: T }
export declare type LogGroup<T = unknown> = { logGroup: T }
export declare type LogGroups<T = unknown> = { logGroups: T }
export declare type LogLevel<T = unknown> = { logLevel: T }
export declare type LogLevels<T = unknown> = { logLevels: T }
export declare type Logger<T = unknown> = { logger: T }
export declare type Logging<T = unknown> = { logging: T }
export declare type Login<T = unknown> = { login: T }
export declare type Logs<T = unknown> = { logs: T }
export declare type Main<T = unknown> = { main: T }
export declare type Margin<T = unknown> = { margin: T }
export declare type MarginBottom<T = unknown> = { marginBottom: T }
export declare type MarginLeft<T = unknown> = { marginLeft: T }
export declare type MarginRight<T = unknown> = { marginRight: T }
export declare type Marked<T = unknown> = { marked: T }
export declare type Master<T = unknown> = { master: T }
export declare type MasterId<T = unknown> = { masterId: T }
export declare type MasterIds<T = unknown> = { masterIds: T }
export declare type Masters<T = unknown> = { masters: T }
export declare type Material<T = unknown> = { material: T }
export declare type MaterialId<T = unknown> = { materialId: T }
export declare type MaterialIds<T = unknown> = { materialIds: T }
export declare type Materials<T = unknown> = { materials: T }
export declare type Matrix<T = unknown> = { matrix: T }
export declare type Max<T = unknown> = { max: T }
export declare type MaxLength<T = unknown> = { maxLength: T }
export declare type Merchant<T = unknown> = { merchant: T }
export declare type MerchantId<T = unknown> = { merchantId: T }
export declare type MerchantIds<T = unknown> = { merchantIds: T }
export declare type Merchants<T = unknown> = { merchants: T }
export declare type Message<T = unknown> = { message: T }
export declare type MessageId<T = unknown> = { messageId: T }
export declare type MessageIds<T = unknown> = { messageIds: T }
export declare type Messages<T = unknown> = { messages: T }
export declare type Meta<T = unknown> = { meta: T }
export declare type Metadata<T = unknown> = { metadata: T }
export declare type Method<T = unknown> = { method: T }
export declare type Methods<T = unknown> = { methods: T }
export declare type Metric<T = unknown> = { metric: T }
export declare type MetricId<T = unknown> = { metricId: T }
export declare type MetricIds<T = unknown> = { metricIds: T }
export declare type Metrics<T = unknown> = { metrics: T }
export declare type Migration<T = unknown> = { migration: T }
export declare type Migrations<T = unknown> = { migrations: T }
export declare type Milliseconds<T = unknown> = { milliseconds: T }
export declare type MimeType<T = unknown> = { mimeType: T }
export declare type Min<T = unknown> = { min: T }
export declare type MinLength<T = unknown> = { minLength: T }
export declare type Minutes<T = unknown> = { minutes: T }
export declare type Mode<T = unknown> = { mode: T }
export declare type Model<T = unknown> = { model: T }
export declare type ModelId<T = unknown> = { modelId: T }
export declare type ModelIds<T = unknown> = { modelIds: T }
export declare type ModelName<T = unknown> = { modelName: T }
export declare type Models<T = unknown> = { models: T }
export declare type Modes<T = unknown> = { modes: T }
export declare type Module<T = unknown> = { module: T }
export declare type Modules<T = unknown> = { modules: T }
export declare type Months<T = unknown> = { months: T }
export declare type Multiplier<T = unknown> = { multiplier: T }
export declare type Name<T = unknown> = { name: T }
export declare type Next<T = unknown> = { next: T }
export declare type NextPageUrl<T = unknown> = { nextPageUrl: T }
export declare type Node<T = unknown> = { node: T }
export declare type NodeId<T = unknown> = { nodeId: T }
export declare type NodeIds<T = unknown> = { nodeIds: T }
export declare type Nodes<T = unknown> = { nodes: T }
export declare type Note<T = unknown> = { note: T }
export declare type NoteId<T = unknown> = { noteId: T }
export declare type NoteIds<T = unknown> = { noteIds: T }
export declare type Notes<T = unknown> = { notes: T }
export declare type Notification<T = unknown> = { notification: T }
export declare type NotificationId<T = unknown> = { notificationId: T }
export declare type NotificationIds<T = unknown> = { notificationIds: T }
export declare type NotificationType<T = unknown> = { notificationType: T }
export declare type Notifications<T = unknown> = { notifications: T }
export declare type Nulluble<T = unknown> = { nullable: T }
export declare type OS<T = unknown> = { os: T }
export declare type Object<T = unknown> = { object: T }
export declare type ObjectId<T = unknown> = { objectId: T }
export declare type ObjectIds<T = unknown> = { objectIds: T }
export declare type Objects<T = unknown> = { objects: T }
export declare type Offer<T = unknown> = { offer: T }
export declare type OfferId<T = unknown> = { offerId: T }
export declare type OfferIds<T = unknown> = { offerIds: T }
export declare type Offers<T = unknown> = { offers: T }
export declare type Offset<T = unknown> = { offset: T }
export declare type OffsetX<T = unknown> = { offsetX: T }
export declare type OffsetY<T = unknown> = { offsetY: T }
export declare type OffsetZ<T = unknown> = { offsetZ: T }
export declare type Offsets<T = unknown> = { offsets: T }
export declare type OnCreate<T = unknown> = { onCreate: T }
export declare type OnDelete<T = unknown> = { onDelete: T }
export declare type OnUpdate<T = unknown> = { onUpdate: T }
export declare type Option<T = unknown> = { option: T }
export declare type Options<T = unknown> = { options: T }
export declare type Order<T = unknown> = { order: T }
export declare type OrderId<T = unknown> = { orderId: T }
export declare type OrderIds<T = unknown> = { orderIds: T }
export declare type Orders<T = unknown> = { orders: T }
export declare type Origin<T = unknown> = { origin: T }
export declare type OriginId<T = unknown> = { originId: T }
export declare type OriginIds<T = unknown> = { originIds: T }
export declare type Origins<T = unknown> = { origins: T }
export declare type Owner<T = unknown> = { owner: T }
export declare type OwnerId<T = unknown> = { ownerId: T }
export declare type OwnerIds<T = unknown> = { ownerIds: T }
export declare type OwnerName<T = unknown> = { ownerName: T }
export declare type Owners<T = unknown> = { owners: T }
export declare type PID<T = unknown> = { pid: T }
export declare type PIN<T = unknown> = { pin: T }
export declare type PUK<T = unknown> = { puk: T }
export declare type Package<T = unknown> = { package: T }
export declare type PackageId<T = unknown> = { packageId: T }
export declare type PackageIds<T = unknown> = { packageIds: T }
export declare type PackageName<T = unknown> = { packageName: T }
export declare type Packages<T = unknown> = { packages: T }
export declare type Padding<T = unknown> = { padding: T }
export declare type PaddingBottom<T = unknown> = { paddingBottom: T }
export declare type PaddingLeft<T = unknown> = { paddingLeft: T }
export declare type PaddingRight<T = unknown> = { paddingRight: T }
export declare type Page<T = unknown> = { page: T }
export declare type PageId<T = unknown> = { pageId: T }
export declare type PageIds<T = unknown> = { pageIds: T }
export declare type PageInfo<T = unknown> = { pageInfo: T }
export declare type PageSize<T = unknown> = { pageSize: T }
export declare type PageUrl<T = unknown> = { pageUrl: T }
export declare type Param<T = unknown> = { param: T }
export declare type Params<T = unknown> = { params: T }
export declare type Part<T = unknown> = { part: T }
export declare type PartId<T = unknown> = { partId: T }
export declare type PartIds<T = unknown> = { partIds: T }
export declare type Parts<T = unknown> = { parts: T }
export declare type Password<T = unknown> = { password: T }
export declare type Path<T = unknown> = { path: T }
export declare type Paths<T = unknown> = { paths: T }
export declare type Pause<T = unknown> = { pause: T }
export declare type Paused<T = unknown> = { paused: T }
export declare type PausedAt<T = unknown> = { pausedAt: T }
export declare type PausedFrom<T = unknown> = { pausedFrom: T }
export declare type PausedTo<T = unknown> = { pausedTo: T }
export declare type Payer<T = unknown> = { payer: T }
export declare type PayerId<T = unknown> = { payerId: T }
export declare type PayerIds<T = unknown> = { payerIds: T }
export declare type Payers<T = unknown> = { payers: T }
export declare type Payload<T = unknown> = { payload: T }
export declare type Permission<T = unknown> = { permission: T }
export declare type PermissionId<T = unknown> = { permissionId: T }
export declare type PermissionIds<T = unknown> = { permissionIds: T }
export declare type Permissions<T = unknown> = { permissions: T }
export declare type Placement<T = unknown> = { placement: T }
export declare type PlacementId<T = unknown> = { placementId: T }
export declare type PlacementIds<T = unknown> = { placementIds: T }
export declare type Placements<T = unknown> = { placements: T }
export declare type Platform<T = unknown> = { platform: T }
export declare type PlatformId<T = unknown> = { platformId: T }
export declare type PlatformIds<T = unknown> = { platformIds: T }
export declare type PlatformName<T = unknown> = { platformName: T }
export declare type Platforms<T = unknown> = { platforms: T }
export declare type Player<T = unknown> = { player: T }
export declare type PlayerId<T = unknown> = { playerId: T }
export declare type PlayerIds<T = unknown> = { playerIds: T }
export declare type Players<T = unknown> = { players: T }
export declare type Point<T = unknown> = { point: T }
export declare type PointId<T = unknown> = { pointId: T }
export declare type PointIds<T = unknown> = { pointIds: T }
export declare type Pointer<T = unknown> = { pointer: T }
export declare type Points<T = unknown> = { points: T }
export declare type Port<T = unknown> = { port: T }
export declare type Possition<T = unknown> = { possition: T }
export declare type PossitionX<T = unknown> = { possitionX: T }
export declare type PossitionY<T = unknown> = { possitionY: T }
export declare type PossitionZ<T = unknown> = { possitionZ: T }
export declare type Possitions<T = unknown> = { possitions: T }
export declare type Post<T = unknown> = { post: T }
export declare type PostId<T = unknown> = { postId: T }
export declare type PostIds<T = unknown> = { postIds: T }
export declare type PostalCode<T = unknown> = { postalCode: T }
export declare type Posts<T = unknown> = { posts: T }
export declare type Preferences<T = unknown> = { preferences: T }
export declare type Prefix<T = unknown> = { prefix: T }
export declare type Price<T = unknown> = { price: T }
export declare type Primary<T = unknown> = { primary: T }
export declare type Private<T = unknown> = { private: T }
export declare type PrivateKey<T = unknown> = { privateKey: T }
export declare type Product<T = unknown> = { product: T }
export declare type ProductId<T = unknown> = { productId: T }
export declare type ProductIds<T = unknown> = { productIds: T }
export declare type ProductName<T = unknown> = { productName: T }
export declare type Production<T = unknown> = { production: T }
export declare type Products<T = unknown> = { products: T }
export declare type Profile<T = unknown> = { profile: T }
export declare type ProfileId<T = unknown> = { profileId: T }
export declare type ProfileIds<T = unknown> = { profileIds: T }
export declare type Profiles<T = unknown> = { profiles: T }
export declare type Project<T = unknown> = { project: T }
export declare type ProjectId<T = unknown> = { projectId: T }
export declare type ProjectIds<T = unknown> = { projectIds: T }
export declare type Projects<T = unknown> = { projects: T }
export declare type Properties<T = unknown> = { properties: T }
export declare type Property<T = unknown> = { property: T }
export declare type PropertyId<T = unknown> = { propertyId: T }
export declare type PropertyIds<T = unknown> = { propertyIds: T }
export declare type Props<T = unknown> = { props: T }
export declare type Provider<T = unknown> = { provider: T }
export declare type Providers<T = unknown> = { providers: T }
export declare type Public<T = unknown> = { public: T }
export declare type PublicKey<T = unknown> = { publicKey: T }
export declare type PublicPath<T = unknown> = { publicPath: T }
export declare type Publication<T = unknown> = { publication: T }
export declare type PublicationId<T = unknown> = { publicationId: T }
export declare type PublicationIds<T = unknown> = { publicationIds: T }
export declare type Publications<T = unknown> = { publications: T }
export declare type Published<T = unknown> = { published: T }
export declare type PublishedAt<T = unknown> = { publishedAt: T }
export declare type Publisher<T = unknown> = { publisher: T }
export declare type PublisherId<T = unknown> = { publisherId: T }
export declare type PublisherIds<T = unknown> = { publisherIds: T }
export declare type PublisherName<T = unknown> = { publisherName: T }
export declare type Publishers<T = unknown> = { publishers: T }
export declare type Purchase<T = unknown> = { purchase: T }
export declare type PurchaseId<T = unknown> = { purchaseId: T }
export declare type PurchaseIds<T = unknown> = { purchaseIds: T }
export declare type PurchaseType<T = unknown> = { purchaseType: T }
export declare type Purchases<T = unknown> = { purchases: T }
export declare type Quantity<T = unknown> = { quantity: T }
export declare type Queries<T = unknown> = { queries: T }
export declare type Query<T = unknown> = { query: T }
export declare type Question<T = unknown> = { question: T }
export declare type QuestionId<T = unknown> = { questionId: T }
export declare type QuestionIds<T = unknown> = { questionIds: T }
export declare type Questions<T = unknown> = { questions: T }
export declare type Queue<T = unknown> = { queue: T }
export declare type QueueId<T = unknown> = { queueId: T }
export declare type QueueIds<T = unknown> = { queueIds: T }
export declare type QueueName<T = unknown> = { queueName: T }
export declare type QueueUrl<T = unknown> = { queueUrl: T }
export declare type Queues<T = unknown> = { queues: T }
export declare type Radius<T = unknown> = { radius: T }
export declare type Ratio<T = unknown> = { ratio: T }
export declare type Raw<T = unknown> = { raw: T }
export declare type RawBody<T = unknown> = { rawBody: T }
export declare type Reason<T = unknown> = { reason: T }
export declare type ReasonId<T = unknown> = { reasonId: T }
export declare type ReasonIds<T = unknown> = { reasonIds: T }
export declare type Reasons<T = unknown> = { reasons: T }
export declare type Receipt<T = unknown> = { receipt: T }
export declare type ReceiptId<T = unknown> = { receiptId: T }
export declare type ReceiptIds<T = unknown> = { receiptIds: T }
export declare type Receipts<T = unknown> = { receipts: T }
export declare type Ref<T = unknown> = { ref: T }
export declare type Reference<T = unknown> = { reference: T }
export declare type References<T = unknown> = { references: T }
export declare type RefreshToken<T = unknown> = { refreshToken: T }
export declare type RefundedAt<T = unknown> = { refundedAt: T }
export declare type Region<T = unknown> = { region: T }
export declare type RegionCode<T = unknown> = { regionCode: T }
export declare type Regions<T = unknown> = { regions: T }
export declare type Relation<T = unknown> = { relation: T }
export declare type RelationId<T = unknown> = { relationId: T }
export declare type RelationIds<T = unknown> = { relationIds: T }
export declare type Relations<T = unknown> = { relations: T }
export declare type Remote<T = unknown> = { remote: T }
export declare type Remove<T = unknown> = { remove: T }
export declare type Replica<T = unknown> = { replica: T }
export declare type ReplicaId<T = unknown> = { replicaId: T }
export declare type ReplicaIds<T = unknown> = { replicaIds: T }
export declare type ReplicaName<T = unknown> = { replicaName: T }
export declare type ReplicaUrl<T = unknown> = { replicaUrl: T }
export declare type Replicas<T = unknown> = { replicas: T }
export declare type Replication<T = unknown> = { replication: T }
export declare type ReplicationId<T = unknown> = { replicationId: T }
export declare type ReplicationIds<T = unknown> = { replicationIds: T }
export declare type Replications<T = unknown> = { replications: T }
export declare type Report<T = unknown> = { report: T }
export declare type ReportId<T = unknown> = { reportId: T }
export declare type ReportIds<T = unknown> = { reportIds: T }
export declare type Reports<T = unknown> = { reports: T }
export declare type Repositories<T = unknown> = { repositories: T }
export declare type Repository<T = unknown> = { repository: T }
export declare type RepositoryUrl<T = unknown> = { repositoryUrl: T }
export declare type Req<T = unknown> = { req: T }
export declare type Request<T = unknown> = { request: T }
export declare type RequestId<T = unknown> = { requestId: T }
export declare type RequestIds<T = unknown> = { requestIds: T }
export declare type Requests<T = unknown> = { requests: T }
export declare type Res<T = unknown> = { res: T }
export declare type Resource<T = unknown> = { resource: T }
export declare type ResourceId<T = unknown> = { resourceId: T }
export declare type ResourceIds<T = unknown> = { resourceIds: T }
export declare type ResourceName<T = unknown> = { resourceName: T }
export declare type ResourcePath<T = unknown> = { resourcePath: T }
export declare type ResourceUrl<T = unknown> = { resourceUrl: T }
export declare type Resources<T = unknown> = { resources: T }
export declare type Response<T = unknown> = { response: T }
export declare type ResponseId<T = unknown> = { responseId: T }
export declare type ResponseIds<T = unknown> = { responseIds: T }
export declare type Responses<T = unknown> = { responses: T }
export declare type Result<T = unknown> = { result: T }
export declare type ResultId<T = unknown> = { resultId: T }
export declare type ResultIds<T = unknown> = { resultIds: T }
export declare type Results<T = unknown> = { results: T }
export declare type Right<T = unknown> = { right: T }
export declare type Role<T = unknown> = { role: T }
export declare type RoleId<T = unknown> = { roleId: T }
export declare type RoleIds<T = unknown> = { roleIds: T }
export declare type RoleName<T = unknown> = { roleName: T }
export declare type Roles<T = unknown> = { roles: T }
export declare type Rotation<T = unknown> = { rotation: T }
export declare type RotationX<T = unknown> = { rotationX: T }
export declare type RotationY<T = unknown> = { rotationY: T }
export declare type RotationZ<T = unknown> = { rotationZ: T }
export declare type Rotations<T = unknown> = { rotations: T }
export declare type Route<T = unknown> = { route: T }
export declare type Routes<T = unknown> = { routes: T }
export declare type Row<T = unknown> = { row: T }
export declare type RowId<T = unknown> = { rowId: T }
export declare type RowIds<T = unknown> = { rowIds: T }
export declare type Rows<T = unknown> = { rows: T }
export declare type SETID<T = unknown> = { setid: T }
export declare type SSL<T = unknown> = { ssl: T }
export declare type Salt<T = unknown> = { salt: T }
export declare type Scale<T = unknown> = { scale: T }
export declare type ScaleX<T = unknown> = { scaleX: T }
export declare type ScaleY<T = unknown> = { scaleY: T }
export declare type ScaleZ<T = unknown> = { scaleZ: T }
export declare type Scales<T = unknown> = { scales: T }
export declare type Schema<T = unknown> = { schema: T }
export declare type SchemaId<T = unknown> = { schemaId: T }
export declare type SchemaIds<T = unknown> = { schemaIds: T }
export declare type SchemaName<T = unknown> = { schemaName: T }
export declare type Schemas<T = unknown> = { schemas: T }
export declare type Scope<T = unknown> = { scope: T }
export declare type Scopes<T = unknown> = { scopes: T }
export declare type Screen<T = unknown> = { screen: T }
export declare type Sdk<T = unknown> = { sdk: T }
export declare type Secondary<T = unknown> = { secondary: T }
export declare type Seconds<T = unknown> = { seconds: T }
export declare type Secret<T = unknown> = { secret: T }
export declare type SecretKey<T = unknown> = { secretKey: T }
export declare type Select<T = unknown> = { select: T }
export declare type Selected<T = unknown> = { selected: T }
export declare type Selector<T = unknown> = { selector: T }
export declare type Sender<T = unknown> = { sender: T }
export declare type SenderId<T = unknown> = { senderId: T }
export declare type SenderIds<T = unknown> = { senderIds: T }
export declare type SenderName<T = unknown> = { senderName: T }
export declare type Senders<T = unknown> = { senders: T }
export declare type Separator<T = unknown> = { separator: T }
export declare type Sequence<T = unknown> = { sequence: T }
export declare type SequenceId<T = unknown> = { sequenceId: T }
export declare type SequenceIds<T = unknown> = { sequenceIds: T }
export declare type Sequences<T = unknown> = { sequences: T }
export declare type Server<T = unknown> = { server: T }
export declare type ServerHost<T = unknown> = { serverHost: T }
export declare type ServerPort<T = unknown> = { serverPort: T }
export declare type ServerUrl<T = unknown> = { serverUrl: T }
export declare type Service<T = unknown> = { service: T }
export declare type ServiceId<T = unknown> = { serviceId: T }
export declare type ServiceIds<T = unknown> = { serviceIds: T }
export declare type ServiceName<T = unknown> = { serviceName: T }
export declare type ServicePath<T = unknown> = { servicePath: T }
export declare type ServiceUrl<T = unknown> = { serviceUrl: T }
export declare type Services<T = unknown> = { services: T }
export declare type Session<T = unknown> = { session: T }
export declare type SessionId<T = unknown> = { sessionId: T }
export declare type SessionIds<T = unknown> = { sessionIds: T }
export declare type Sessions<T = unknown> = { sessions: T }
export declare type Set<T = unknown> = { set: T }
export declare type SetId<T = unknown> = { setId: T }
export declare type SetIds<T = unknown> = { setIds: T }
export declare type Sets<T = unknown> = { sets: T }
export declare type Settings<T = unknown> = { settings: T }
export declare type Setup<T = unknown> = { setup: T }
export declare type SetupId<T = unknown> = { setupId: T }
export declare type SetupIds<T = unknown> = { setupIds: T }
export declare type Setups<T = unknown> = { setups: T }
export declare type Signature<T = unknown> = { signature: T }
export declare type Size<T = unknown> = { size: T }
export declare type Skip<T = unknown> = { skip: T }
export declare type Slave<T = unknown> = { slave: T }
export declare type SlaveId<T = unknown> = { slaveId: T }
export declare type SlaveIds<T = unknown> = { slaveIds: T }
export declare type Slaves<T = unknown> = { slaves: T }
export declare type Snapshot<T = unknown> = { snapshot: T }
export declare type SnapshotId<T = unknown> = { snapshotId: T }
export declare type SnapshotIds<T = unknown> = { snapshotIds: T }
export declare type SnapshotUrl<T = unknown> = { snapshotUrl: T }
export declare type Snapshots<T = unknown> = { snapshots: T }
export declare type Sort<T = unknown> = { sort: T }
export declare type Source<T = unknown> = { source: T }
export declare type Spend<T = unknown> = { spend: T }
export declare type Spends<T = unknown> = { spends: T }
export declare type StartDate<T = unknown> = { startDate: T }
export declare type StartTime<T = unknown> = { startTime: T }
export declare type StartedAt<T = unknown> = { startedAt: T }
export declare type State<T = unknown> = { state: T }
export declare type States<T = unknown> = { states: T }
export declare type Stats<T = unknown> = { stats: T }
export declare type Status<T = unknown> = { status: T }
export declare type Strategies<T = unknown> = { strategies: T }
export declare type Strategy<T = unknown> = { strategy: T }
export declare type StrategyId<T = unknown> = { strategyId: T }
export declare type StrategyIds<T = unknown> = { strategyIds: T }
export declare type StrategyName<T = unknown> = { strategyName: T }
export declare type Stream<T = unknown> = { stream: T }
export declare type StreamId<T = unknown> = { streamId: T }
export declare type StreamIds<T = unknown> = { streamIds: T }
export declare type StreamName<T = unknown> = { streamName: T }
export declare type Streams<T = unknown> = { streams: T }
export declare type Subject<T = unknown> = { subject: T }
export declare type SubjectId<T = unknown> = { subjectId: T }
export declare type SubjectIds<T = unknown> = { subjectIds: T }
export declare type Subjects<T = unknown> = { subjects: T }
export declare type Subscriber<T = unknown> = { subscriber: T }
export declare type SubscriberId<T = unknown> = { subscriberId: T }
export declare type SubscriberIds<T = unknown> = { subscriberIds: T }
export declare type Subscribers<T = unknown> = { subscribers: T }
export declare type Subscription<T = unknown> = { subscription: T }
export declare type SubscriptionId<T = unknown> = { subscriptionId: T }
export declare type SubscriptionIds<T = unknown> = { subscriptionIds: T }
export declare type Subscriptions<T = unknown> = { subscriptions: T }
export declare type Success<T = unknown> = { success: T }
export declare type Sum<T = unknown> = { sum: T }
export declare type Summary<T = unknown> = { summary: T }
export declare type Synchronize<T = unknown> = { synchronize: T }
export declare type Table<T = unknown> = { table: T }
export declare type TableId<T = unknown> = { tableId: T }
export declare type TableIds<T = unknown> = { tableIds: T }
export declare type TableName<T = unknown> = { tableName: T }
export declare type Tables<T = unknown> = { tables: T }
export declare type Tag<T = unknown> = { tag: T }
export declare type TagId<T = unknown> = { tagId: T }
export declare type TagIds<T = unknown> = { tagIds: T }
export declare type Tags<T = unknown> = { tags: T }
export declare type Take<T = unknown> = { take: T }
export declare type Target<T = unknown> = { target: T }
export declare type TargetId<T = unknown> = { targetId: T }
export declare type TargetIds<T = unknown> = { targetIds: T }
export declare type Targets<T = unknown> = { targets: T }
export declare type Task<T = unknown> = { task: T }
export declare type TaskId<T = unknown> = { taskId: T }
export declare type TaskIds<T = unknown> = { taskIds: T }
export declare type Tasks<T = unknown> = { tasks: T }
export declare type Taxes<T = unknown> = { taxes: T }
export declare type Template<T = unknown> = { template: T }
export declare type TemplateId<T = unknown> = { templateId: T }
export declare type TemplateIds<T = unknown> = { templateIds: T }
export declare type TemplateName<T = unknown> = { templateName: T }
export declare type TemplatePath<T = unknown> = { templatePath: T }
export declare type TemplateUrl<T = unknown> = { templateUrl: T }
export declare type Templates<T = unknown> = { templates: T }
export declare type Text<T = unknown> = { text: T }
export declare type TextSize<T = unknown> = { textSize: T }
export declare type Throttle<T = unknown> = { throttle: T }
export declare type ThrottleMs<T = unknown> = { throttleMs: T }
export declare type ThrottleSec<T = unknown> = { throttleSec: T }
export declare type Ticket<T = unknown> = { ticket: T }
export declare type TicketId<T = unknown> = { ticketId: T }
export declare type TicketIds<T = unknown> = { ticketIds: T }
export declare type Tickets<T = unknown> = { tickets: T }
export declare type Time<T = unknown> = { time: T }
export declare type TimeUtc<T = unknown> = { timeUtc: T }
export declare type Timeout<T = unknown> = { timeout: T }
export declare type Timestamp<T = unknown> = { timestamp: T }
export declare type Timezone<T = unknown> = { timezone: T }
export declare type TimezoneOffset<T = unknown> = { timezoneOffset: T }
export declare type Title<T = unknown> = { title: T }
export declare type Tmp<T = unknown> = { tmp: T }
export declare type TmpPath<T = unknown> = { tmpPath: T }
export declare type ToDate<T = unknown> = { toDate: T }
export declare type Token<T = unknown> = { token: T }
export declare type TokenId<T = unknown> = { tokenId: T }
export declare type TokenIds<T = unknown> = { tokenIds: T }
export declare type TokenType<T = unknown> = { tokenType: T }
export declare type Tokens<T = unknown> = { tokens: T }
export declare type Top<T = unknown> = { top: T }
export declare type Topic<T = unknown> = { topic: T }
export declare type TopicId<T = unknown> = { topicId: T }
export declare type TopicIds<T = unknown> = { topicIds: T }
export declare type TopicName<T = unknown> = { topicName: T }
export declare type Topics<T = unknown> = { topics: T }
export declare type Town<T = unknown> = { town: T }
export declare type Transaction<T = unknown> = { transaction: T }
export declare type TransactionId<T = unknown> = { transactionId: T }
export declare type TransactionIds<T = unknown> = { transactionIds: T }
export declare type Transactions<T = unknown> = { transactions: T }
export declare type Transformer<T = unknown> = { transformer: T }
export declare type Trial<T = unknown> = { trial: T }
export declare type Ttl<T = unknown> = { ttl: T }
export declare type TtlMs<T = unknown> = { ttlMs: T }
export declare type TtlSec<T = unknown> = { ttlSec: T }
export declare type Type<T = unknown> = { type: T }
export declare type TypeId<T = unknown> = { typeId: T }
export declare type TypeIds<T = unknown> = { typeIds: T }
export declare type Types<T = unknown> = { types: T }
export declare type UUID<T = unknown> = { uuid: T }
export declare type Unique<T = unknown> = { unique: T }
export declare type UniqueId<T = unknown> = { uniqueId: T }
export declare type UniqueIds<T = unknown> = { uniqueIds: T }
export declare type Uniques<T = unknown> = { uniques: T }
export declare type Update<T = unknown> = { update: T }
export declare type UpdatedAt<T = unknown> = { updatedAt: T }
export declare type Uri<T = unknown> = { uri: T }
export declare type Url<T = unknown> = { url: T }
export declare type User<T = unknown> = { user: T }
export declare type UserAgent<T = unknown> = { userAgent: T }
export declare type UserData<T = unknown> = { userData: T }
export declare type UserId<T = unknown> = { userId: T }
export declare type UserIds<T = unknown> = { userIds: T }
export declare type UserName<T = unknown> = { userName: T }
export declare type UserPassword<T = unknown> = { userPassword: T }
export declare type UserProperties<T = unknown> = { userProperties: T }
export declare type Username<T = unknown> = { username: T }
export declare type Users<T = unknown> = { users: T }
export declare type Utc<T = unknown> = { utc: T }
export declare type Value<T = unknown> = { value: T }
export declare type Values<T = unknown> = { values: T }
export declare type Vars<T = unknown> = { vars: T }
export declare type Vector<T = unknown> = { vector: T }
export declare type VendorId<T = unknown> = { vendorId: T }
export declare type VendorIds<T = unknown> = { vendorIds: T }
export declare type Verbose<T = unknown> = { verbose: T }
export declare type Version<T = unknown> = { version: T }
export declare type Video<T = unknown> = { video: T }
export declare type VideoId<T = unknown> = { videoId: T }
export declare type VideoIds<T = unknown> = { videoIds: T }
export declare type VideoName<T = unknown> = { videoName: T }
export declare type VideoUrl<T = unknown> = { videoUrl: T }
export declare type Videos<T = unknown> = { videos: T }
export declare type View<T = unknown> = { view: T }
export declare type ViewId<T = unknown> = { viewId: T }
export declare type ViewIds<T = unknown> = { viewIds: T }
export declare type Views<T = unknown> = { views: T }
export declare type Visitor<T = unknown> = { visitor: T }
export declare type VisitorId<T = unknown> = { visitorId: T }
export declare type VisitorIds<T = unknown> = { visitorIds: T }
export declare type Visitors<T = unknown> = { visitors: T }
export declare type Warning<T = unknown> = { warning: T }
export declare type Web<T = unknown> = { web: T }
export declare type Webhook<T = unknown> = { webhook: T }
export declare type WebhookUrl<T = unknown> = { webhookUrl: T }
export declare type Webhooks<T = unknown> = { webhooks: T }
export declare type Week<T = unknown> = { week: T }
export declare type Weeks<T = unknown> = { weeks: T }
export declare type Weight<T = unknown> = { weight: T }
export declare type Where<T = unknown> = { where: T }
export declare type Width<T = unknown> = { width: T }
export declare type X<T = unknown> = { x: T }
export declare type Y<T = unknown> = { y: T }
export declare type Year<T = unknown> = { year: T }
export declare type Years<T = unknown> = { years: T }
export declare type Z<T = unknown> = { z: T }
export declare type ZIndex<T = unknown> = { zIndex: T }
export declare type Zip<T = unknown> = { zip: T }
export declare type ZipCode<T = unknown> = { zipCode: T }
export declare type Ziped<T = unknown> = { ziped: T }