export type AAID<T = unknown> = { aaid: T }
export type About<T = unknown> = { about: T }
export type AccessKey<T = unknown> = { access_key: T }
export type AccessKeyId<T = unknown> = { access_key_id: T }
export type AccessKeyName<T = unknown> = { access_key_name: T }
export type AccessPoint<T = unknown> = { access_point: T }
export type AccessToken<T = unknown> = { access_token: T }
export type Account<T = unknown> = { account: T }
export type AccountId<T = unknown> = { account_id: T }
export type AccountIds<T = unknown> = { account_ids: T }
export type AccountName<T = unknown> = { account_name: T }
export type Accounts<T = unknown> = { accounts: T }
export type Action<T = unknown> = { action: T }
export type Activator<T = unknown> = { activator: T }
export type ActivatorId<T = unknown> = { activator_id: T }
export type ActivatorIds<T = unknown> = { activator_ids: T }
export type ActivatorName<T = unknown> = { activator_name: T }
export type Activators<T = unknown> = { activators: T }
export type Ad<T = unknown> = { ad: T }
export type AdGroup<T = unknown> = { adgroup: T }
export type AdGroupId<T = unknown> = { adgroup_id: T }
export type AdGroupIds<T = unknown> = { adgroup_ids: T }
export type AdGroupName<T = unknown> = { adgroup_name: T }
export type AdId<T = unknown> = { ad_id: T }
export type AdIds<T = unknown> = { ad_ids: T }
export type AdName<T = unknown> = { ad_name: T }
export type Add<T = unknown> = { add: T }
export type Address<T = unknown> = { address: T }
export type Addresses<T = unknown> = { addresses: T }
export type Adgroups<T = unknown> = { adgroups: T }
export type Admin<T = unknown> = { admin: T }
export type AdminId<T = unknown> = { admin_id: T }
export type AdminIds<T = unknown> = { admin_ids: T }
export type AdminUrl<T = unknown> = { admin_url: T }
export type Admins<T = unknown> = { admins: T }
export type Ads<T = unknown> = { ads: T }
export type Adset<T = unknown> = { adset: T }
export type AdsetId<T = unknown> = { adset_id: T }
export type AdsetIds<T = unknown> = { adset_ids: T }
export type AdsetName<T = unknown> = { adset_name: T }
export type Advanced<T = unknown> = { advanced: T }
export type Advertiser<T = unknown> = { advertiser: T }
export type AdvertiserId<T = unknown> = { advertiser_id: T }
export type AdvertiserIds<T = unknown> = { advertiser_ids: T }
export type Advertisers<T = unknown> = { advertisers: T }
export type Age<T = unknown> = { age: T }
export type AgeGroup<T = unknown> = { age_group: T }
export type Airtable<T = unknown> = { airtable: T }
export type Album<T = unknown> = { album: T }
export type AlbumId<T = unknown> = { album_id: T }
export type AlbumIds<T = unknown> = { album_ids: T }
export type AlbumName<T = unknown> = { album_name: T }
export type Albums<T = unknown> = { albums: T }
export type Alg<T = unknown> = { alg: T }
export type Alias<T = unknown> = { alias: T }
export type Align<T = unknown> = { align: T }
export type All<T = unknown> = { all: T }
export type Amount<T = unknown> = { amount: T }
export type Amplitude<T = unknown> = { amplitude: T }
export type Android<T = unknown> = { android: T }
export type Answer<T = unknown> = { answer: T }
export type AnswerId<T = unknown> = { answer_id: T }
export type AnswerIds<T = unknown> = { answer_ids: T }
export type Answers<T = unknown> = { answers: T }
export type Api<T = unknown> = { api: T }
export type ApiKey<T = unknown> = { api_key: T }
export type ApiKeys<T = unknown> = { api_keys: T }
export type ApiSecret<T = unknown> = { api_secret: T }
export type ApiUrl<T = unknown> = { api_url: T }
export type App<T = unknown> = { app: T }
export type AppId<T = unknown> = { app_id: T }
export type AppIds<T = unknown> = { app_ids: T }
export type Apple<T = unknown> = { apple: T }
export type Application<T = unknown> = { application: T }
export type ApplicationId<T = unknown> = { application_id: T }
export type ApplicationIds<T = unknown> = { application_ids: T }
export type Applications<T = unknown> = { applications: T }
export type Applovin<T = unknown> = { applovin: T }
export type Apps<T = unknown> = { apps: T }
export type Appsflyer<T = unknown> = { appsflyer: T }
export type AppsflyerId<T = unknown> = { appsflyer_id: T }
export type Arg<T = unknown> = { arg: T }
export type Args<T = unknown> = { args: T }
export type Asset<T = unknown> = { asset: T }
export type AssetHash<T = unknown> = { asset_hash: T }
export type AssetId<T = unknown> = { asset_id: T }
export type AssetIds<T = unknown> = { asset_ids: T }
export type AssetName<T = unknown> = { asset_name: T }
export type Assets<T = unknown> = { assets: T }
export type Attempt<T = unknown> = { attempt: T }
export type Attempts<T = unknown> = { attempts: T }
export type Attribute<T = unknown> = { attribute: T }
export type AttributeId<T = unknown> = { attribute_id: T }
export type AttributeIds<T = unknown> = { attribute_ids: T }
export type Attributes<T = unknown> = { attributes: T }
export type Auth<T = unknown> = { auth: T }
export type AuthProvider<T = unknown> = { auth_provider: T }
export type Authorized<T = unknown> = { authorized: T }
export type Auto<T = unknown> = { auto: T }
export type AutoLoad<T = unknown> = { auto_load: T }
export type AutoRun<T = unknown> = { auto_run: T }
export type Aws<T = unknown> = { aws: T }
export type BID<T = unknown> = { bid: T }
export type Background<T = unknown> = { background: T }
export type BackgroundColor<T = unknown> = { background_color: T }
export type Badge<T = unknown> = { badge: T }
export type BadgeId<T = unknown> = { badge_id: T }
export type BadgeIds<T = unknown> = { badge_ids: T }
export type Badges<T = unknown> = { badges: T }
export type Base<T = unknown> = { base: T }
export type BaseId<T = unknown> = { base_id: T }
export type BaseUrl<T = unknown> = { base_url: T }
export type Blacklist<T = unknown> = { blacklist: T }
export type Block<T = unknown> = { block: T }
export type BlockId<T = unknown> = { block_id: T }
export type BlockIds<T = unknown> = { block_ids: T }
export type Blocked<T = unknown> = { blocked: T }
export type Blocks<T = unknown> = { blocks: T }
export type Blueprint<T = unknown> = { blueprint: T }
export type BlueprintId<T = unknown> = { blueprint_id: T }
export type BlueprintIds<T = unknown> = { blueprint_ids: T }
export type BlueprintName<T = unknown> = { blueprint_name: T }
export type Blueprints<T = unknown> = { blueprints: T }
export type Body<T = unknown> = { body: T }
export type Border<T = unknown> = { border: T }
export type Bottom<T = unknown> = { bottom: T }
export type Bucket<T = unknown> = { bucket: T }
export type BucketId<T = unknown> = { bucket_id: T }
export type BucketIds<T = unknown> = { bucket_ids: T }
export type BucketName<T = unknown> = { bucket_name: T }
export type BucketUrl<T = unknown> = { bucket_url: T }
export type Buckets<T = unknown> = { buckets: T }
export type Budget<T = unknown> = { budget: T }
export type BudgetMode<T = unknown> = { budget_mode: T }
export type Buffer<T = unknown> = { buffer: T }
export type Builder<T = unknown> = { builder: T }
export type Bundle<T = unknown> = { bundle: T }
export type BundleId<T = unknown> = { bundle_id: T }
export type BundleIds<T = unknown> = { bundle_ids: T }
export type Bundles<T = unknown> = { bundles: T }
export type Cache<T = unknown> = { cache: T }
export type CacheId<T = unknown> = { cache_id: T }
export type CacheIds<T = unknown> = { cache_ids: T }
export type CacheKey<T = unknown> = { cache_key: T }
export type Callback<T = unknown> = { callback: T }
export type Calls<T = unknown> = { calls: T }
export type Campaign<T = unknown> = { campaign: T }
export type CampaignId<T = unknown> = { campaign_id: T }
export type CampaignIds<T = unknown> = { campaign_ids: T }
export type CampaignName<T = unknown> = { campaign_name: T }
export type CampaignNames<T = unknown> = { campaign_names: T }
export type Campaigns<T = unknown> = { campaigns: T }
export type Cancel<T = unknown> = { cancel: T }
export type Canceled<T = unknown> = { canceled: T }
export type Card<T = unknown> = { card: T }
export type CardId<T = unknown> = { card_id: T }
export type CardIds<T = unknown> = { card_ids: T }
export type Cards<T = unknown> = { cards: T }
export type Cascade<T = unknown> = { cascade: T }
export type Categories<T = unknown> = { categories: T }
export type Category<T = unknown> = { category: T }
export type CategoryId<T = unknown> = { category_id: T }
export type CategoryIds<T = unknown> = { category_ids: T }
export type CategoryName<T = unknown> = { category_name: T }
export type Cert<T = unknown> = { cert: T }
export type Certificate<T = unknown> = { certificate: T }
export type CertificateId<T = unknown> = { certificate_id: T }
export type CertificateIds<T = unknown> = { certificate_ids: T }
export type Certificates<T = unknown> = { certificates: T }
export type Channel<T = unknown> = { channel: T }
export type ChannelId<T = unknown> = { channel_id: T }
export type ChannelIds<T = unknown> = { channel_ids: T }
export type ChannelName<T = unknown> = { channel_name: T }
export type Channels<T = unknown> = { channels: T }
export type ChargedAt<T = unknown> = { charged_at: T }
export type Chunk<T = unknown> = { chunk: T }
export type ChunkId<T = unknown> = { chunk_id: T }
export type ChunkIds<T = unknown> = { chunk_ids: T }
export type ChunkSize<T = unknown> = { chunk_size: T }
export type Chunks<T = unknown> = { chunks: T }
export type City<T = unknown> = { city: T }
export type Class<T = unknown> = { class: T }
export type ClassId<T = unknown> = { class_id: T }
export type ClassIds<T = unknown> = { class_ids: T }
export type Classes<T = unknown> = { classes: T }
export type ClickId<T = unknown> = { click_id: T }
export type ClickIds<T = unknown> = { click_ids: T }
export type Clicks<T = unknown> = { clicks: T }
export type Client<T = unknown> = { client: T }
export type ClientId<T = unknown> = { client_id: T }
export type ClientIds<T = unknown> = { client_ids: T }
export type Clients<T = unknown> = { clients: T }
export type CloseConnectionTimeout<T = unknown> = { close_connection_timeout: T }
export type Cluster<T = unknown> = { cluster: T }
export type ClusterId<T = unknown> = { cluster_id: T }
export type ClusterIds<T = unknown> = { cluster_ids: T }
export type ClusterMode<T = unknown> = { cluster_mode: T }
export type Clusters<T = unknown> = { clusters: T }
export type Code<T = unknown> = { code: T }
export type Codes<T = unknown> = { codes: T }
export type Collection<T = unknown> = { collection: T }
export type CollectionId<T = unknown> = { collection_id: T }
export type CollectionIds<T = unknown> = { collection_ids: T }
export type CollectionName<T = unknown> = { collection_name: T }
export type Collections<T = unknown> = { collections: T }
export type Color<T = unknown> = { color: T }
export type Colors<T = unknown> = { colors: T }
export type Column<T = unknown> = { column: T }
export type ColumnId<T = unknown> = { column_id: T }
export type ColumnIds<T = unknown> = { column_ids: T }
export type ColumnName<T = unknown> = { column_name: T }
export type Columns<T = unknown> = { columns: T }
export type Comment<T = unknown> = { comment: T }
export type CommentId<T = unknown> = { comment_id: T }
export type CommentIds<T = unknown> = { comment_ids: T }
export type Comments<T = unknown> = { comments: T }
export type Common<T = unknown> = { common: T }
export type CompletedAt<T = unknown> = { completed_at: T }
export type Compressed<T = unknown> = { compressed: T }
export type Config<T = unknown> = { config: T }
export type ConfigId<T = unknown> = { config_id: T }
export type ConfigIds<T = unknown> = { config_ids: T }
export type ConfigName<T = unknown> = { config_name: T }
export type ConfigPath<T = unknown> = { config_path: T }
export type ConfigUrl<T = unknown> = { config_url: T }
export type Configs<T = unknown> = { configs: T }
export type Constant<T = unknown> = { constant: T }
export type Constraint<T = unknown> = { constraint: T }
export type Constraints<T = unknown> = { constraints: T }
export type Constructor<T = unknown> = { constructor: T }
export type Consumer<T = unknown> = { consumer: T }
export type ConsumerId<T = unknown> = { consumer_id: T }
export type ConsumerIds<T = unknown> = { consumer_ids: T }
export type Consumers<T = unknown> = { consumers: T }
export type Content<T = unknown> = { content: T }
export type ContentId<T = unknown> = { content_id: T }
export type ContentIds<T = unknown> = { content_ids: T }
export type Contents<T = unknown> = { contents: T }
export type Context<T = unknown> = { context: T }
export type Controller<T = unknown> = { controller: T }
export type Controllers<T = unknown> = { controllers: T }
export type Conversion<T = unknown> = { conversion: T }
export type Cors<T = unknown> = { cors: T }
export type Cost<T = unknown> = { cost: T }
export type Costs<T = unknown> = { costs: T }
export type Count<T = unknown> = { count: T }
export type Country<T = unknown> = { country: T }
export type CountryCode<T = unknown> = { country_code: T }
export type Create<T = unknown> = { create: T }
export type CreatedAt<T = unknown> = { created_at: T }
export type Creative<T = unknown> = { creative: T }
export type CreativeId<T = unknown> = { creative_id: T }
export type CreativeIds<T = unknown> = { creative_ids: T }
export type CreativeName<T = unknown> = { creative_name: T }
export type Creatives<T = unknown> = { creatives: T }
export type Credentials<T = unknown> = { credentials: T }
export type Csv<T = unknown> = { csv: T }
export type Currencies<T = unknown> = { currencies: T }
export type Currency<T = unknown> = { currency: T }
export type CurrencyCode<T = unknown> = { currency_code: T }
export type Cursor<T = unknown> = { cursor: T }
export type Customer<T = unknown> = { customer: T }
export type CustomerEmail<T = unknown> = { customer_email: T }
export type CustomerId<T = unknown> = { customer_id: T }
export type CustomerIds<T = unknown> = { customer_ids: T }
export type Customers<T = unknown> = { customers: T }
export type Data<T = unknown> = { data: T }
export type DataLevel<T = unknown> = { data_level: T }
export type Database<T = unknown> = { database: T }
export type DatabaseHost<T = unknown> = { database_host: T }
export type DatabaseName<T = unknown> = { database_name: T }
export type DatabasePort<T = unknown> = { database_port: T }
export type DatabaseUrl<T = unknown> = { database_url: T }
export type Databases<T = unknown> = { databases: T }
export type Date<T = unknown> = { date: T }
export type DateRange<T = unknown> = { date_range: T }
export type DateStart<T = unknown> = { date_start: T }
export type DateStop<T = unknown> = { date_stop: T }
export type DateUtc<T = unknown> = { date_utc: T }
export type Dates<T = unknown> = { dates: T }
export type Day<T = unknown> = { day: T }
export type Days<T = unknown> = { days: T }
export type DeadLetter<T = unknown> = { dead_letter: T }
export type DeadLetters<T = unknown> = { dead_letters: T }
export type DeadLettersUrl<T = unknown> = { dead_letters_url: T }
export type Debug<T = unknown> = { debug: T }
export type Decrement<T = unknown> = { decrement: T }
export type Default<T = unknown> = { default: T }
export type DefaultId<T = unknown> = { default_id: T }
export type DefaultIds<T = unknown> = { default_ids: T }
export type Defaults<T = unknown> = { defaults: T }
export type Delay<T = unknown> = { delay: T }
export type DelayMs<T = unknown> = { delay_ms: T }
export type DelaySec<T = unknown> = { delay_sec: T }
export type Delete<T = unknown> = { delete: T }
export type DeletedAt<T = unknown> = { deleted_at: T }
export type Dependencies<T = unknown> = { dependencies: T }
export type Depends<T = unknown> = { depends: T }
export type DependsOn<T = unknown> = { depends_on: T }
export type Depth<T = unknown> = { depth: T }
export type Description<T = unknown> = { description: T }
export type DescriptionId<T = unknown> = { description_id: T }
export type DescriptionIds<T = unknown> = { description_ids: T }
export type Descriptions<T = unknown> = { descriptions: T }
export type Desktop<T = unknown> = { desktop: T }
export type Detail<T = unknown> = { detail: T }
export type DetailId<T = unknown> = { detail_id: T }
export type DetailIds<T = unknown> = { detail_ids: T }
export type Details<T = unknown> = { details: T }
export type Dev<T = unknown> = { dev: T }
export type DevKey<T = unknown> = { dev_key: T }
export type Developer<T = unknown> = { developer: T }
export type DeveloperId<T = unknown> = { developer_id: T }
export type DeveloperIds<T = unknown> = { developer_ids: T }
export type Developers<T = unknown> = { developers: T }
export type Device<T = unknown> = { device: T }
export type DeviceId<T = unknown> = { device_id: T }
export type DeviceIds<T = unknown> = { device_ids: T }
export type Devices<T = unknown> = { devices: T }
export type Dict<T = unknown> = { dict: T }
export type Dictionaries<T = unknown> = { dictionaries: T }
export type Dictionary<T = unknown> = { dictionary: T }
export type Dimension<T = unknown> = { dimension: T }
export type Dimensions<T = unknown> = { dimensions: T }
export type Directories<T = unknown> = { directories: T }
export type Directory<T = unknown> = { directory: T }
export type DirectoryName<T = unknown> = { directory_name: T }
export type DirectoryPath<T = unknown> = { directory_path: T }
export type Disabled<T = unknown> = { disabled: T }
export type Discount<T = unknown> = { discount: T }
export type DiscountId<T = unknown> = { discount_id: T }
export type DiscountIds<T = unknown> = { discount_ids: T }
export type Discounts<T = unknown> = { discounts: T }
export type Display<T = unknown> = { display: T }
export type Docs<T = unknown> = { docs: T }
export type Document<T = unknown> = { document: T }
export type DocumentId<T = unknown> = { document_id: T }
export type DocumentIds<T = unknown> = { document_ids: T }
export type Documents<T = unknown> = { documents: T }
export type Domain<T = unknown> = { domain: T }
export type DomainId<T = unknown> = { domain_id: T }
export type DomainIds<T = unknown> = { domain_ids: T }
export type DomainName<T = unknown> = { domain_name: T }
export type DomainUrl<T = unknown> = { domain_url: T }
export type Domains<T = unknown> = { domains: T }
export type Dto<T = unknown> = { dto: T }
export type Dtos<T = unknown> = { dtos: T }
export type Duplicate<T = unknown> = { duplicate: T }
export type DuplicateId<T = unknown> = { duplicate_id: T }
export type DuplicateIds<T = unknown> = { duplicate_ids: T }
export type DuplicateName<T = unknown> = { duplicate_name: T }
export type Duplicates<T = unknown> = { duplicates: T }
export type Duration<T = unknown> = { duration: T }
export type Dynamic<T = unknown> = { dynamic: T }
export type Dynamics<T = unknown> = { dynamics: T }
export type Element<T = unknown> = { element: T }
export type ElementId<T = unknown> = { element_id: T }
export type ElementIds<T = unknown> = { element_ids: T }
export type Elements<T = unknown> = { elements: T }
export type Email<T = unknown> = { email: T }
export type Employee<T = unknown> = { employee: T }
export type EmployeeId<T = unknown> = { employee_id: T }
export type EmployeeIds<T = unknown> = { employee_ids: T }
export type Employees<T = unknown> = { employees: T }
export type Employer<T = unknown> = { employer: T }
export type EmployerId<T = unknown> = { employer_id: T }
export type EmployerIds<T = unknown> = { employer_ids: T }
export type Employers<T = unknown> = { employers: T }
export type Empty<T = unknown> = { empty: T }
export type Enabled<T = unknown> = { enabled: T }
export type Encoded<T = unknown> = { encoded: T }
export type Encoding<T = unknown> = { encoding: T }
export type EndDate<T = unknown> = { end_date: T }
export type EndTime<T = unknown> = { end_time: T }
export type Endpoint<T = unknown> = { endpoint: T }
export type Endpoints<T = unknown> = { endpoints: T }
export type Entities<T = unknown> = { entities: T }
export type Entity<T = unknown> = { entity: T }
export type EntityId<T = unknown> = { entity_id: T }
export type EntityIds<T = unknown> = { entity_ids: T }
export type Entries<T = unknown> = { entries: T }
export type Entry<T = unknown> = { entry: T }
export type EntryId<T = unknown> = { entry_id: T }
export type EntryIds<T = unknown> = { entry_ids: T }
export type Enum<T = unknown> = { enum: T }
export type Env<T = unknown> = { env: T }
export type EnvFilePath<T = unknown> = { env_file_path: T }
export type EnvKey<T = unknown> = { env_key: T }
export type EnvKeys<T = unknown> = { env_keys: T }
export type Envar<T = unknown> = { envar: T }
export type EnvarKey<T = unknown> = { envar_key: T }
export type Envars<T = unknown> = { envars: T }
export type Equals<T = unknown> = { equals: T }
export type Error<T = unknown> = { error: T }
export type Errors<T = unknown> = { errors: T }
export type Event<T = unknown> = { event: T }
export type EventId<T = unknown> = { event_id: T }
export type EventIds<T = unknown> = { event_ids: T }
export type EventName<T = unknown> = { event_name: T }
export type EventProperties<T = unknown> = { event_properties: T }
export type EventProperty<T = unknown> = { event_property: T }
export type EventTime<T = unknown> = { event_time: T }
export type EventType<T = unknown> = { event_type: T }
export type Events<T = unknown> = { events: T }
export type Exact<T = unknown> = { exact: T }
export type Example<T = unknown> = { example: T }
export type ExampleId<T = unknown> = { example_id: T }
export type ExampleIds<T = unknown> = { example_ids: T }
export type ExamplePath<T = unknown> = { example_path: T }
export type ExampleUrl<T = unknown> = { example_url: T }
export type Examples<T = unknown> = { examples: T }
export type Exclude<T = unknown> = { exclude: T }
export type ExcludePath<T = unknown> = { exclude_path: T }
export type ExcludePaths<T = unknown> = { exclude_paths: T }
export type Exists<T = unknown> = { exists: T }
export type ExpireAt<T = unknown> = { expire_at: T }
export type Expired<T = unknown> = { expired: T }
export type ExpiredToken<T = unknown> = { expired_token: T }
export type ExpiredTokens<T = unknown> = { expired_tokens: T }
export type Expires<T = unknown> = { expires: T }
export type Export<T = unknown> = { export: T }
export type Exports<T = unknown> = { exports: T }
export type ExposedHeaders<T = unknown> = { exposed_headers: T }
export type Extension<T = unknown> = { extension: T }
export type Extensions<T = unknown> = { extensions: T }
export type External<T = unknown> = { external: T }
export type ExternalId<T = unknown> = { external_id: T }
export type ExternalIds<T = unknown> = { external_ids: T }
export type Externals<T = unknown> = { externals: T }
export type Facebook<T = unknown> = { facebook: T }
export type Factory<T = unknown> = { factory: T }
export type Fail<T = unknown> = { fail: T }
export type Failed<T = unknown> = { failed: T }
export type Fails<T = unknown> = { fails: T }
export type Failure<T = unknown> = { failure: T }
export type Feature<T = unknown> = { feature: T }
export type FeatureId<T = unknown> = { feature_id: T }
export type FeatureIds<T = unknown> = { feature_ids: T }
export type FeatureName<T = unknown> = { feature_name: T }
export type Features<T = unknown> = { features: T }
export type Field<T = unknown> = { field: T }
export type FieldId<T = unknown> = { field_id: T }
export type FieldIds<T = unknown> = { field_ids: T }
export type FieldName<T = unknown> = { field_name: T }
export type Fields<T = unknown> = { fields: T }
export type Fifo<T = unknown> = { fifo: T }
export type File<T = unknown> = { file: T }
export type FileId<T = unknown> = { file_id: T }
export type FileIds<T = unknown> = { file_ids: T }
export type FileName<T = unknown> = { file_name: T }
export type FilePath<T = unknown> = { file_path: T }
export type FileSize<T = unknown> = { file_size: T }
export type Files<T = unknown> = { files: T }
export type Filter<T = unknown> = { filter: T }
export type FilterId<T = unknown> = { filter_id: T }
export type FilterIds<T = unknown> = { filter_ids: T }
export type Filters<T = unknown> = { filters: T }
export type FinishedAt<T = unknown> = { finished_at: T }
export type FirstName<T = unknown> = { first_name: T }
export type Folder<T = unknown> = { folder: T }
export type FolderId<T = unknown> = { folder_id: T }
export type FolderIds<T = unknown> = { folder_ids: T }
export type FolderPath<T = unknown> = { folder_path: T }
export type Folders<T = unknown> = { folders: T }
export type Font<T = unknown> = { font: T }
export type FontFamily<T = unknown> = { font_family: T }
export type FontId<T = unknown> = { font_id: T }
export type FontIds<T = unknown> = { font_ids: T }
export type FontName<T = unknown> = { font_name: T }
export type FontPath<T = unknown> = { font_path: T }
export type FontUrl<T = unknown> = { font_url: T }
export type Fonts<T = unknown> = { fonts: T }
export type Force<T = unknown> = { force: T }
export type Form<T = unknown> = { form: T }
export type FormId<T = unknown> = { form_id: T }
export type FormIds<T = unknown> = { form_ids: T }
export type Format<T = unknown> = { format: T }
export type Formats<T = unknown> = { formats: T }
export type Forms<T = unknown> = { forms: T }
export type FromDate<T = unknown> = { from_date: T }
export type FullName<T = unknown> = { full_name: T }
export type GID<T = unknown> = { gid: T }
export type GUID<T = unknown> = { guid: T }
export type Game<T = unknown> = { game: T }
export type GameId<T = unknown> = { game_id: T }
export type GameIds<T = unknown> = { game_ids: T }
export type Games<T = unknown> = { games: T }
export type Gender<T = unknown> = { gender: T }
export type Git<T = unknown> = { git: T }
export type Gitignore<T = unknown> = { gitignore: T }
export type Google<T = unknown> = { google: T }
export type Group<T = unknown> = { group: T }
export type GroupId<T = unknown> = { group_id: T }
export type GroupIds<T = unknown> = { group_ids: T }
export type GroupName<T = unknown> = { group_name: T }
export type Groups<T = unknown> = { groups: T }
export type Hash<T = unknown> = { hash: T }
export type Header<T = unknown> = { header: T }
export type Headers<T = unknown> = { headers: T }
export type HeadersTimeout<T = unknown> = { headers_timeout: T }
export type Height<T = unknown> = { height: T }
export type Hidden<T = unknown> = { hidden: T }
export type Home<T = unknown> = { home: T }
export type Homepage<T = unknown> = { homepage: T }
export type Hook<T = unknown> = { hook: T }
export type HookId<T = unknown> = { hook_id: T }
export type Hooks<T = unknown> = { hooks: T }
export type Hour<T = unknown> = { hour: T }
export type Hours<T = unknown> = { hours: T }
export type Html<T = unknown> = { html: T }
export type HttpCode<T = unknown> = { http_code: T }
export type HttpCodes<T = unknown> = { http_codes: T }
export type HttpOptions<T = unknown> = { http_options: T }
export type HttpStatus<T = unknown> = { http_status: T }
export type ID<T = unknown> = { id: T }
export type IDFA<T = unknown> = { idfa: T }
export type IDFV<T = unknown> = { idfv: T }
export type IOS<T = unknown> = { ios: T }
export type Icon<T = unknown> = { icon: T }
export type IconId<T = unknown> = { icon_id: T }
export type IconIds<T = unknown> = { icon_ids: T }
export type IconPath<T = unknown> = { icon_path: T }
export type IconUrl<T = unknown> = { icon_url: T }
export type Icons<T = unknown> = { icons: T }
export type Image<T = unknown> = { image: T }
export type ImageId<T = unknown> = { image_id: T }
export type ImageIds<T = unknown> = { image_ids: T }
export type ImageName<T = unknown> = { image_name: T }
export type ImagePath<T = unknown> = { image_path: T }
export type ImageUrl<T = unknown> = { image_url: T }
export type Images<T = unknown> = { images: T }
export type Immutable<T = unknown> = { immutable: T }
export type Import<T = unknown> = { import: T }
export type Imports<T = unknown> = { imports: T }
export type Impression<T = unknown> = { impression: T }
export type Impressions<T = unknown> = { impressions: T }
export type Include<T = unknown> = { include: T }
export type IncludeId<T = unknown> = { include_id: T }
export type IncludeIds<T = unknown> = { include_ids: T }
export type IncludePath<T = unknown> = { include_path: T }
export type IncludePaths<T = unknown> = { include_paths: T }
export type Includes<T = unknown> = { includes: T }
export type Increment<T = unknown> = { increment: T }
export type Index<T = unknown> = { index: T }
export type Info<T = unknown> = { info: T }
export type Inject<T = unknown> = { inject: T }
export type Insert<T = unknown> = { insert: T }
export type Insights<T = unknown> = { insights: T }
export type Installs<T = unknown> = { installs: T }
export type Internal<T = unknown> = { internal: T }
export type InternalId<T = unknown> = { internal_id: T }
export type InternalIds<T = unknown> = { internal_ids: T }
export type Internals<T = unknown> = { internals: T }
export type Interval<T = unknown> = { interval: T }
export type Invoice<T = unknown> = { invoice: T }
export type InvoiceId<T = unknown> = { invoice_id: T }
export type InvoiceIds<T = unknown> = { invoice_ids: T }
export type InvoiceStatus<T = unknown> = { invoice_status: T }
export type Ip<T = unknown> = { ip: T }
export type IpAddress<T = unknown> = { ip_address: T }
export type IpV4<T = unknown> = { ip_v4: T }
export type IpV6<T = unknown> = { ip_v6: T }
export type Is<T = unknown> = { is: T }
export type IsDebug<T = unknown> = { is_debug: T }
export type IsDirty<T = unknown> = { is_dirty: T }
export type IsEnable<T = unknown> = { is_enable: T }
export type IsNullable<T = unknown> = { is_nullable: T }
export type IsProduction<T = unknown> = { is_production: T }
export type IsTrial<T = unknown> = { is_trial: T }
export type IsUsed<T = unknown> = { is_used: T }
export type IsValid<T = unknown> = { is_valid: T }
export type Iso<T = unknown> = { iso: T }
export type Iss<T = unknown> = { iss: T }
export type Issue<T = unknown> = { issue: T }
export type IssueId<T = unknown> = { issue_id: T }
export type IssueIds<T = unknown> = { issue_ids: T }
export type Issuer<T = unknown> = { issuer: T }
export type Issues<T = unknown> = { issues: T }
export type Item<T = unknown> = { item: T }
export type ItemId<T = unknown> = { item_id: T }
export type ItemIds<T = unknown> = { item_ids: T }
export type ItemName<T = unknown> = { item_name: T }
export type Items<T = unknown> = { items: T }
export type Job<T = unknown> = { job: T }
export type JobId<T = unknown> = { job_id: T }
export type JobIds<T = unknown> = { job_ids: T }
export type Jobs<T = unknown> = { jobs: T }
export type Json<T = unknown> = { json: T }
export type KID<T = unknown> = { kid: T }
export type KeepAliveTimeout<T = unknown> = { keep_alive_timeout: T }
export type Key<T = unknown> = { key: T }
export type KeyId<T = unknown> = { key_id: T }
export type KeyIds<T = unknown> = { key_ids: T }
export type KeyName<T = unknown> = { key_name: T }
export type Keys<T = unknown> = { keys: T }
export type Keyword<T = unknown> = { keyword: T }
export type Keywords<T = unknown> = { keywords: T }
export type Kind<T = unknown> = { kind: T }
export type Label<T = unknown> = { label: T }
export type Language<T = unknown> = { language: T }
export type Languages<T = unknown> = { languages: T }
export type LastName<T = unknown> = { last_name: T }
export type Layer<T = unknown> = { layer: T }
export type Layers<T = unknown> = { layers: T }
export type Left<T = unknown> = { left: T }
export type Length<T = unknown> = { length: T }
export type Letter<T = unknown> = { letter: T }
export type LetterId<T = unknown> = { letter_id: T }
export type LetterIds<T = unknown> = { letter_ids: T }
export type Letters<T = unknown> = { letters: T }
export type Level<T = unknown> = { level: T }
export type LevelId<T = unknown> = { level_id: T }
export type LevelIds<T = unknown> = { level_ids: T }
export type Levels<T = unknown> = { levels: T }
export type License<T = unknown> = { license: T }
export type Lifetime<T = unknown> = { lifetime: T }
export type Lifo<T = unknown> = { lifo: T }
export type Limit<T = unknown> = { limit: T }
export type Limited<T = unknown> = { limited: T }
export type Limits<T = unknown> = { limits: T }
export type Link<T = unknown> = { link: T }
export type Links<T = unknown> = { links: T }
export type List<T = unknown> = { list: T }
export type ListId<T = unknown> = { list_id: T }
export type ListIds<T = unknown> = { list_ids: T }
export type Listener<T = unknown> = { listener: T }
export type ListenerId<T = unknown> = { listener_id: T }
export type ListenerIds<T = unknown> = { listener_ids: T }
export type Listeners<T = unknown> = { listeners: T }
export type Lists<T = unknown> = { lists: T }
export type Load<T = unknown> = { load: T }
export type Local<T = unknown> = { local: T }
export type LocalEnv<T = unknown> = { local_env: T }
export type LocalOffset<T = unknown> = { local_offset: T }
export type Locale<T = unknown> = { locale: T }
export type LocaleId<T = unknown> = { locale_id: T }
export type LocaleIds<T = unknown> = { locale_ids: T }
export type Locales<T = unknown> = { locales: T }
export type Localhost<T = unknown> = { localhost: T }
export type Localization<T = unknown> = { localization: T }
export type LocalizationId<T = unknown> = { localization_id: T }
export type LocalizationIds<T = unknown> = { localization_ids: T }
export type LocalizationPath<T = unknown> = { localization_path: T }
export type LocalizationUrl<T = unknown> = { localization_url: T }
export type Localizations<T = unknown> = { localizations: T }
export type Location<T = unknown> = { location: T }
export type LocationId<T = unknown> = { location_id: T }
export type LocationIds<T = unknown> = { location_ids: T }
export type LocationName<T = unknown> = { location_name: T }
export type Locations<T = unknown> = { locations: T }
export type Log<T = unknown> = { log: T }
export type LogGroup<T = unknown> = { log_group: T }
export type LogGroups<T = unknown> = { log_groups: T }
export type LogLevel<T = unknown> = { log_level: T }
export type LogLevels<T = unknown> = { log_levels: T }
export type LogPath<T = unknown> = { log_path: T }
export type LogPaths<T = unknown> = { log_paths: T }
export type Logger<T = unknown> = { logger: T }
export type Logging<T = unknown> = { logging: T }
export type Login<T = unknown> = { login: T }
export type Logs<T = unknown> = { logs: T }
export type Main<T = unknown> = { main: T }
export type Margin<T = unknown> = { margin: T }
export type MarginBottom<T = unknown> = { margin_bottom: T }
export type MarginLeft<T = unknown> = { margin_left: T }
export type MarginRight<T = unknown> = { margin_right: T }
export type Marked<T = unknown> = { marked: T }
export type Mask<T = unknown> = { mask: T }
export type Masks<T = unknown> = { masks: T }
export type Master<T = unknown> = { master: T }
export type MasterId<T = unknown> = { master_id: T }
export type MasterIds<T = unknown> = { master_ids: T }
export type Masters<T = unknown> = { masters: T }
export type Material<T = unknown> = { material: T }
export type MaterialId<T = unknown> = { material_id: T }
export type MaterialIds<T = unknown> = { material_ids: T }
export type Materials<T = unknown> = { materials: T }
export type Matrix<T = unknown> = { matrix: T }
export type Max<T = unknown> = { max: T }
export type MaxLength<T = unknown> = { max_length: T }
export type MaxRecords<T = unknown> = { max_records: T }
export type Merchant<T = unknown> = { merchant: T }
export type MerchantId<T = unknown> = { merchant_id: T }
export type MerchantIds<T = unknown> = { merchant_ids: T }
export type Merchants<T = unknown> = { merchants: T }
export type Message<T = unknown> = { message: T }
export type MessageId<T = unknown> = { message_id: T }
export type MessageIds<T = unknown> = { message_ids: T }
export type Messages<T = unknown> = { messages: T }
export type Meta<T = unknown> = { meta: T }
export type Metadata<T = unknown> = { metadata: T }
export type Method<T = unknown> = { method: T }
export type Methods<T = unknown> = { methods: T }
export type Metric<T = unknown> = { metric: T }
export type MetricId<T = unknown> = { metric_id: T }
export type MetricIds<T = unknown> = { metric_ids: T }
export type Metrics<T = unknown> = { metrics: T }
export type Middleware<T = unknown> = { middleware: T }
export type Migration<T = unknown> = { migration: T }
export type Migrations<T = unknown> = { migrations: T }
export type Milliseconds<T = unknown> = { milliseconds: T }
export type MimeType<T = unknown> = { mime_type: T }
export type Min<T = unknown> = { min: T }
export type MinLength<T = unknown> = { min_length: T }
export type Minutes<T = unknown> = { minutes: T }
export type Missing<T = unknown> = { missing: T }
export type MissingId<T = unknown> = { missing_id: T }
export type MissingIds<T = unknown> = { missing_ids: T }
export type MissingName<T = unknown> = { missing_name: T }
export type Missings<T = unknown> = { missings: T }
export type Mode<T = unknown> = { mode: T }
export type Model<T = unknown> = { model: T }
export type ModelId<T = unknown> = { model_id: T }
export type ModelIds<T = unknown> = { model_ids: T }
export type ModelName<T = unknown> = { model_name: T }
export type Models<T = unknown> = { models: T }
export type Modes<T = unknown> = { modes: T }
export type Module<T = unknown> = { module: T }
export type Modules<T = unknown> = { modules: T }
export type Months<T = unknown> = { months: T }
export type Multiplier<T = unknown> = { multiplier: T }
export type Mutable<T = unknown> = { mutable: T }
export type Name<T = unknown> = { name: T }
export type Namespace<T = unknown> = { namespace: T }
export type NamespaceId<T = unknown> = { namespace_id: T }
export type NamespaceIds<T = unknown> = { namespace_ids: T }
export type Namespaces<T = unknown> = { namespaces: T }
export type Next<T = unknown> = { next: T }
export type NextDate<T = unknown> = { next_date: T }
export type NextPageUrl<T = unknown> = { next_page_url: T }
export type Node<T = unknown> = { node: T }
export type NodeId<T = unknown> = { node_id: T }
export type NodeIds<T = unknown> = { node_ids: T }
export type Nodes<T = unknown> = { nodes: T }
export type Not<T = unknown> = { not: T }
export type Note<T = unknown> = { note: T }
export type NoteId<T = unknown> = { note_id: T }
export type NoteIds<T = unknown> = { note_ids: T }
export type Notes<T = unknown> = { notes: T }
export type Notification<T = unknown> = { notification: T }
export type NotificationId<T = unknown> = { notification_id: T }
export type NotificationIds<T = unknown> = { notification_ids: T }
export type NotificationType<T = unknown> = { notification_type: T }
export type Notifications<T = unknown> = { notifications: T }
export type Nullable<T = unknown> = { nullable: T }
export type OS<T = unknown> = { os: T }
export type Object<T = unknown> = { object: T }
export type ObjectId<T = unknown> = { object_id: T }
export type ObjectIds<T = unknown> = { object_ids: T }
export type ObjectiveType<T = unknown> = { objective_type: T }
export type Objects<T = unknown> = { objects: T }
export type Offer<T = unknown> = { offer: T }
export type OfferId<T = unknown> = { offer_id: T }
export type OfferIds<T = unknown> = { offer_ids: T }
export type Offers<T = unknown> = { offers: T }
export type Offset<T = unknown> = { offset: T }
export type OffsetX<T = unknown> = { offset_x: T }
export type OffsetY<T = unknown> = { offset_y: T }
export type OffsetZ<T = unknown> = { offset_z: T }
export type Offsets<T = unknown> = { offsets: T }
export type OnCreate<T = unknown> = { on_create: T }
export type OnDelete<T = unknown> = { on_delete: T }
export type OnUpdate<T = unknown> = { on_update: T }
export type Operation<T = unknown> = { operation: T }
export type OperationId<T = unknown> = { operation_id: T }
export type OperationIds<T = unknown> = { operation_ids: T }
export type OperationType<T = unknown> = { operation_type: T }
export type Operations<T = unknown> = { operations: T }
export type Option<T = unknown> = { option: T }
export type Options<T = unknown> = { options: T }
export type Or<T = unknown> = { or: T }
export type Order<T = unknown> = { order: T }
export type OrderDescription<T = unknown> = { order_description: T }
export type OrderId<T = unknown> = { order_id: T }
export type OrderIds<T = unknown> = { order_ids: T }
export type OrderMetadata<T = unknown> = { order_metadata: T }
export type Ordered<T = unknown> = { ordered: T }
export type Orders<T = unknown> = { orders: T }
export type Origin<T = unknown> = { origin: T }
export type OriginId<T = unknown> = { origin_id: T }
export type OriginIds<T = unknown> = { origin_ids: T }
export type Origins<T = unknown> = { origins: T }
export type Owner<T = unknown> = { owner: T }
export type OwnerId<T = unknown> = { owner_id: T }
export type OwnerIds<T = unknown> = { owner_ids: T }
export type OwnerName<T = unknown> = { owner_name: T }
export type Owners<T = unknown> = { owners: T }
export type PID<T = unknown> = { pid: T }
export type PIN<T = unknown> = { pin: T }
export type PUK<T = unknown> = { puk: T }
export type Package<T = unknown> = { package: T }
export type PackageId<T = unknown> = { package_id: T }
export type PackageIds<T = unknown> = { package_ids: T }
export type PackageName<T = unknown> = { package_name: T }
export type Packages<T = unknown> = { packages: T }
export type Padding<T = unknown> = { padding: T }
export type PaddingBottom<T = unknown> = { padding_bottom: T }
export type PaddingLeft<T = unknown> = { padding_left: T }
export type PaddingRight<T = unknown> = { padding_right: T }
export type Page<T = unknown> = { page: T }
export type PageId<T = unknown> = { page_id: T }
export type PageIds<T = unknown> = { page_ids: T }
export type PageInfo<T = unknown> = { page_info: T }
export type PageSize<T = unknown> = { page_size: T }
export type PageUrl<T = unknown> = { page_url: T }
export type Pagination<T = unknown> = { pagination: T }
export type Paging<T = unknown> = { paging: T }
export type Param<T = unknown> = { param: T }
export type Params<T = unknown> = { params: T }
export type Part<T = unknown> = { part: T }
export type PartId<T = unknown> = { part_id: T }
export type PartIds<T = unknown> = { part_ids: T }
export type Parts<T = unknown> = { parts: T }
export type Password<T = unknown> = { password: T }
export type Path<T = unknown> = { path: T }
export type Paths<T = unknown> = { paths: T }
export type Pause<T = unknown> = { pause: T }
export type Paused<T = unknown> = { paused: T }
export type PausedAt<T = unknown> = { paused_at: T }
export type PausedFrom<T = unknown> = { paused_from: T }
export type PausedTo<T = unknown> = { paused_to: T }
export type Payer<T = unknown> = { payer: T }
export type PayerId<T = unknown> = { payer_id: T }
export type PayerIds<T = unknown> = { payer_ids: T }
export type Payers<T = unknown> = { payers: T }
export type Payload<T = unknown> = { payload: T }
export type Payment<T = unknown> = { payment: T }
export type PaymentDescription<T = unknown> = { payment_description: T }
export type PaymentId<T = unknown> = { payment_id: T }
export type PaymentIds<T = unknown> = { payment_ids: T }
export type PaymentMethod<T = unknown> = { payment_method: T }
export type PaymentNumber<T = unknown> = { payment_number: T }
export type PaymentType<T = unknown> = { payment_type: T }
export type Payments<T = unknown> = { payments: T }
export type PaymentsNumber<T = unknown> = { payments_number: T }
export type Permission<T = unknown> = { permission: T }
export type PermissionId<T = unknown> = { permission_id: T }
export type PermissionIds<T = unknown> = { permission_ids: T }
export type Permissions<T = unknown> = { permissions: T }
export type PhoneNumber<T = unknown> = { phone_number: T }
export type PixelCode<T = unknown> = { pixel_code: T }
export type Placement<T = unknown> = { placement: T }
export type PlacementId<T = unknown> = { placement_id: T }
export type PlacementIds<T = unknown> = { placement_ids: T }
export type Placements<T = unknown> = { placements: T }
export type Platform<T = unknown> = { platform: T }
export type PlatformId<T = unknown> = { platform_id: T }
export type PlatformIds<T = unknown> = { platform_ids: T }
export type PlatformName<T = unknown> = { platform_name: T }
export type Platforms<T = unknown> = { platforms: T }
export type Player<T = unknown> = { player: T }
export type PlayerId<T = unknown> = { player_id: T }
export type PlayerIds<T = unknown> = { player_ids: T }
export type Players<T = unknown> = { players: T }
export type Point<T = unknown> = { point: T }
export type PointId<T = unknown> = { point_id: T }
export type PointIds<T = unknown> = { point_ids: T }
export type Pointer<T = unknown> = { pointer: T }
export type Points<T = unknown> = { points: T }
export type Port<T = unknown> = { port: T }
export type Position<T = unknown> = { position: T }
export type PositionX<T = unknown> = { position_x: T }
export type PositionY<T = unknown> = { position_y: T }
export type PositionZ<T = unknown> = { position_z: T }
export type Positions<T = unknown> = { positions: T }
export type Post<T = unknown> = { post: T }
export type PostId<T = unknown> = { post_id: T }
export type PostIds<T = unknown> = { post_ids: T }
export type PostalCode<T = unknown> = { postal_code: T }
export type Posts<T = unknown> = { posts: T }
export type Preferences<T = unknown> = { preferences: T }
export type Prefix<T = unknown> = { prefix: T }
export type Price<T = unknown> = { price: T }
export type Prices<T = unknown> = { prices: T }
export type Primary<T = unknown> = { primary: T }
export type Priority<T = unknown> = { priority: T }
export type Private<T = unknown> = { private: T }
export type PrivateKey<T = unknown> = { private_key: T }
export type Process<T = unknown> = { process: T }
export type ProcessId<T = unknown> = { process_id: T }
export type ProcessIds<T = unknown> = { process_ids: T }
export type ProcessName<T = unknown> = { process_name: T }
export type Processes<T = unknown> = { processes: T }
export type Processor<T = unknown> = { processor: T }
export type Prod<T = unknown> = { prod: T }
export type Product<T = unknown> = { product: T }
export type ProductId<T = unknown> = { product_id: T }
export type ProductIds<T = unknown> = { product_ids: T }
export type ProductName<T = unknown> = { product_name: T }
export type Production<T = unknown> = { production: T }
export type Products<T = unknown> = { products: T }
export type Profile<T = unknown> = { profile: T }
export type ProfileId<T = unknown> = { profile_id: T }
export type ProfileIds<T = unknown> = { profile_ids: T }
export type Profiles<T = unknown> = { profiles: T }
export type Project<T = unknown> = { project: T }
export type ProjectId<T = unknown> = { project_id: T }
export type ProjectIds<T = unknown> = { project_ids: T }
export type Projects<T = unknown> = { projects: T }
export type Properties<T = unknown> = { properties: T }
export type Property<T = unknown> = { property: T }
export type PropertyId<T = unknown> = { property_id: T }
export type PropertyIds<T = unknown> = { property_ids: T }
export type Props<T = unknown> = { props: T }
export type Provider<T = unknown> = { provider: T }
export type Providers<T = unknown> = { providers: T }
export type Public<T = unknown> = { public: T }
export type PublicKey<T = unknown> = { public_key: T }
export type PublicPath<T = unknown> = { public_path: T }
export type Publication<T = unknown> = { publication: T }
export type PublicationId<T = unknown> = { publication_id: T }
export type PublicationIds<T = unknown> = { publication_ids: T }
export type Publications<T = unknown> = { publications: T }
export type Published<T = unknown> = { published: T }
export type PublishedAt<T = unknown> = { published_at: T }
export type Publisher<T = unknown> = { publisher: T }
export type PublisherId<T = unknown> = { publisher_id: T }
export type PublisherIds<T = unknown> = { publisher_ids: T }
export type PublisherName<T = unknown> = { publisher_name: T }
export type Publishers<T = unknown> = { publishers: T }
export type Purchase<T = unknown> = { purchase: T }
export type PurchaseDate<T = unknown> = { purchase_date: T }
export type PurchaseId<T = unknown> = { purchase_id: T }
export type PurchaseIds<T = unknown> = { purchase_ids: T }
export type PurchaseName<T = unknown> = { purchase_name: T }
export type PurchaseToken<T = unknown> = { purchase_token: T }
export type PurchaseType<T = unknown> = { purchase_type: T }
export type Purchases<T = unknown> = { purchases: T }
export type Quantity<T = unknown> = { quantity: T }
export type Queries<T = unknown> = { queries: T }
export type Query<T = unknown> = { query: T }
export type Question<T = unknown> = { question: T }
export type QuestionId<T = unknown> = { question_id: T }
export type QuestionIds<T = unknown> = { question_ids: T }
export type Questions<T = unknown> = { questions: T }
export type Queue<T = unknown> = { queue: T }
export type QueueId<T = unknown> = { queue_id: T }
export type QueueIds<T = unknown> = { queue_ids: T }
export type QueueName<T = unknown> = { queue_name: T }
export type QueueUrl<T = unknown> = { queue_url: T }
export type Queues<T = unknown> = { queues: T }
export type Radius<T = unknown> = { radius: T }
export type Range<T = unknown> = { range: T }
export type Ranges<T = unknown> = { ranges: T }
export type Rating<T = unknown> = { rating: T }
export type Ratio<T = unknown> = { ratio: T }
export type Raw<T = unknown> = { raw: T }
export type RawBody<T = unknown> = { raw_body: T }
export type Reason<T = unknown> = { reason: T }
export type ReasonId<T = unknown> = { reason_id: T }
export type ReasonIds<T = unknown> = { reason_ids: T }
export type Reasons<T = unknown> = { reasons: T }
export type Receipt<T = unknown> = { receipt: T }
export type ReceiptId<T = unknown> = { receipt_id: T }
export type ReceiptIds<T = unknown> = { receipt_ids: T }
export type Receipts<T = unknown> = { receipts: T }
export type Record<T = unknown> = { record: T }
export type RecordId<T = unknown> = { record_id: T }
export type RecordIds<T = unknown> = { record_ids: T }
export type RecordName<T = unknown> = { record_name: T }
export type RecordType<T = unknown> = { record_type: T }
export type Records<T = unknown> = { records: T }
export type Redis<T = unknown> = { redis: T }
export type Ref<T = unknown> = { ref: T }
export type Reference<T = unknown> = { reference: T }
export type References<T = unknown> = { references: T }
export type Referrer<T = unknown> = { referrer: T }
export type RefreshToken<T = unknown> = { refresh_token: T }
export type RefundedAt<T = unknown> = { refunded_at: T }
export type Region<T = unknown> = { region: T }
export type RegionCode<T = unknown> = { region_code: T }
export type Regions<T = unknown> = { regions: T }
export type Relation<T = unknown> = { relation: T }
export type RelationId<T = unknown> = { relation_id: T }
export type RelationIds<T = unknown> = { relation_ids: T }
export type Relations<T = unknown> = { relations: T }
export type Remote<T = unknown> = { remote: T }
export type Remove<T = unknown> = { remove: T }
export type Replica<T = unknown> = { replica: T }
export type ReplicaId<T = unknown> = { replica_id: T }
export type ReplicaIds<T = unknown> = { replica_ids: T }
export type ReplicaName<T = unknown> = { replica_name: T }
export type ReplicaUrl<T = unknown> = { replica_url: T }
export type Replicas<T = unknown> = { replicas: T }
export type Replication<T = unknown> = { replication: T }
export type ReplicationId<T = unknown> = { replication_id: T }
export type ReplicationIds<T = unknown> = { replication_ids: T }
export type Replications<T = unknown> = { replications: T }
export type Report<T = unknown> = { report: T }
export type ReportId<T = unknown> = { report_id: T }
export type ReportIds<T = unknown> = { report_ids: T }
export type ReportType<T = unknown> = { report_type: T }
export type Reports<T = unknown> = { reports: T }
export type Repositories<T = unknown> = { repositories: T }
export type Repository<T = unknown> = { repository: T }
export type RepositoryUrl<T = unknown> = { repository_url: T }
export type Req<T = unknown> = { req: T }
export type Request<T = unknown> = { request: T }
export type RequestId<T = unknown> = { request_id: T }
export type RequestIds<T = unknown> = { request_ids: T }
export type Requests<T = unknown> = { requests: T }
export type Res<T = unknown> = { res: T }
export type Resource<T = unknown> = { resource: T }
export type ResourceId<T = unknown> = { resource_id: T }
export type ResourceIds<T = unknown> = { resource_ids: T }
export type ResourceName<T = unknown> = { resource_name: T }
export type ResourcePath<T = unknown> = { resource_path: T }
export type ResourceUrl<T = unknown> = { resource_url: T }
export type Resources<T = unknown> = { resources: T }
export type Response<T = unknown> = { response: T }
export type ResponseId<T = unknown> = { response_id: T }
export type ResponseIds<T = unknown> = { response_ids: T }
export type Responses<T = unknown> = { responses: T }
export type Result<T = unknown> = { result: T }
export type ResultId<T = unknown> = { result_id: T }
export type ResultIds<T = unknown> = { result_ids: T }
export type Results<T = unknown> = { results: T }
export type Retry<T = unknown> = { retry: T }
export type RetryCount<T = unknown> = { try_count: T }
export type Review<T = unknown> = { review: T }
export type ReviewId<T = unknown> = { review_id: T }
export type ReviewIds<T = unknown> = { review_ids: T }
export type Reviews<T = unknown> = { reviews: T }
export type Right<T = unknown> = { right: T }
export type Role<T = unknown> = { role: T }
export type RoleId<T = unknown> = { role_id: T }
export type RoleIds<T = unknown> = { role_ids: T }
export type RoleName<T = unknown> = { role_name: T }
export type Roles<T = unknown> = { roles: T }
export type Rotation<T = unknown> = { rotation: T }
export type RotationX<T = unknown> = { rotation_x: T }
export type RotationY<T = unknown> = { rotation_y: T }
export type RotationZ<T = unknown> = { rotation_z: T }
export type Rotations<T = unknown> = { rotations: T }
export type Route<T = unknown> = { route: T }
export type Routes<T = unknown> = { routes: T }
export type Row<T = unknown> = { row: T }
export type RowId<T = unknown> = { row_id: T }
export type RowIds<T = unknown> = { row_ids: T }
export type RowIndex<T = unknown> = { row_index: T }
export type Rows<T = unknown> = { rows: T }
export type SETID<T = unknown> = { setid: T }
export type SSL<T = unknown> = { ssl: T }
export type Salt<T = unknown> = { salt: T }
export type Scale<T = unknown> = { scale: T }
export type ScaleX<T = unknown> = { scale_x: T }
export type ScaleY<T = unknown> = { scale_y: T }
export type ScaleZ<T = unknown> = { scale_z: T }
export type Scales<T = unknown> = { scales: T }
export type Scenario<T = unknown> = { scenario: T }
export type ScenarioId<T = unknown> = { scenario_id: T }
export type ScenarioIds<T = unknown> = { scenario_ids: T }
export type Scenarios<T = unknown> = { scenarios: T }
export type Schedule<T = unknown> = { schedule: T }
export type Scheduled<T = unknown> = { scheduled: T }
export type Scheduler<T = unknown> = { scheduler: T }
export type Schema<T = unknown> = { schema: T }
export type SchemaId<T = unknown> = { schema_id: T }
export type SchemaIds<T = unknown> = { schema_ids: T }
export type SchemaName<T = unknown> = { schema_name: T }
export type Schemas<T = unknown> = { schemas: T }
export type Scope<T = unknown> = { scope: T }
export type Scopes<T = unknown> = { scopes: T }
export type Screen<T = unknown> = { screen: T }
export type Screenshot<T = unknown> = { screenshot: T }
export type ScreenshotId<T = unknown> = { screenshot_id: T }
export type ScreenshotIds<T = unknown> = { screenshot_ids: T }
export type ScreenshotName<T = unknown> = { screenshot_name: T }
export type ScreenshotPath<T = unknown> = { screenshot_path: T }
export type ScreenshotUrl<T = unknown> = { screenshot_url: T }
export type Screenshots<T = unknown> = { screenshots: T }
export type Sdk<T = unknown> = { sdk: T }
export type Secondary<T = unknown> = { secondary: T }
export type Seconds<T = unknown> = { seconds: T }
export type Secret<T = unknown> = { secret: T }
export type SecretKey<T = unknown> = { secret_key: T }
export type Select<T = unknown> = { select: T }
export type Selected<T = unknown> = { selected: T }
export type Selector<T = unknown> = { selector: T }
export type Self<T = unknown> = { self: T }
export type Sender<T = unknown> = { sender: T }
export type SenderId<T = unknown> = { sender_id: T }
export type SenderIds<T = unknown> = { sender_ids: T }
export type SenderName<T = unknown> = { sender_name: T }
export type Senders<T = unknown> = { senders: T }
export type Separator<T = unknown> = { separator: T }
export type Sequence<T = unknown> = { sequence: T }
export type SequenceId<T = unknown> = { sequence_id: T }
export type SequenceIds<T = unknown> = { sequence_ids: T }
export type Sequences<T = unknown> = { sequences: T }
export type Server<T = unknown> = { server: T }
export type ServerHost<T = unknown> = { server_host: T }
export type ServerPort<T = unknown> = { server_port: T }
export type ServerUrl<T = unknown> = { server_url: T }
export type Service<T = unknown> = { service: T }
export type ServiceId<T = unknown> = { service_id: T }
export type ServiceIds<T = unknown> = { service_ids: T }
export type ServiceName<T = unknown> = { service_name: T }
export type ServicePath<T = unknown> = { service_path: T }
export type ServiceType<T = unknown> = { service_type: T }
export type ServiceUrl<T = unknown> = { service_url: T }
export type Services<T = unknown> = { services: T }
export type Session<T = unknown> = { session: T }
export type SessionId<T = unknown> = { session_id: T }
export type SessionIds<T = unknown> = { session_ids: T }
export type Sessions<T = unknown> = { sessions: T }
export type Set<T = unknown> = { set: T }
export type SetId<T = unknown> = { set_id: T }
export type SetIds<T = unknown> = { set_ids: T }
export type Sets<T = unknown> = { sets: T }
export type Settings<T = unknown> = { settings: T }
export type Setup<T = unknown> = { setup: T }
export type SetupId<T = unknown> = { setup_id: T }
export type SetupIds<T = unknown> = { setup_ids: T }
export type Setups<T = unknown> = { setups: T }
export type Sheet<T = unknown> = { sheet: T }
export type SheetId<T = unknown> = { sheet_id: T }
export type SheetIds<T = unknown> = { sheet_ids: T }
export type SheetName<T = unknown> = { sheet_name: T }
export type Sheets<T = unknown> = { sheets: T }
export type ShutdownDelay<T = unknown> = { shutdown_delay: T }
export type Signature<T = unknown> = { signature: T }
export type Since<T = unknown> = { since: T }
export type Size<T = unknown> = { size: T }
export type Skip<T = unknown> = { skip: T }
export type Slack<T = unknown> = { slack: T }
export type Slave<T = unknown> = { slave: T }
export type SlaveId<T = unknown> = { slave_id: T }
export type SlaveIds<T = unknown> = { slave_ids: T }
export type Slaves<T = unknown> = { slaves: T }
export type Snapshot<T = unknown> = { snapshot: T }
export type SnapshotId<T = unknown> = { snapshot_id: T }
export type SnapshotIds<T = unknown> = { snapshot_ids: T }
export type SnapshotUrl<T = unknown> = { snapshot_url: T }
export type Snapshots<T = unknown> = { snapshots: T }
export type Sort<T = unknown> = { sort: T }
export type Source<T = unknown> = { source: T }
export type Spend<T = unknown> = { spend: T }
export type Spends<T = unknown> = { spends: T }
export type Stage<T = unknown> = { stage: T }
export type StartDate<T = unknown> = { start_date: T }
export type StartTime<T = unknown> = { start_time: T }
export type StartedAt<T = unknown> = { started_at: T }
export type State<T = unknown> = { state: T }
export type States<T = unknown> = { states: T }
export type Stats<T = unknown> = { stats: T }
export type Status<T = unknown> = { status: T }
export type Strategies<T = unknown> = { strategies: T }
export type Strategy<T = unknown> = { strategy: T }
export type StrategyId<T = unknown> = { strategy_id: T }
export type StrategyIds<T = unknown> = { strategy_ids: T }
export type StrategyName<T = unknown> = { strategy_name: T }
export type Stream<T = unknown> = { stream: T }
export type StreamId<T = unknown> = { stream_id: T }
export type StreamIds<T = unknown> = { stream_ids: T }
export type StreamName<T = unknown> = { stream_name: T }
export type Streams<T = unknown> = { streams: T }
export type Subject<T = unknown> = { subject: T }
export type SubjectId<T = unknown> = { subject_id: T }
export type SubjectIds<T = unknown> = { subject_ids: T }
export type Subjects<T = unknown> = { subjects: T }
export type Subscriber<T = unknown> = { subscriber: T }
export type SubscriberId<T = unknown> = { subscriber_id: T }
export type SubscriberIds<T = unknown> = { subscriber_ids: T }
export type Subscribers<T = unknown> = { subscribers: T }
export type Subscription<T = unknown> = { subscription: T }
export type SubscriptionId<T = unknown> = { subscription_id: T }
export type SubscriptionIds<T = unknown> = { subscription_ids: T }
export type Subscriptions<T = unknown> = { subscriptions: T }
export type Success<T = unknown> = { success: T }
export type Sum<T = unknown> = { sum: T }
export type Summary<T = unknown> = { summary: T }
export type Synchronize<T = unknown> = { synchronize: T }
export type Table<T = unknown> = { table: T }
export type TableId<T = unknown> = { table_id: T }
export type TableIds<T = unknown> = { table_ids: T }
export type TableName<T = unknown> = { table_name: T }
export type Tables<T = unknown> = { tables: T }
export type Tag<T = unknown> = { tag: T }
export type TagId<T = unknown> = { tag_id: T }
export type TagIds<T = unknown> = { tag_ids: T }
export type Tags<T = unknown> = { tags: T }
export type Take<T = unknown> = { take: T }
export type Target<T = unknown> = { target: T }
export type TargetId<T = unknown> = { target_id: T }
export type TargetIds<T = unknown> = { target_ids: T }
export type Targets<T = unknown> = { targets: T }
export type Task<T = unknown> = { task: T }
export type TaskId<T = unknown> = { task_id: T }
export type TaskIds<T = unknown> = { task_ids: T }
export type Tasks<T = unknown> = { tasks: T }
export type Taxes<T = unknown> = { taxes: T }
export type Template<T = unknown> = { template: T }
export type TemplateId<T = unknown> = { template_id: T }
export type TemplateIds<T = unknown> = { template_ids: T }
export type TemplateName<T = unknown> = { template_name: T }
export type TemplatePath<T = unknown> = { template_path: T }
export type TemplateUrl<T = unknown> = { template_url: T }
export type Templates<T = unknown> = { templates: T }
export type Territories<T = unknown> = { territories: T }
export type Territory<T = unknown> = { territory: T }
export type Text<T = unknown> = { text: T }
export type TextSize<T = unknown> = { text_size: T }
export type Throttle<T = unknown> = { throttle: T }
export type ThrottleMs<T = unknown> = { throttle_ms: T }
export type ThrottleSec<T = unknown> = { throttle_sec: T }
export type Ticket<T = unknown> = { ticket: T }
export type TicketId<T = unknown> = { ticket_id: T }
export type TicketIds<T = unknown> = { ticket_ids: T }
export type Tickets<T = unknown> = { tickets: T }
export type Tiktok<T = unknown> = { tiktok: T }
export type Time<T = unknown> = { time: T }
export type TimeRange<T = unknown> = { time_range: T }
export type TimeUtc<T = unknown> = { time_utc: T }
export type Timeout<T = unknown> = { timeout: T }
export type Timer<T = unknown> = { timer: T }
export type Timestamp<T = unknown> = { timestamp: T }
export type TimestampUtc<T = unknown> = { timestamp_utc: T }
export type Timezone<T = unknown> = { timezone: T }
export type TimezoneOffset<T = unknown> = { timezone_offset: T }
export type Title<T = unknown> = { title: T }
export type Tmp<T = unknown> = { tmp: T }
export type TmpPath<T = unknown> = { tmp_path: T }
export type ToDate<T = unknown> = { to_date: T }
export type Token<T = unknown> = { token: T }
export type TokenId<T = unknown> = { token_id: T }
export type TokenIds<T = unknown> = { token_ids: T }
export type TokenType<T = unknown> = { token_type: T }
export type Tokens<T = unknown> = { tokens: T }
export type Tool<T = unknown> = { tool: T }
export type ToolId<T = unknown> = { tool_id: T }
export type ToolIds<T = unknown> = { tool_ids: T }
export type Tools<T = unknown> = { tools: T }
export type Top<T = unknown> = { top: T }
export type Topic<T = unknown> = { topic: T }
export type TopicId<T = unknown> = { topic_id: T }
export type TopicIds<T = unknown> = { topic_ids: T }
export type TopicName<T = unknown> = { topic_name: T }
export type Topics<T = unknown> = { topics: T }
export type TotalClicks<T = unknown> = { total_clicks: T }
export type TotalCount<T = unknown> = { total_count: T }
export type TotalImpressions<T = unknown> = { total_impressions: T }
export type TotalInstalls<T = unknown> = { total_installs: T }
export type TotalNumber<T = unknown> = { total_number: T }
export type TotalSpend<T = unknown> = { total_spend: T }
export type Town<T = unknown> = { town: T }
export type Transaction<T = unknown> = { transaction: T }
export type TransactionId<T = unknown> = { transaction_id: T }
export type TransactionIds<T = unknown> = { transaction_ids: T }
export type TransactionToken<T = unknown> = { transaction_token: T }
export type Transactions<T = unknown> = { transactions: T }
export type Transformer<T = unknown> = { transformer: T }
export type Trial<T = unknown> = { trial: T }
export type Ttl<T = unknown> = { ttl: T }
export type TtlMs<T = unknown> = { ttl_ms: T }
export type TtlSec<T = unknown> = { ttl_sec: T }
export type Type<T = unknown> = { type: T }
export type TypeId<T = unknown> = { type_id: T }
export type TypeIds<T = unknown> = { type_ids: T }
export type Types<T = unknown> = { types: T }
export type UUID<T = unknown> = { uuid: T }
export type Unique<T = unknown> = { unique: T }
export type UniqueId<T = unknown> = { unique_id: T }
export type UniqueIds<T = unknown> = { unique_ids: T }
export type Uniques<T = unknown> = { uniques: T }
export type Unit<T = unknown> = { unit: T }
export type UnitId<T = unknown> = { unit_id: T }
export type UnitIds<T = unknown> = { unit_ids: T }
export type UnitName<T = unknown> = { unit_name: T }
export type Units<T = unknown> = { units: T }
export type Unlimited<T = unknown> = { unlimited: T }
export type Until<T = unknown> = { until: T }
export type Update<T = unknown> = { update: T }
export type UpdatedAt<T = unknown> = { updated_at: T }
export type Uri<T = unknown> = { uri: T }
export type Url<T = unknown> = { url: T }
export type Use<T = unknown> = { use: T }
export type UseCase<T = unknown> = { use_case: T }
export type UseDefault<T = unknown> = { use_default: T }
export type User<T = unknown> = { user: T }
export type UserAgent<T = unknown> = { user_agent: T }
export type UserData<T = unknown> = { user_data: T }
export type UserId<T = unknown> = { user_id: T }
export type UserIds<T = unknown> = { user_ids: T }
export type UserName<T = unknown> = { user_name: T }
export type UserPassword<T = unknown> = { user_password: T }
export type UserProperties<T = unknown> = { user_properties: T }
export type Username<T = unknown> = { username: T }
export type Users<T = unknown> = { users: T }
export type Utc<T = unknown> = { utc: T }
export type Valid<T = unknown> = { valid: T }
export type Validate<T = unknown> = { validate: T }
export type Validated<T = unknown> = { validated: T }
export type Validation<T = unknown> = { validation: T }
export type Value<T = unknown> = { value: T }
export type Values<T = unknown> = { values: T }
export type Variation<T = unknown> = { variation: T }
export type Variations<T = unknown> = { variations: T }
export type Vars<T = unknown> = { vars: T }
export type Vector<T = unknown> = { vector: T }
export type VendorId<T = unknown> = { vendor_id: T }
export type VendorIds<T = unknown> = { vendor_ids: T }
export type Verbose<T = unknown> = { verbose: T }
export type Version<T = unknown> = { version: T }
export type Video<T = unknown> = { video: T }
export type VideoId<T = unknown> = { video_id: T }
export type VideoIds<T = unknown> = { video_ids: T }
export type VideoName<T = unknown> = { video_name: T }
export type VideoUrl<T = unknown> = { video_url: T }
export type Videos<T = unknown> = { videos: T }
export type View<T = unknown> = { view: T }
export type ViewId<T = unknown> = { view_id: T }
export type ViewIds<T = unknown> = { view_ids: T }
export type Views<T = unknown> = { views: T }
export type Visitor<T = unknown> = { visitor: T }
export type VisitorId<T = unknown> = { visitor_id: T }
export type VisitorIds<T = unknown> = { visitor_ids: T }
export type Visitors<T = unknown> = { visitors: T }
export type Warning<T = unknown> = { warning: T }
export type Web<T = unknown> = { web: T }
export type Webhook<T = unknown> = { webhook: T }
export type WebhookUrl<T = unknown> = { webhook_url: T }
export type Webhooks<T = unknown> = { webhooks: T }
export type Week<T = unknown> = { week: T }
export type Weeks<T = unknown> = { weeks: T }
export type Weight<T = unknown> = { weight: T }
export type Where<T = unknown> = { where: T }
export type Whitelist<T = unknown> = { whitelist: T }
export type Width<T = unknown> = { width: T }
export type Workspace<T = unknown> = { workspace: T }
export type WorkspaceId<T = unknown> = { workspace_id: T }
export type WorkspaceIds<T = unknown> = { workspace_ids: T }
export type Workspaces<T = unknown> = { workspaces: T }
export type X<T = unknown> = { x: T }
export type Y<T = unknown> = { y: T }
export type Year<T = unknown> = { year: T }
export type Years<T = unknown> = { years: T }
export type Z<T = unknown> = { z: T }
export type ZIndex<T = unknown> = { z_index: T }
export type Zip<T = unknown> = { zip: T }
export type ZipCode<T = unknown> = { zip_code: T }
export type Ziped<T = unknown> = { ziped: T }