export declare type AAID<T = unknown> = { aaid: T }
export declare type About<T = unknown> = { about: T }
export declare type AccessKey<T = unknown> = { access_key: T }
export declare type AccessKeyId<T = unknown> = { access_key_id: T }
export declare type AccessKeyName<T = unknown> = { access_key_name: T }
export declare type AccessPoint<T = unknown> = { access_point: T }
export declare type AccessToken<T = unknown> = { access_token: T }
export declare type Account<T = unknown> = { account: T }
export declare type AccountId<T = unknown> = { account_id: T }
export declare type AccountIds<T = unknown> = { account_ids: T }
export declare type Accounts<T = unknown> = { accounts: T }
export declare type Action<T = unknown> = { action: T }
export declare type Ad<T = unknown> = { ad: T }
export declare type AdGroup<T = unknown> = { adgroup: T }
export declare type AdGroupId<T = unknown> = { adgroup_id: T }
export declare type AdGroupIds<T = unknown> = { adgroup_ids: T }
export declare type AdGroupName<T = unknown> = { adgroup_name: T }
export declare type AdId<T = unknown> = { ad_id: T }
export declare type AdIds<T = unknown> = { ad_ids: T }
export declare type AdName<T = unknown> = { ad_name: T }
export declare type Add<T = unknown> = { add: T }
export declare type Address<T = unknown> = { address: T }
export declare type Addresses<T = unknown> = { addresses: T }
export declare type Adgroups<T = unknown> = { adgroups: T }
export declare type Admin<T = unknown> = { admin: T }
export declare type AdminId<T = unknown> = { admin_id: T }
export declare type AdminIds<T = unknown> = { admin_ids: T }
export declare type Admins<T = unknown> = { admins: T }
export declare type Ads<T = unknown> = { ads: T }
export declare type Adset<T = unknown> = { adset: T }
export declare type AdsetId<T = unknown> = { adset_id: T }
export declare type AdsetIds<T = unknown> = { adset_ids: T }
export declare type AdsetName<T = unknown> = { adset_name: T }
export declare type Advertiser<T = unknown> = { advertiser: T }
export declare type AdvertiserId<T = unknown> = { advertiser_id: T }
export declare type AdvertiserIds<T = unknown> = { advertiser_ids: T }
export declare type Advertisers<T = unknown> = { advertisers: T }
export declare type Age<T = unknown> = { age: T }
export declare type AgeGroup<T = unknown> = { age_group: T }
export declare type Albom<T = unknown> = { albom: T }
export declare type AlbomId<T = unknown> = { albom_id: T }
export declare type AlbomIds<T = unknown> = { albom_ids: T }
export declare type AlbomName<T = unknown> = { albom_name: T }
export declare type Alboms<T = unknown> = { alboms: T }
export declare type Alg<T = unknown> = { alg: T }
export declare type Alias<T = unknown> = { alias: T }
export declare type Align<T = unknown> = { align: T }
export declare type Amount<T = unknown> = { amount: T }
export declare type Android<T = unknown> = { android: T }
export declare type Answer<T = unknown> = { answer: T }
export declare type AnswerId<T = unknown> = { answer_id: T }
export declare type AnswerIds<T = unknown> = { answer_ids: T }
export declare type Answers<T = unknown> = { answers: T }
export declare type Api<T = unknown> = { api: T }
export declare type ApiKey<T = unknown> = { api_key: T }
export declare type ApiUrl<T = unknown> = { api_url: T }
export declare type App<T = unknown> = { app: T }
export declare type AppId<T = unknown> = { app_id: T }
export declare type AppIds<T = unknown> = { app_ids: T }
export declare type Apple<T = unknown> = { apple: T }
export declare type Application<T = unknown> = { application: T }
export declare type ApplicationId<T = unknown> = { application_id: T }
export declare type ApplicationIds<T = unknown> = { application_ids: T }
export declare type Applications<T = unknown> = { applications: T }
export declare type Apps<T = unknown> = { apps: T }
export declare type AppslyerId<T = unknown> = { appsflyer_id: T }
export declare type Arg<T = unknown> = { arg: T }
export declare type Args<T = unknown> = { args: T }
export declare type Asset<T = unknown> = { asset: T }
export declare type AssetHash<T = unknown> = { asset_hash: T }
export declare type AssetId<T = unknown> = { asset_id: T }
export declare type AssetIds<T = unknown> = { asset_ids: T }
export declare type AssetName<T = unknown> = { asset_name: T }
export declare type Assets<T = unknown> = { assets: T }
export declare type Attribute<T = unknown> = { attribute: T }
export declare type AttributeId<T = unknown> = { attribute_id: T }
export declare type AttributeIds<T = unknown> = { attribute_ids: T }
export declare type Attributes<T = unknown> = { attributes: T }
export declare type Auth<T = unknown> = { auth: T }
export declare type AuthProvider<T = unknown> = { auth_provider: T }
export declare type Authorized<T = unknown> = { authorized: T }
export declare type Aws<T = unknown> = { aws: T }
export declare type BID<T = unknown> = { bid: T }
export declare type Background<T = unknown> = { background: T }
export declare type BackgroundColor<T = unknown> = { background_color: T }
export declare type BaseUrl<T = unknown> = { base_url: T }
export declare type Block<T = unknown> = { block: T }
export declare type BlockId<T = unknown> = { block_id: T }
export declare type BlockIds<T = unknown> = { block_ids: T }
export declare type Blocked<T = unknown> = { blocked: T }
export declare type Blocks<T = unknown> = { blocks: T }
export declare type Body<T = unknown> = { body: T }
export declare type Border<T = unknown> = { border: T }
export declare type Bottom<T = unknown> = { bottom: T }
export declare type Bucket<T = unknown> = { bucket: T }
export declare type BucketId<T = unknown> = { bucket_id: T }
export declare type BucketIds<T = unknown> = { bucket_ids: T }
export declare type BucketName<T = unknown> = { bucket_name: T }
export declare type BucketUrl<T = unknown> = { bucket_url: T }
export declare type Buckets<T = unknown> = { buckets: T }
export declare type Budget<T = unknown> = { budget: T }
export declare type Buffer<T = unknown> = { buffer: T }
export declare type Bundle<T = unknown> = { bundle: T }
export declare type BundleId<T = unknown> = { bundle_id: T }
export declare type BundleIds<T = unknown> = { bundle_ids: T }
export declare type Bundles<T = unknown> = { bundles: T }
export declare type Cache<T = unknown> = { cache: T }
export declare type CacheId<T = unknown> = { cache_id: T }
export declare type CacheIds<T = unknown> = { cache_ids: T }
export declare type Callback<T = unknown> = { callback: T }
export declare type Campaign<T = unknown> = { campaign: T }
export declare type CampaignId<T = unknown> = { campaign_id: T }
export declare type CampaignIds<T = unknown> = { campaign_ids: T }
export declare type CampaignName<T = unknown> = { campaign_name: T }
export declare type CampaignNames<T = unknown> = { campaign_names: T }
export declare type Campaigns<T = unknown> = { campaigns: T }
export declare type Cancel<T = unknown> = { cancel: T }
export declare type Canceled<T = unknown> = { canceled: T }
export declare type Card<T = unknown> = { card: T }
export declare type CardId<T = unknown> = { card_id: T }
export declare type CardIds<T = unknown> = { card_ids: T }
export declare type Cards<T = unknown> = { cards: T }
export declare type Categories<T = unknown> = { categories: T }
export declare type Category<T = unknown> = { category: T }
export declare type CategoryId<T = unknown> = { category_id: T }
export declare type CategoryIds<T = unknown> = { category_ids: T }
export declare type CategoryName<T = unknown> = { category_name: T }
export declare type Cert<T = unknown> = { cert: T }
export declare type Certificate<T = unknown> = { certificate: T }
export declare type CertificateId<T = unknown> = { certificat_id: T }
export declare type CertificateIds<T = unknown> = { certificat_ids: T }
export declare type Certificates<T = unknown> = { certificates: T }
export declare type Channel<T = unknown> = { channel: T }
export declare type ChannelId<T = unknown> = { channel_id: T }
export declare type ChannelIds<T = unknown> = { channel_ids: T }
export declare type ChannelName<T = unknown> = { channel_name: T }
export declare type Channels<T = unknown> = { channels: T }
export declare type ChargedAt<T = unknown> = { charged_at: T }
export declare type Chunk<T = unknown> = { chunk: T }
export declare type ChunkId<T = unknown> = { chunk_id: T }
export declare type ChunkIds<T = unknown> = { chunk_ids: T }
export declare type ChunkSize<T = unknown> = { chunk_size: T }
export declare type Chunks<T = unknown> = { chunks: T }
export declare type City<T = unknown> = { city: T }
export declare type ClickId<T = unknown> = { click_id: T }
export declare type ClickIds<T = unknown> = { click_ids: T }
export declare type Clicks<T = unknown> = { clicks: T }
export declare type Client<T = unknown> = { client: T }
export declare type ClientId<T = unknown> = { client_id: T }
export declare type ClientIds<T = unknown> = { client_ids: T }
export declare type Clients<T = unknown> = { clients: T }
export declare type Cluster<T = unknown> = { cluster: T }
export declare type ClusterId<T = unknown> = { cluster_id: T }
export declare type ClusterIds<T = unknown> = { cluster_ids: T }
export declare type ClusterMode<T = unknown> = { cluster_mode: T }
export declare type Clusters<T = unknown> = { clusters: T }
export declare type Code<T = unknown> = { code: T }
export declare type Codes<T = unknown> = { codes: T }
export declare type Collection<T = unknown> = { collection: T }
export declare type CollectionId<T = unknown> = { collection_id: T }
export declare type CollectionIds<T = unknown> = { collection_ids: T }
export declare type CollectionName<T = unknown> = { collection_name: T }
export declare type Collections<T = unknown> = { collections: T }
export declare type Color<T = unknown> = { color: T }
export declare type Colors<T = unknown> = { colors: T }
export declare type Comment<T = unknown> = { comment: T }
export declare type CommentId<T = unknown> = { comment_id: T }
export declare type CommentIds<T = unknown> = { comment_ids: T }
export declare type Comments<T = unknown> = { comments: T }
export declare type CompletedAt<T = unknown> = { completed_at: T }
export declare type Compressed<T = unknown> = { compressed: T }
export declare type Config<T = unknown> = { config: T }
export declare type ConfigId<T = unknown> = { config_id: T }
export declare type ConfigIds<T = unknown> = { config_ids: T }
export declare type ConfigName<T = unknown> = { config_name: T }
export declare type ConfigPath<T = unknown> = { config_path: T }
export declare type ConfigUrl<T = unknown> = { config_url: T }
export declare type Configs<T = unknown> = { configs: T }
export declare type Constant<T = unknown> = { constant: T }
export declare type Constraint<T = unknown> = { constraint: T }
export declare type Constraints<T = unknown> = { constraints: T }
export declare type Consumer<T = unknown> = { consumer: T }
export declare type ConsumerId<T = unknown> = { consumer_id: T }
export declare type ConsumerIds<T = unknown> = { consumer_ids: T }
export declare type Consumers<T = unknown> = { consumers: T }
export declare type Content<T = unknown> = { content: T }
export declare type Context<T = unknown> = { context: T }
export declare type Controller<T = unknown> = { controller: T }
export declare type Controllers<T = unknown> = { controllers: T }
export declare type Cors<T = unknown> = { cors: T }
export declare type Cost<T = unknown> = { cost: T }
export declare type Count<T = unknown> = { count: T }
export declare type Country<T = unknown> = { country: T }
export declare type CountryCode<T = unknown> = { country_code: T }
export declare type CreatedAt<T = unknown> = { created_at: T }
export declare type Credentials<T = unknown> = { credentials: T }
export declare type Csv<T = unknown> = { csv: T }
export declare type Currencies<T = unknown> = { currencies: T }
export declare type Currency<T = unknown> = { currency: T }
export declare type CurrencyCode<T = unknown> = { currency_code: T }
export declare type Customer<T = unknown> = { customer: T }
export declare type CustomerEmail<T = unknown> = { customer_email: T }
export declare type CustomerId<T = unknown> = { customer_id: T }
export declare type CustomerIds<T = unknown> = { customer_ids: T }
export declare type Customers<T = unknown> = { customers: T }
export declare type Data<T = unknown> = { data: T }
export declare type Database<T = unknown> = { database: T }
export declare type DatabaseHost<T = unknown> = { database_host: T }
export declare type DatabaseName<T = unknown> = { database_name: T }
export declare type DatabasePort<T = unknown> = { database_port: T }
export declare type DatabaseUrl<T = unknown> = { database_url: T }
export declare type Databases<T = unknown> = { databases: T }
export declare type Date<T = unknown> = { date: T }
export declare type Dates<T = unknown> = { dates: T }
export declare type Day<T = unknown> = { day: T }
export declare type Days<T = unknown> = { days: T }
export declare type DeadLetter<T = unknown> = { dead_letter: T }
export declare type DeadLetters<T = unknown> = { dead_letters: T }
export declare type Debug<T = unknown> = { debug: T }
export declare type Default<T = unknown> = { default: T }
export declare type DefaultId<T = unknown> = { default_id: T }
export declare type DefaultIds<T = unknown> = { default_ids: T }
export declare type Defaults<T = unknown> = { defaults: T }
export declare type Delay<T = unknown> = { delay: T }
export declare type DelayMs<T = unknown> = { delay_ms: T }
export declare type DelaySec<T = unknown> = { delay_sec: T }
export declare type DeletedAt<T = unknown> = { deleted_at: T }
export declare type Dependences<T = unknown> = { dependences: T }
export declare type Depends<T = unknown> = { depends: T }
export declare type DependsOn<T = unknown> = { depends_on: T }
export declare type Depth<T = unknown> = { depth: T }
export declare type Description<T = unknown> = { description: T }
export declare type DescriptionId<T = unknown> = { description_id: T }
export declare type DescriptionIds<T = unknown> = { description_ids: T }
export declare type Descriptions<T = unknown> = { descriptions: T }
export declare type Detail<T = unknown> = { detail: T }
export declare type DetailId<T = unknown> = { detail_id: T }
export declare type DetailIds<T = unknown> = { detail_ids: T }
export declare type Details<T = unknown> = { details: T }
export declare type Developer<T = unknown> = { developer: T }
export declare type DeveloperId<T = unknown> = { developer_id: T }
export declare type DeveloperIds<T = unknown> = { developer_ids: T }
export declare type Developers<T = unknown> = { developers: T }
export declare type Device<T = unknown> = { device: T }
export declare type DeviceId<T = unknown> = { device_id: T }
export declare type DeviceIds<T = unknown> = { device_ids: T }
export declare type Devices<T = unknown> = { devices: T }
export declare type Directories<T = unknown> = { directories: T }
export declare type Directory<T = unknown> = { directory: T }
export declare type DirectoryName<T = unknown> = { directory_name: T }
export declare type DirectoryPath<T = unknown> = { directory_path: T }
export declare type Disabled<T = unknown> = { disabled: T }
export declare type Discount<T = unknown> = { discount: T }
export declare type DiscountId<T = unknown> = { discount_id: T }
export declare type DiscountIds<T = unknown> = { discount_ids: T }
export declare type Discounts<T = unknown> = { discounts: T }
export declare type Display<T = unknown> = { display: T }
export declare type Docs<T = unknown> = { docs: T }
export declare type Document<T = unknown> = { document: T }
export declare type DocumentId<T = unknown> = { document_id: T }
export declare type DocumentIds<T = unknown> = { document_ids: T }
export declare type Documents<T = unknown> = { documents: T }
export declare type Domain<T = unknown> = { domain: T }
export declare type DomainId<T = unknown> = { domain_id: T }
export declare type DomainIds<T = unknown> = { domain_ids: T }
export declare type DomainName<T = unknown> = { domain_name: T }
export declare type DomainUrl<T = unknown> = { domain_url: T }
export declare type Domains<T = unknown> = { domains: T }
export declare type Dto<T = unknown> = { dto: T }
export declare type Dtos<T = unknown> = { dtos: T }
export declare type Duplicate<T = unknown> = { duplicate: T }
export declare type DuplicateId<T = unknown> = { duplicate_id: T }
export declare type DuplicateIds<T = unknown> = { duplicate_ids: T }
export declare type DuplicateName<T = unknown> = { duplicate_name: T }
export declare type Duplicates<T = unknown> = { duplicates: T }
export declare type Duration<T = unknown> = { duration: T }
export declare type Element<T = unknown> = { element: T }
export declare type ElementId<T = unknown> = { element_id: T }
export declare type ElementIds<T = unknown> = { element_ids: T }
export declare type Elements<T = unknown> = { elements: T }
export declare type Email<T = unknown> = { email: T }
export declare type Employee<T = unknown> = { employee: T }
export declare type EmployeeId<T = unknown> = { employee_id: T }
export declare type EmployeeIds<T = unknown> = { employee_ids: T }
export declare type Employees<T = unknown> = { employees: T }
export declare type Employer<T = unknown> = { employer: T }
export declare type EmployerId<T = unknown> = { employer_id: T }
export declare type EmployerIds<T = unknown> = { employer_ids: T }
export declare type Employers<T = unknown> = { employers: T }
export declare type Enabled<T = unknown> = { enabled: T }
export declare type Encoded<T = unknown> = { encoded: T }
export declare type Encoding<T = unknown> = { encoding: T }
export declare type EndDate<T = unknown> = { end_date: T }
export declare type EndTime<T = unknown> = { end_time: T }
export declare type Endpoint<T = unknown> = { endpoint: T }
export declare type Endpoints<T = unknown> = { endpoints: T }
export declare type Entities<T = unknown> = { entities: T }
export declare type Entity<T = unknown> = { entity: T }
export declare type EntityId<T = unknown> = { entity_id: T }
export declare type EntityIds<T = unknown> = { entity_ids: T }
export declare type Entries<T = unknown> = { entries: T }
export declare type Entry<T = unknown> = { entry: T }
export declare type EntryId<T = unknown> = { entry_id: T }
export declare type EntryIds<T = unknown> = { entry_ids: T }
export declare type Env<T = unknown> = { env: T }
export declare type EnvFilePath<T = unknown> = { env_file_path: T }
export declare type EnvKeys<T = unknown> = { env_keys: T }
export declare type Envar<T = unknown> = { envar: T }
export declare type Envars<T = unknown> = { envars: T }
export declare type Equals<T = unknown> = { equals: T }
export declare type Error<T = unknown> = { error: T }
export declare type Errors<T = unknown> = { errors: T }
export declare type Event<T = unknown> = { event: T }
export declare type EventId<T = unknown> = { event_id: T }
export declare type EventIds<T = unknown> = { event_ids: T }
export declare type EventName<T = unknown> = { event_name: T }
export declare type EventProperties<T = unknown> = { event_properties: T }
export declare type EventTime<T = unknown> = { event_time: T }
export declare type EventType<T = unknown> = { event_type: T }
export declare type Events<T = unknown> = { events: T }
export declare type Exact<T = unknown> = { exact: T }
export declare type Example<T = unknown> = { example: T }
export declare type ExampleId<T = unknown> = { example_id: T }
export declare type ExampleIds<T = unknown> = { example_ids: T }
export declare type ExamplePath<T = unknown> = { example_path: T }
export declare type ExampleUrl<T = unknown> = { example_url: T }
export declare type Examples<T = unknown> = { examples: T }
export declare type Exclude<T = unknown> = { exclude: T }
export declare type ExcludePath<T = unknown> = { exclude_path: T }
export declare type ExcludePaths<T = unknown> = { exclude_paths: T }
export declare type Exists<T = unknown> = { exists: T }
export declare type ExpireAt<T = unknown> = { expire_at: T }
export declare type Expires<T = unknown> = { expires: T }
export declare type Export<T = unknown> = { export: T }
export declare type Exports<T = unknown> = { exports: T }
export declare type ExposedHeaders<T = unknown> = { exposed_headers: T }
export declare type Extention<T = unknown> = { extention: T }
export declare type Extentions<T = unknown> = { extentions: T }
export declare type External<T = unknown> = { external: T }
export declare type ExternalId<T = unknown> = { external_id: T }
export declare type ExternalIds<T = unknown> = { external_ids: T }
export declare type Externals<T = unknown> = { externals: T }
export declare type Fail<T = unknown> = { fail: T }
export declare type Failed<T = unknown> = { failed: T }
export declare type Failure<T = unknown> = { failure: T }
export declare type Field<T = unknown> = { field: T }
export declare type FieldId<T = unknown> = { field_id: T }
export declare type FieldIds<T = unknown> = { field_ids: T }
export declare type FieldName<T = unknown> = { field_name: T }
export declare type Fields<T = unknown> = { fields: T }
export declare type File<T = unknown> = { file: T }
export declare type FileId<T = unknown> = { file_id: T }
export declare type FileIds<T = unknown> = { file_ids: T }
export declare type FileName<T = unknown> = { file_name: T }
export declare type FilePath<T = unknown> = { file_path: T }
export declare type FileSize<T = unknown> = { file_size: T }
export declare type Files<T = unknown> = { files: T }
export declare type Filter<T = unknown> = { filter: T }
export declare type FilterId<T = unknown> = { filter_id: T }
export declare type FilterIds<T = unknown> = { filter_ids: T }
export declare type Filters<T = unknown> = { filters: T }
export declare type FinishedAt<T = unknown> = { finished_at: T }
export declare type FirstName<T = unknown> = { first_name: T }
export declare type Folder<T = unknown> = { folder: T }
export declare type FolderId<T = unknown> = { folder_id: T }
export declare type FolderIds<T = unknown> = { folder_ids: T }
export declare type FolderPath<T = unknown> = { folder_path: T }
export declare type Folders<T = unknown> = { folders: T }
export declare type Font<T = unknown> = { font: T }
export declare type FontFamily<T = unknown> = { font_family: T }
export declare type FontId<T = unknown> = { font_id: T }
export declare type FontIds<T = unknown> = { font_ids: T }
export declare type FontName<T = unknown> = { font_name: T }
export declare type FontPath<T = unknown> = { font_path: T }
export declare type FontUrl<T = unknown> = { font_url: T }
export declare type Fonts<T = unknown> = { fonts: T }
export declare type Force<T = unknown> = { force: T }
export declare type Form<T = unknown> = { form: T }
export declare type FormId<T = unknown> = { form_id: T }
export declare type FormIds<T = unknown> = { form_ids: T }
export declare type Format<T = unknown> = { format: T }
export declare type Formats<T = unknown> = { formats: T }
export declare type Forms<T = unknown> = { forms: T }
export declare type FromDate<T = unknown> = { from_date: T }
export declare type GID<T = unknown> = { gid: T }
export declare type GUID<T = unknown> = { guid: T }
export declare type Game<T = unknown> = { game: T }
export declare type GameId<T = unknown> = { game_id: T }
export declare type GameIds<T = unknown> = { game_ids: T }
export declare type Games<T = unknown> = { games: T }
export declare type Gender<T = unknown> = { gender: T }
export declare type Git<T = unknown> = { git: T }
export declare type Gitignore<T = unknown> = { gitignore: T }
export declare type Group<T = unknown> = { group: T }
export declare type GroupId<T = unknown> = { group_id: T }
export declare type GroupIds<T = unknown> = { group_ids: T }
export declare type GroupName<T = unknown> = { group_name: T }
export declare type Groups<T = unknown> = { groups: T }
export declare type Hash<T = unknown> = { hash: T }
export declare type Header<T = unknown> = { header: T }
export declare type Headers<T = unknown> = { headers: T }
export declare type HeadersTimeout<T = unknown> = { headers_timeout: T }
export declare type Height<T = unknown> = { height: T }
export declare type Hidden<T = unknown> = { hidden: T }
export declare type Home<T = unknown> = { home: T }
export declare type Homepage<T = unknown> = { homepage: T }
export declare type Hour<T = unknown> = { hour: T }
export declare type Hours<T = unknown> = { hours: T }
export declare type Html<T = unknown> = { html: T }
export declare type HttpOptions<T = unknown> = { http_options: T }
export declare type ID<T = unknown> = { id: T }
export declare type IDFA<T = unknown> = { idfa: T }
export declare type IDFV<T = unknown> = { idfv: T }
export declare type IOS<T = unknown> = { ios: T }
export declare type Icon<T = unknown> = { icon: T }
export declare type IconId<T = unknown> = { icon_id: T }
export declare type IconIds<T = unknown> = { icon_ids: T }
export declare type IconPath<T = unknown> = { icon_path: T }
export declare type IconUrl<T = unknown> = { icon_url: T }
export declare type Icons<T = unknown> = { icons: T }
export declare type Image<T = unknown> = { image: T }
export declare type ImageId<T = unknown> = { image_id: T }
export declare type ImageIds<T = unknown> = { image_ids: T }
export declare type ImageName<T = unknown> = { image_name: T }
export declare type ImagePath<T = unknown> = { image_path: T }
export declare type ImageUrl<T = unknown> = { image_url: T }
export declare type Images<T = unknown> = { images: T }
export declare type Import<T = unknown> = { import: T }
export declare type Imports<T = unknown> = { imports: T }
export declare type Impressions<T = unknown> = { impressions: T }
export declare type IncludePath<T = unknown> = { include_path: T }
export declare type IncludePaths<T = unknown> = { include_paths: T }
export declare type Index<T = unknown> = { index: T }
export declare type Info<T = unknown> = { info: T }
export declare type Inject<T = unknown> = { inject: T }
export declare type Insights<T = unknown> = { insights: T }
export declare type Installs<T = unknown> = { installs: T }
export declare type Internal<T = unknown> = { internal: T }
export declare type InternalId<T = unknown> = { internal_id: T }
export declare type InternalIds<T = unknown> = { internal_ids: T }
export declare type Internals<T = unknown> = { internals: T }
export declare type Invoice<T = unknown> = { invoice: T }
export declare type InvoiceId<T = unknown> = { invoice_id: T }
export declare type InvoiceIds<T = unknown> = { invoice_ids: T }
export declare type InvoiceStatus<T = unknown> = { invoice_status: T }
export declare type IpAddress<T = unknown> = { ip_address: T }
export declare type IsDebug<T = unknown> = { is_debug: T }
export declare type IsDirty<T = unknown> = { is_dirty: T }
export declare type IsEnable<T = unknown> = { is_enable: T }
export declare type IsNulluble<T = unknown> = { is_nullable: T }
export declare type IsProduction<T = unknown> = { is_production: T }
export declare type IsTrial<T = unknown> = { is_trial: T }
export declare type Iso<T = unknown> = { iso: T }
export declare type Iss<T = unknown> = { iss: T }
export declare type Issue<T = unknown> = { issue: T }
export declare type IssueId<T = unknown> = { issue_id: T }
export declare type IssueIds<T = unknown> = { issue_ids: T }
export declare type Issuer<T = unknown> = { issuer: T }
export declare type Issues<T = unknown> = { issues: T }
export declare type Item<T = unknown> = { item: T }
export declare type ItemId<T = unknown> = { item_id: T }
export declare type ItemIds<T = unknown> = { item_ids: T }
export declare type ItemName<T = unknown> = { item_name: T }
export declare type Items<T = unknown> = { items: T }
export declare type Job<T = unknown> = { job: T }
export declare type JobId<T = unknown> = { job_id: T }
export declare type JobIds<T = unknown> = { job_ids: T }
export declare type Jobs<T = unknown> = { jobs: T }
export declare type Json<T = unknown> = { json: T }
export declare type KID<T = unknown> = { kid: T }
export declare type KeepAliveTimeout<T = unknown> = { keep_alive_timeout: T }
export declare type Key<T = unknown> = { key: T }
export declare type KeyId<T = unknown> = { key_id: T }
export declare type KeyIds<T = unknown> = { key_ids: T }
export declare type KeyName<T = unknown> = { key_name: T }
export declare type Keys<T = unknown> = { keys: T }
export declare type Keyword<T = unknown> = { keyword: T }
export declare type Keywords<T = unknown> = { keywords: T }
export declare type Kind<T = unknown> = { kind: T }
export declare type Lable<T = unknown> = { lable: T }
export declare type Language<T = unknown> = { language: T }
export declare type Languages<T = unknown> = { languages: T }
export declare type LastName<T = unknown> = { last_name: T }
export declare type Left<T = unknown> = { left: T }
export declare type Length<T = unknown> = { length: T }
export declare type Letter<T = unknown> = { letter: T }
export declare type LetterId<T = unknown> = { letter_id: T }
export declare type LetterIds<T = unknown> = { letter_ids: T }
export declare type Letters<T = unknown> = { letters: T }
export declare type Level<T = unknown> = { level: T }
export declare type LevelId<T = unknown> = { level_id: T }
export declare type LevelIds<T = unknown> = { level_ids: T }
export declare type Levels<T = unknown> = { levels: T }
export declare type License<T = unknown> = { license: T }
export declare type Link<T = unknown> = { link: T }
export declare type Links<T = unknown> = { links: T }
export declare type List<T = unknown> = { list: T }
export declare type ListId<T = unknown> = { list_id: T }
export declare type ListIds<T = unknown> = { list_ids: T }
export declare type Listener<T = unknown> = { listener: T }
export declare type ListenerId<T = unknown> = { listener_id: T }
export declare type ListenerIds<T = unknown> = { listener_ids: T }
export declare type Listeners<T = unknown> = { listeners: T }
export declare type Lists<T = unknown> = { lists: T }
export declare type Load<T = unknown> = { load: T }
export declare type Local<T = unknown> = { local: T }
export declare type LocalEnv<T = unknown> = { local_env: T }
export declare type Location<T = unknown> = { location: T }
export declare type LocationId<T = unknown> = { location_id: T }
export declare type LocationIds<T = unknown> = { location_ids: T }
export declare type LocationName<T = unknown> = { location_name: T }
export declare type Locations<T = unknown> = { locations: T }
export declare type Log<T = unknown> = { log: T }
export declare type LogGroup<T = unknown> = { log_group: T }
export declare type LogGroups<T = unknown> = { log_groups: T }
export declare type LogLevel<T = unknown> = { log_level: T }
export declare type LogLevels<T = unknown> = { log_levels: T }
export declare type Logger<T = unknown> = { logger: T }
export declare type Login<T = unknown> = { login: T }
export declare type Logs<T = unknown> = { logs: T }
export declare type Main<T = unknown> = { main: T }
export declare type Margin<T = unknown> = { margin: T }
export declare type MarginBottom<T = unknown> = { margin_bottom: T }
export declare type MarginLeft<T = unknown> = { margin_left: T }
export declare type MarginRight<T = unknown> = { margin_right: T }
export declare type Material<T = unknown> = { material: T }
export declare type MaterialId<T = unknown> = { material_id: T }
export declare type MaterialIds<T = unknown> = { material_ids: T }
export declare type Materials<T = unknown> = { materials: T }
export declare type Matrix<T = unknown> = { matrix: T }
export declare type Max<T = unknown> = { max: T }
export declare type MaxLength<T = unknown> = { max_length: T }
export declare type Merchant<T = unknown> = { merchant: T }
export declare type MerchantId<T = unknown> = { merchant_id: T }
export declare type MerchantIds<T = unknown> = { merchant_ids: T }
export declare type Merchants<T = unknown> = { merchants: T }
export declare type Message<T = unknown> = { message: T }
export declare type MessageId<T = unknown> = { message_id: T }
export declare type MessageIds<T = unknown> = { message_ids: T }
export declare type Messages<T = unknown> = { messages: T }
export declare type Meta<T = unknown> = { meta: T }
export declare type Metadata<T = unknown> = { metadata: T }
export declare type Method<T = unknown> = { method: T }
export declare type Methods<T = unknown> = { methods: T }
export declare type Metric<T = unknown> = { metric: T }
export declare type MetricId<T = unknown> = { metric_id: T }
export declare type MetricIds<T = unknown> = { metric_ids: T }
export declare type Metrics<T = unknown> = { metrics: T }
export declare type Migration<T = unknown> = { migration: T }
export declare type Migrations<T = unknown> = { migrations: T }
export declare type Milliseconds<T = unknown> = { milliseconds: T }
export declare type MimeType<T = unknown> = { mime_type: T }
export declare type Min<T = unknown> = { min: T }
export declare type MinLength<T = unknown> = { min_length: T }
export declare type Minutes<T = unknown> = { minutes: T }
export declare type Mode<T = unknown> = { mode: T }
export declare type Model<T = unknown> = { model: T }
export declare type ModelId<T = unknown> = { model_id: T }
export declare type ModelIds<T = unknown> = { model_ids: T }
export declare type ModelName<T = unknown> = { model_name: T }
export declare type Models<T = unknown> = { models: T }
export declare type Modes<T = unknown> = { modes: T }
export declare type Module<T = unknown> = { module: T }
export declare type Modules<T = unknown> = { modules: T }
export declare type Months<T = unknown> = { months: T }
export declare type Name<T = unknown> = { name: T }
export declare type Next<T = unknown> = { next: T }
export declare type NextPageUrl<T = unknown> = { next_page_url: T }
export declare type Node<T = unknown> = { node: T }
export declare type NodeId<T = unknown> = { node_id: T }
export declare type NodeIds<T = unknown> = { node_ids: T }
export declare type Nodes<T = unknown> = { nodes: T }
export declare type Note<T = unknown> = { note: T }
export declare type NoteId<T = unknown> = { note_id: T }
export declare type NoteIds<T = unknown> = { note_ids: T }
export declare type Notes<T = unknown> = { notes: T }
export declare type Notification<T = unknown> = { notification: T }
export declare type NotificationId<T = unknown> = { notification_id: T }
export declare type NotificationIds<T = unknown> = { notification_ids: T }
export declare type NotificationType<T = unknown> = { notification_type: T }
export declare type Notifications<T = unknown> = { notifications: T }
export declare type Nulluble<T = unknown> = { nullable: T }
export declare type OS<T = unknown> = { os: T }
export declare type Object<T = unknown> = { object: T }
export declare type ObjectId<T = unknown> = { object_id: T }
export declare type ObjectIds<T = unknown> = { object_ids: T }
export declare type Objects<T = unknown> = { objects: T }
export declare type Offer<T = unknown> = { offer: T }
export declare type OfferId<T = unknown> = { offer_id: T }
export declare type OfferIds<T = unknown> = { offer_ids: T }
export declare type Offers<T = unknown> = { offers: T }
export declare type Offset<T = unknown> = { offset: T }
export declare type OffsetX<T = unknown> = { offset_x: T }
export declare type OffsetY<T = unknown> = { offset_y: T }
export declare type OffsetZ<T = unknown> = { offset_z: T }
export declare type Offsets<T = unknown> = { offsets: T }
export declare type Options<T = unknown> = { options: T }
export declare type Order<T = unknown> = { order: T }
export declare type OrderId<T = unknown> = { order_id: T }
export declare type OrderIds<T = unknown> = { order_ids: T }
export declare type Orders<T = unknown> = { orders: T }
export declare type Origin<T = unknown> = { origin: T }
export declare type OriginId<T = unknown> = { origin_id: T }
export declare type OriginIds<T = unknown> = { origin_ids: T }
export declare type Origins<T = unknown> = { origins: T }
export declare type Owner<T = unknown> = { owner: T }
export declare type OwnerId<T = unknown> = { owner_id: T }
export declare type OwnerIds<T = unknown> = { owner_ids: T }
export declare type OwnerName<T = unknown> = { owner_name: T }
export declare type Owners<T = unknown> = { owners: T }
export declare type PID<T = unknown> = { pid: T }
export declare type PIN<T = unknown> = { pin: T }
export declare type PUK<T = unknown> = { puk: T }
export declare type Package<T = unknown> = { package: T }
export declare type PackageId<T = unknown> = { package_id: T }
export declare type PackageIds<T = unknown> = { package_ids: T }
export declare type PackageName<T = unknown> = { package_name: T }
export declare type Packages<T = unknown> = { packages: T }
export declare type Padding<T = unknown> = { padding: T }
export declare type PaddingBottom<T = unknown> = { padding_bottom: T }
export declare type PaddingLeft<T = unknown> = { padding_left: T }
export declare type PaddingRight<T = unknown> = { padding_right: T }
export declare type Page<T = unknown> = { page: T }
export declare type PageId<T = unknown> = { page_id: T }
export declare type PageIds<T = unknown> = { page_ids: T }
export declare type PageInfo<T = unknown> = { page_info: T }
export declare type PageSize<T = unknown> = { page_size: T }
export declare type PageUrl<T = unknown> = { page_url: T }
export declare type Param<T = unknown> = { param: T }
export declare type Params<T = unknown> = { params: T }
export declare type Part<T = unknown> = { part: T }
export declare type PartId<T = unknown> = { part_id: T }
export declare type PartIds<T = unknown> = { part_ids: T }
export declare type Parts<T = unknown> = { parts: T }
export declare type Password<T = unknown> = { password: T }
export declare type Path<T = unknown> = { path: T }
export declare type Paths<T = unknown> = { paths: T }
export declare type Pause<T = unknown> = { pause: T }
export declare type Paused<T = unknown> = { paused: T }
export declare type PausedAt<T = unknown> = { paused_at: T }
export declare type PausedFrom<T = unknown> = { paused_from: T }
export declare type PausedTo<T = unknown> = { paused_to: T }
export declare type Payer<T = unknown> = { payer: T }
export declare type PayerId<T = unknown> = { payer_id: T }
export declare type PayerIds<T = unknown> = { payer_ids: T }
export declare type Payers<T = unknown> = { payers: T }
export declare type Payload<T = unknown> = { payload: T }
export declare type Permission<T = unknown> = { permission: T }
export declare type PermissionId<T = unknown> = { permission_id: T }
export declare type PermissionIds<T = unknown> = { permission_ids: T }
export declare type Permissions<T = unknown> = { permissions: T }
export declare type Placement<T = unknown> = { placement: T }
export declare type PlacementId<T = unknown> = { placement_id: T }
export declare type PlacementIds<T = unknown> = { placement_ids: T }
export declare type Placements<T = unknown> = { placements: T }
export declare type Platform<T = unknown> = { platform: T }
export declare type PlatformId<T = unknown> = { platform_id: T }
export declare type PlatformIds<T = unknown> = { platform_ids: T }
export declare type PlatformName<T = unknown> = { platform_name: T }
export declare type Platforms<T = unknown> = { platforms: T }
export declare type Player<T = unknown> = { player: T }
export declare type PlayerId<T = unknown> = { player_id: T }
export declare type PlayerIds<T = unknown> = { player_ids: T }
export declare type Players<T = unknown> = { players: T }
export declare type Point<T = unknown> = { point: T }
export declare type PointId<T = unknown> = { point_id: T }
export declare type PointIds<T = unknown> = { point_ids: T }
export declare type Points<T = unknown> = { points: T }
export declare type Port<T = unknown> = { port: T }
export declare type Possition<T = unknown> = { possition: T }
export declare type PossitionX<T = unknown> = { possition_x: T }
export declare type PossitionY<T = unknown> = { possition_y: T }
export declare type PossitionZ<T = unknown> = { possition_z: T }
export declare type Possitions<T = unknown> = { possitions: T }
export declare type Post<T = unknown> = { post: T }
export declare type PostId<T = unknown> = { post_id: T }
export declare type PostIds<T = unknown> = { post_ids: T }
export declare type PostalCode<T = unknown> = { postal_code: T }
export declare type Posts<T = unknown> = { posts: T }
export declare type Preferences<T = unknown> = { preferences: T }
export declare type Prefix<T = unknown> = { prefix: T }
export declare type Price<T = unknown> = { price: T }
export declare type Primary<T = unknown> = { primary: T }
export declare type Private<T = unknown> = { private: T }
export declare type PrivateKey<T = unknown> = { private_key: T }
export declare type Product<T = unknown> = { product: T }
export declare type ProductId<T = unknown> = { product_id: T }
export declare type ProductIds<T = unknown> = { product_ids: T }
export declare type ProductName<T = unknown> = { product_name: T }
export declare type Production<T = unknown> = { production: T }
export declare type Products<T = unknown> = { products: T }
export declare type Profile<T = unknown> = { profile: T }
export declare type ProfileId<T = unknown> = { profile_id: T }
export declare type ProfileIds<T = unknown> = { profile_ids: T }
export declare type Profiles<T = unknown> = { profiles: T }
export declare type Project<T = unknown> = { project: T }
export declare type ProjectId<T = unknown> = { project_id: T }
export declare type ProjectIds<T = unknown> = { project_ids: T }
export declare type Projects<T = unknown> = { projects: T }
export declare type Properties<T = unknown> = { properties: T }
export declare type Property<T = unknown> = { property: T }
export declare type PropertyId<T = unknown> = { property_id: T }
export declare type PropertyIds<T = unknown> = { property_ids: T }
export declare type Props<T = unknown> = { props: T }
export declare type Provider<T = unknown> = { provider: T }
export declare type Providers<T = unknown> = { providers: T }
export declare type Public<T = unknown> = { public: T }
export declare type PublicKey<T = unknown> = { public_key: T }
export declare type PublicPath<T = unknown> = { public_path: T }
export declare type Publication<T = unknown> = { publication: T }
export declare type PublicationId<T = unknown> = { publication_id: T }
export declare type PublicationIds<T = unknown> = { publication_ids: T }
export declare type Publications<T = unknown> = { publications: T }
export declare type Published<T = unknown> = { published: T }
export declare type PublishedAt<T = unknown> = { published_at: T }
export declare type Publisher<T = unknown> = { publisher: T }
export declare type PublisherId<T = unknown> = { publisher_id: T }
export declare type PublisherIds<T = unknown> = { publisher_ids: T }
export declare type PublisherName<T = unknown> = { publisher_name: T }
export declare type Publishers<T = unknown> = { publishers: T }
export declare type Purchase<T = unknown> = { purchase: T }
export declare type PurchaseId<T = unknown> = { purchase_id: T }
export declare type PurchaseIds<T = unknown> = { purchase_ids: T }
export declare type PurchaseType<T = unknown> = { purchase_type: T }
export declare type Purchases<T = unknown> = { purchases: T }
export declare type Quantity<T = unknown> = { quantity: T }
export declare type Queries<T = unknown> = { queries: T }
export declare type Query<T = unknown> = { query: T }
export declare type Question<T = unknown> = { question: T }
export declare type QuestionId<T = unknown> = { question_id: T }
export declare type QuestionIds<T = unknown> = { question_ids: T }
export declare type Questions<T = unknown> = { questions: T }
export declare type Queue<T = unknown> = { queue: T }
export declare type QueueId<T = unknown> = { queue_id: T }
export declare type QueueIds<T = unknown> = { queue_ids: T }
export declare type QueueName<T = unknown> = { queue_name: T }
export declare type QueueUrl<T = unknown> = { queue_url: T }
export declare type Queues<T = unknown> = { queues: T }
export declare type Radius<T = unknown> = { radius: T }
export declare type Ratio<T = unknown> = { ratio: T }
export declare type Reason<T = unknown> = { reason: T }
export declare type ReasonId<T = unknown> = { reason_id: T }
export declare type ReasonIds<T = unknown> = { reason_ids: T }
export declare type Reasons<T = unknown> = { reasons: T }
export declare type Receipt<T = unknown> = { receipt: T }
export declare type ReceiptId<T = unknown> = { receipt_id: T }
export declare type ReceiptIds<T = unknown> = { receipt_ids: T }
export declare type Receipts<T = unknown> = { receipts: T }
export declare type Ref<T = unknown> = { ref: T }
export declare type Reference<T = unknown> = { reference: T }
export declare type References<T = unknown> = { references: T }
export declare type RefreshToken<T = unknown> = { refresh_token: T }
export declare type RefundedAt<T = unknown> = { refunded_at: T }
export declare type Region<T = unknown> = { region: T }
export declare type RegionCode<T = unknown> = { region_code: T }
export declare type Regions<T = unknown> = { regions: T }
export declare type Relation<T = unknown> = { relation: T }
export declare type RelationId<T = unknown> = { relation_id: T }
export declare type RelationIds<T = unknown> = { relation_ids: T }
export declare type Relations<T = unknown> = { relations: T }
export declare type Remote<T = unknown> = { remote: T }
export declare type Remove<T = unknown> = { remove: T }
export declare type Replica<T = unknown> = { replica: T }
export declare type ReplicaId<T = unknown> = { replica_id: T }
export declare type ReplicaIds<T = unknown> = { replica_ids: T }
export declare type ReplicaName<T = unknown> = { replica_name: T }
export declare type ReplicaUrl<T = unknown> = { replica_url: T }
export declare type Replicas<T = unknown> = { replicas: T }
export declare type Report<T = unknown> = { report: T }
export declare type ReportId<T = unknown> = { report_id: T }
export declare type ReportIds<T = unknown> = { report_ids: T }
export declare type Reports<T = unknown> = { reports: T }
export declare type Repositories<T = unknown> = { repositories: T }
export declare type Repository<T = unknown> = { repository: T }
export declare type RepositoryUrl<T = unknown> = { repository_url: T }
export declare type Req<T = unknown> = { req: T }
export declare type Request<T = unknown> = { request: T }
export declare type RequestId<T = unknown> = { request_id: T }
export declare type RequestIds<T = unknown> = { request_ids: T }
export declare type Requests<T = unknown> = { requests: T }
export declare type Res<T = unknown> = { res: T }
export declare type Resource<T = unknown> = { resource: T }
export declare type ResourceId<T = unknown> = { resource_id: T }
export declare type ResourceIds<T = unknown> = { resource_ids: T }
export declare type ResourceName<T = unknown> = { resource_name: T }
export declare type ResourcePath<T = unknown> = { resource_path: T }
export declare type ResourceUrl<T = unknown> = { resource_url: T }
export declare type Resources<T = unknown> = { resources: T }
export declare type Response<T = unknown> = { response: T }
export declare type ResponseId<T = unknown> = { response_id: T }
export declare type ResponseIds<T = unknown> = { response_ids: T }
export declare type Responses<T = unknown> = { responses: T }
export declare type Result<T = unknown> = { result: T }
export declare type ResultId<T = unknown> = { result_id: T }
export declare type ResultIds<T = unknown> = { result_ids: T }
export declare type Results<T = unknown> = { results: T }
export declare type Right<T = unknown> = { right: T }
export declare type Role<T = unknown> = { role: T }
export declare type RoleId<T = unknown> = { role_id: T }
export declare type RoleIds<T = unknown> = { role_ids: T }
export declare type RoleName<T = unknown> = { role_name: T }
export declare type Roles<T = unknown> = { roles: T }
export declare type Rotation<T = unknown> = { rotation: T }
export declare type RotationX<T = unknown> = { rotation_x: T }
export declare type RotationY<T = unknown> = { rotation_y: T }
export declare type RotationZ<T = unknown> = { rotation_z: T }
export declare type Rotations<T = unknown> = { rotations: T }
export declare type Route<T = unknown> = { route: T }
export declare type Routes<T = unknown> = { routes: T }
export declare type SETID<T = unknown> = { setid: T }
export declare type SSL<T = unknown> = { ssl: T }
export declare type Salt<T = unknown> = { salt: T }
export declare type Scale<T = unknown> = { scale: T }
export declare type ScaleX<T = unknown> = { scale_x: T }
export declare type ScaleY<T = unknown> = { scale_y: T }
export declare type ScaleZ<T = unknown> = { scale_z: T }
export declare type Scales<T = unknown> = { scales: T }
export declare type Schema<T = unknown> = { schema: T }
export declare type SchemaId<T = unknown> = { schema_id: T }
export declare type SchemaIds<T = unknown> = { schema_ids: T }
export declare type SchemaName<T = unknown> = { schema_name: T }
export declare type Schemas<T = unknown> = { schemas: T }
export declare type Scope<T = unknown> = { scope: T }
export declare type Scopes<T = unknown> = { scopes: T }
export declare type Screen<T = unknown> = { screen: T }
export declare type Sdk<T = unknown> = { sdk: T }
export declare type Secondary<T = unknown> = { secondary: T }
export declare type Seconds<T = unknown> = { seconds: T }
export declare type Secret<T = unknown> = { secret: T }
export declare type SecretKey<T = unknown> = { secret_key: T }
export declare type Sender<T = unknown> = { sender: T }
export declare type SenderId<T = unknown> = { sender_id: T }
export declare type SenderIds<T = unknown> = { sender_ids: T }
export declare type SenderName<T = unknown> = { sender_name: T }
export declare type Senders<T = unknown> = { senders: T }
export declare type Separator<T = unknown> = { separator: T }
export declare type Sequence<T = unknown> = { sequence: T }
export declare type SequenceId<T = unknown> = { sequence_id: T }
export declare type SequenceIds<T = unknown> = { sequence_ids: T }
export declare type Sequences<T = unknown> = { sequences: T }
export declare type Server<T = unknown> = { server: T }
export declare type ServerHost<T = unknown> = { server_host: T }
export declare type ServerPort<T = unknown> = { server_port: T }
export declare type ServerUrl<T = unknown> = { server_url: T }
export declare type Service<T = unknown> = { service: T }
export declare type ServiceId<T = unknown> = { service_id: T }
export declare type ServiceIds<T = unknown> = { service_ids: T }
export declare type ServiceName<T = unknown> = { service_name: T }
export declare type ServicePath<T = unknown> = { service_path: T }
export declare type ServiceUrl<T = unknown> = { service_url: T }
export declare type Services<T = unknown> = { services: T }
export declare type Session<T = unknown> = { session: T }
export declare type SessionId<T = unknown> = { session_id: T }
export declare type SessionIds<T = unknown> = { session_ids: T }
export declare type Sessions<T = unknown> = { sessions: T }
export declare type Set<T = unknown> = { set: T }
export declare type SetId<T = unknown> = { set_id: T }
export declare type SetIds<T = unknown> = { set_ids: T }
export declare type Sets<T = unknown> = { sets: T }
export declare type Settings<T = unknown> = { settings: T }
export declare type Signature<T = unknown> = { signature: T }
export declare type Size<T = unknown> = { size: T }
export declare type Snapshot<T = unknown> = { snapshot: T }
export declare type SnapshotId<T = unknown> = { snapshot_id: T }
export declare type SnapshotIds<T = unknown> = { snapshot_ids: T }
export declare type SnapshotUrl<T = unknown> = { snapshot_url: T }
export declare type Snapshots<T = unknown> = { snapshots: T }
export declare type Sort<T = unknown> = { sort: T }
export declare type Source<T = unknown> = { source: T }
export declare type Spend<T = unknown> = { spend: T }
export declare type Spends<T = unknown> = { spends: T }
export declare type StartDate<T = unknown> = { start_date: T }
export declare type StartTime<T = unknown> = { start_time: T }
export declare type StartedAt<T = unknown> = { started_at: T }
export declare type State<T = unknown> = { state: T }
export declare type States<T = unknown> = { states: T }
export declare type Stats<T = unknown> = { stats: T }
export declare type Status<T = unknown> = { status: T }
export declare type Strategies<T = unknown> = { strategies: T }
export declare type Strategy<T = unknown> = { strategy: T }
export declare type StrategyId<T = unknown> = { strategy_id: T }
export declare type StrategyIds<T = unknown> = { strategy_ids: T }
export declare type StrategyName<T = unknown> = { strategy_name: T }
export declare type Stream<T = unknown> = { stream: T }
export declare type StreamId<T = unknown> = { stream_id: T }
export declare type StreamIds<T = unknown> = { stream_ids: T }
export declare type StreamName<T = unknown> = { stream_name: T }
export declare type Streams<T = unknown> = { streams: T }
export declare type Subject<T = unknown> = { subject: T }
export declare type SubjectId<T = unknown> = { subject_id: T }
export declare type SubjectIds<T = unknown> = { subject_ids: T }
export declare type Subjects<T = unknown> = { subjects: T }
export declare type Subscriber<T = unknown> = { subscriber: T }
export declare type SubscriberId<T = unknown> = { subscriber_id: T }
export declare type SubscriberIds<T = unknown> = { subscriber_ids: T }
export declare type Subscribers<T = unknown> = { subscribers: T }
export declare type Subscription<T = unknown> = { subscription: T }
export declare type SubscriptionId<T = unknown> = { subscription_id: T }
export declare type SubscriptionIds<T = unknown> = { subscription_ids: T }
export declare type Subscriptions<T = unknown> = { subscriptions: T }
export declare type Success<T = unknown> = { success: T }
export declare type Sum<T = unknown> = { sum: T }
export declare type Summary<T = unknown> = { summary: T }
export declare type Table<T = unknown> = { table: T }
export declare type TableId<T = unknown> = { table_id: T }
export declare type TableIds<T = unknown> = { table_ids: T }
export declare type TableName<T = unknown> = { table_name: T }
export declare type Tables<T = unknown> = { tables: T }
export declare type Tag<T = unknown> = { tag: T }
export declare type TagId<T = unknown> = { tag_id: T }
export declare type TagIds<T = unknown> = { tag_ids: T }
export declare type Tags<T = unknown> = { tags: T }
export declare type Target<T = unknown> = { target: T }
export declare type TargetId<T = unknown> = { target_id: T }
export declare type TargetIds<T = unknown> = { target_ids: T }
export declare type Targets<T = unknown> = { targets: T }
export declare type Task<T = unknown> = { task: T }
export declare type TaskId<T = unknown> = { task_id: T }
export declare type TaskIds<T = unknown> = { task_ids: T }
export declare type Tasks<T = unknown> = { tasks: T }
export declare type Taxes<T = unknown> = { taxes: T }
export declare type Template<T = unknown> = { template: T }
export declare type TemplateId<T = unknown> = { template_id: T }
export declare type TemplateIds<T = unknown> = { template_ids: T }
export declare type TemplateName<T = unknown> = { template_name: T }
export declare type TemplatePath<T = unknown> = { template_path: T }
export declare type TemplateUrl<T = unknown> = { template_url: T }
export declare type Templates<T = unknown> = { templates: T }
export declare type Text<T = unknown> = { text: T }
export declare type TextSize<T = unknown> = { text_size: T }
export declare type Throttle<T = unknown> = { throttle: T }
export declare type ThrottleMs<T = unknown> = { throttle_ms: T }
export declare type ThrottleSec<T = unknown> = { throttle_sec: T }
export declare type Ticket<T = unknown> = { ticket: T }
export declare type TicketId<T = unknown> = { ticket_id: T }
export declare type TicketIds<T = unknown> = { ticket_ids: T }
export declare type Tickets<T = unknown> = { tickets: T }
export declare type Time<T = unknown> = { time: T }
export declare type TimeUtc<T = unknown> = { time_utc: T }
export declare type Timeout<T = unknown> = { timeout: T }
export declare type Timestamp = { timestamp: number }
export declare type Timezone<T = unknown> = { timezone: T }
export declare type TimezoneOffset<T = unknown> = { timezone_offset: T }
export declare type Title<T = unknown> = { title: T }
export declare type Tmp<T = unknown> = { tmp: T }
export declare type TmpPath<T = unknown> = { tmp_path: T }
export declare type ToDate<T = unknown> = { to_date: T }
export declare type Token<T = unknown> = { token: T }
export declare type TokenId<T = unknown> = { token_id: T }
export declare type TokenIds<T = unknown> = { token_ids: T }
export declare type TokenType<T = unknown> = { token_type: T }
export declare type Tokens<T = unknown> = { tokens: T }
export declare type Top<T = unknown> = { top: T }
export declare type Topic<T = unknown> = { topic: T }
export declare type TopicId<T = unknown> = { topic_id: T }
export declare type TopicIds<T = unknown> = { topic_ids: T }
export declare type TopicName<T = unknown> = { topic_name: T }
export declare type Topics<T = unknown> = { topics: T }
export declare type Town<T = unknown> = { town: T }
export declare type Transaction<T = unknown> = { transaction: T }
export declare type TransactionId<T = unknown> = { transaction_id: T }
export declare type TransactionIds<T = unknown> = { transaction_ids: T }
export declare type Transactions<T = unknown> = { transactions: T }
export declare type Trial<T = unknown> = { trial: T }
export declare type Ttl = { ttl: number }
export declare type TtlMs = { ttl_ms: number }
export declare type TtlSec = { ttl_sec: number }
export declare type Type<T = unknown> = { type: T }
export declare type TypeId<T = unknown> = { type_id: T }
export declare type TypeIds<T = unknown> = { type_ids: T }
export declare type Types<T = unknown> = { types: T }
export declare type UUID<T = unknown> = { uuid: T }
export declare type Unique<T = unknown> = { unique: T }
export declare type UniqueId<T = unknown> = { unique_id: T }
export declare type UniqueIds<T = unknown> = { unique_ids: T }
export declare type Uniques<T = unknown> = { uniques: T }
export declare type UpdatedAt<T = unknown> = { updated_at: T }
export declare type Uri<T = unknown> = { uri: T }
export declare type Url<T = unknown> = { url: T }
export declare type User<T = unknown> = { user: T }
export declare type UserAgent<T = unknown> = { user_agent: T }
export declare type UserData<T = unknown> = { user_data: T }
export declare type UserId<T = unknown> = { user_id: T }
export declare type UserIds<T = unknown> = { user_ids: T }
export declare type UserName<T = unknown> = { user_name: T }
export declare type UserPassword<T = unknown> = { user_password: T }
export declare type UserProperties<T = unknown> = { user_properties: T }
export declare type Username<T = unknown> = { username: T }
export declare type Users<T = unknown> = { users: T }
export declare type Utc<T = unknown> = { utc: T }
export declare type Value<T = unknown> = { value: T }
export declare type Values<T = unknown> = { values: T }
export declare type Vars<T = unknown> = { vars: T }
export declare type Vector<T = unknown> = { vector: T }
export declare type VendorId<T = unknown> = { vendor_id: T }
export declare type VendorIds<T = unknown> = { vendor_ids: T }
export declare type Verbose<T = unknown> = { verbose: T }
export declare type Version<T = unknown> = { version: T }
export declare type Video<T = unknown> = { video: T }
export declare type VideoId<T = unknown> = { video_id: T }
export declare type VideoIds<T = unknown> = { video_ids: T }
export declare type VideoName<T = unknown> = { video_name: T }
export declare type VideoUrl<T = unknown> = { video_url: T }
export declare type Videos<T = unknown> = { videos: T }
export declare type View<T = unknown> = { view: T }
export declare type ViewId<T = unknown> = { view_id: T }
export declare type ViewIds<T = unknown> = { view_ids: T }
export declare type Views<T = unknown> = { views: T }
export declare type Visitor<T = unknown> = { visitor: T }
export declare type VisitorId<T = unknown> = { visitor_id: T }
export declare type VisitorIds<T = unknown> = { visitor_ids: T }
export declare type Visitors<T = unknown> = { visitors: T }
export declare type Web<T = unknown> = { web: T }
export declare type Webhook<T = unknown> = { webhook: T }
export declare type WebhookUrl<T = unknown> = { webhook_url: T }
export declare type Webhooks<T = unknown> = { webhooks: T }
export declare type Week<T = unknown> = { week: T }
export declare type Weeks<T = unknown> = { weeks: T }
export declare type Weight<T = unknown> = { weight: T }
export declare type Width<T = unknown> = { width: T }
export declare type X<T = unknown> = { x: T }
export declare type Y<T = unknown> = { y: T }
export declare type Year<T = unknown> = { year: T }
export declare type Years<T = unknown> = { years: T }
export declare type Z<T = unknown> = { z: T }
export declare type ZIndex<T = unknown> = { z_index: T }
export declare type Zip<T = unknown> = { zip: T }
export declare type ZipCode<T = unknown> = { zip_code: T }
export declare type Ziped<T = unknown> = { ziped: T }