export type AAID<T = unknown> = { aaid: T }
export type About<T = unknown> = { about: T }
export type AccessKey<T = unknown> = { accessKey: T }
export type AccessKeyId<T = unknown> = { accessKeyId: T }
export type AccessKeyName<T = unknown> = { accessKeyName: T }
export type AccessPoint<T = unknown> = { accessPoint: T }
export type AccessToken<T = unknown> = { accessToken: T }
export type Account<T = unknown> = { account: T }
export type AccountId<T = unknown> = { accountId: T }
export type AccountIds<T = unknown> = { accountIds: T }
export type AccountName<T = unknown> = { accountName: T }
export type Accounts<T = unknown> = { accounts: T }
export type AcknowledgeId<T = unknown> = { acknowledgeId: T }
export type AcknowledgeIds<T = unknown> = { acknowledgeIds: T }
export type Acknowledgement<T = unknown> = { acknowledgement: T }
export type AcknowledgementState<T = unknown> = { acknowledgementState: T }
export type Acknowledgements<T = unknown> = { acknowledgements: T }
export type Action<T = unknown> = { action: T }
export type ActionSource<T = unknown> = { actionSource: T }
export type Activator<T = unknown> = { activator: T }
export type ActivatorId<T = unknown> = { activatorId: T }
export type ActivatorIds<T = unknown> = { activatorIds: T }
export type ActivatorName<T = unknown> = { activatorName: T }
export type Activators<T = unknown> = { activators: T }
export type Ad<T = unknown> = { ad: T }
export type AdGroup<T = unknown> = { adgroup: T }
export type AdGroupId<T = unknown> = { adgroupId: T }
export type AdGroupIds<T = unknown> = { adgroupIds: T }
export type AdGroupName<T = unknown> = { adgroupName: T }
export type AdId<T = unknown> = { adId: T }
export type AdIds<T = unknown> = { adIds: T }
export type AdName<T = unknown> = { adName: T }
export type Add<T = unknown> = { add: T }
export type Address<T = unknown> = { address: T }
export type Addresses<T = unknown> = { addresses: T }
export type Adgroups<T = unknown> = { adgroups: T }
export type Admin<T = unknown> = { admin: T }
export type AdminId<T = unknown> = { adminId: T }
export type AdminIds<T = unknown> = { adminIds: T }
export type AdminUrl<T = unknown> = { adminUrl: T }
export type Admins<T = unknown> = { admins: T }
export type Ads<T = unknown> = { ads: T }
export type Adset<T = unknown> = { adset: T }
export type AdsetId<T = unknown> = { adsetId: T }
export type AdsetIds<T = unknown> = { adsetIds: T }
export type AdsetName<T = unknown> = { adsetName: T }
export type Advanced<T = unknown> = { advanced: T }
export type Advertiser<T = unknown> = { advertiser: T }
export type AdvertiserId<T = unknown> = { advertiserId: T }
export type AdvertiserIds<T = unknown> = { advertiserIds: T }
export type Advertisers<T = unknown> = { advertisers: T }
export type Age<T = unknown> = { age: T }
export type AgeGroup<T = unknown> = { ageGroup: T }
export type AgeMax<T = unknown> = { ageMax: T }
export type AgeMin<T = unknown> = { ageMin: T }
export type Airtable<T = unknown> = { airtable: T }
export type Album<T = unknown> = { album: T }
export type AlbumId<T = unknown> = { albumId: T }
export type AlbumIds<T = unknown> = { albumIds: T }
export type AlbumName<T = unknown> = { albumName: T }
export type Albums<T = unknown> = { albums: T }
export type Alg<T = unknown> = { alg: T }
export type Alias<T = unknown> = { alias: T }
export type Align<T = unknown> = { align: T }
export type All<T = unknown> = { all: T }
export type Amount<T = unknown> = { amount: T }
export type Amplitude<T = unknown> = { amplitude: T }
export type Android<T = unknown> = { android: T }
export type Answer<T = unknown> = { answer: T }
export type AnswerId<T = unknown> = { answerId: T }
export type AnswerIds<T = unknown> = { answerIds: T }
export type Answers<T = unknown> = { answers: T }
export type Api<T = unknown> = { api: T }
export type ApiKey<T = unknown> = { apiKey: T }
export type ApiKeys<T = unknown> = { apiKeys: T }
export type ApiSecret<T = unknown> = { apiSecret: T }
export type ApiUrl<T = unknown> = { apiUrl: T }
export type App<T = unknown> = { app: T }
export type AppId<T = unknown> = { appId: T }
export type AppIds<T = unknown> = { appIds: T }
export type Apple<T = unknown> = { apple: T }
export type AppleUserId<T = unknown> = { appleUserId: T }
export type Application<T = unknown> = { application: T }
export type ApplicationId<T = unknown> = { applicationId: T }
export type ApplicationIds<T = unknown> = { applicationIds: T }
export type Applications<T = unknown> = { applications: T }
export type Applovin<T = unknown> = { applovin: T }
export type Apps<T = unknown> = { apps: T }
export type Appsflyer<T = unknown> = { appsflyer: T }
export type AppsflyerId<T = unknown> = { appsflyerId: T }
export type Arg<T = unknown> = { arg: T }
export type Args<T = unknown> = { args: T }
export type Asset<T = unknown> = { asset: T }
export type AssetHash<T = unknown> = { assetHash: T }
export type AssetId<T = unknown> = { assetId: T }
export type AssetIds<T = unknown> = { assetIds: T }
export type AssetName<T = unknown> = { assetName: T }
export type Assets<T = unknown> = { assets: T }
export type Attempt<T = unknown> = { attempt: T }
export type Attempts<T = unknown> = { attempts: T }
export type Attribute<T = unknown> = { attribute: T }
export type AttributeId<T = unknown> = { attributeId: T }
export type AttributeIds<T = unknown> = { attributeIds: T }
export type Attributes<T = unknown> = { attributes: T }
export type AudienceNetworkPositions<T = unknown> = { audienceNetworkPositions: T }
export type Auth<T = unknown> = { auth: T }
export type AuthProvider<T = unknown> = { authProvider: T }
export type Authorized<T = unknown> = { authorized: T }
export type Auto<T = unknown> = { auto: T }
export type AutoLoad<T = unknown> = { autoLoad: T }
export type AutoRenewing<T = unknown> = { autoRenewing: T }
export type AutoResumeTimeMs<T = unknown> = { autoResumeTimeMs: T }
export type AutoRun<T = unknown> = { autoRun: T }
export type Aws<T = unknown> = { aws: T }
export type BID<T = unknown> = { bid: T }
export type Background<T = unknown> = { background: T }
export type BackgroundColor<T = unknown> = { backgroundColor: T }
export type Badge<T = unknown> = { badge: T }
export type BadgeId<T = unknown> = { badgeId: T }
export type BadgeIds<T = unknown> = { badgeIds: T }
export type Badges<T = unknown> = { badges: T }
export type Base<T = unknown> = { base: T }
export type BaseId<T = unknown> = { baseId: T }
export type BaseUrl<T = unknown> = { baseUrl: T }
export type BidAmount<T = unknown> = { bidAmount: T }
export type BidStrategy<T = unknown> = { bidStrategy: T }
export type BillingEvent<T = unknown> = { billingEvent: T }
export type Blacklist<T = unknown> = { blacklist: T }
export type Block<T = unknown> = { block: T }
export type BlockId<T = unknown> = { blockId: T }
export type BlockIds<T = unknown> = { blockIds: T }
export type Blocked<T = unknown> = { blocked: T }
export type Blocks<T = unknown> = { blocks: T }
export type Blueprint<T = unknown> = { blueprint: T }
export type BlueprintId<T = unknown> = { blueprintId: T }
export type BlueprintIds<T = unknown> = { blueprintIds: T }
export type BlueprintName<T = unknown> = { blueprintName: T }
export type Blueprints<T = unknown> = { blueprints: T }
export type Body<T = unknown> = { body: T }
export type Border<T = unknown> = { border: T }
export type Bottom<T = unknown> = { bottom: T }
export type Bucket<T = unknown> = { bucket: T }
export type BucketId<T = unknown> = { bucketId: T }
export type BucketIds<T = unknown> = { bucketIds: T }
export type BucketName<T = unknown> = { bucketName: T }
export type BucketUrl<T = unknown> = { bucketUrl: T }
export type Buckets<T = unknown> = { buckets: T }
export type Budget<T = unknown> = { budget: T }
export type BudgetMode<T = unknown> = { budgetMode: T }
export type Buffer<T = unknown> = { buffer: T }
export type Builder<T = unknown> = { builder: T }
export type Bundle<T = unknown> = { bundle: T }
export type BundleId<T = unknown> = { bundleId: T }
export type BundleIds<T = unknown> = { bundleIds: T }
export type Bundles<T = unknown> = { bundles: T }
export type BusinessVideoId<T = unknown> = { businessVideoId: T }
export type BuyingType<T = unknown> = { buyingType: T }
export type CA<T = unknown> = { ca: T }
export type Cache<T = unknown> = { cache: T }
export type CacheId<T = unknown> = { cacheId: T }
export type CacheIds<T = unknown> = { cacheIds: T }
export type CacheKey<T = unknown> = { cacheKey: T }
export type CallToAction<T = unknown> = { callToAction: T }
export type Callback<T = unknown> = { callback: T }
export type CallbackType<T = unknown> = { callbackType: T }
export type Calls<T = unknown> = { calls: T }
export type Campaign<T = unknown> = { campaign: T }
export type CampaignId<T = unknown> = { campaignId: T }
export type CampaignIds<T = unknown> = { campaignIds: T }
export type CampaignName<T = unknown> = { campaignName: T }
export type CampaignNames<T = unknown> = { campaignNames: T }
export type Campaigns<T = unknown> = { campaigns: T }
export type Cancel<T = unknown> = { cancel: T }
export type CancelReason<T = unknown> = { cancelReason: T }
export type CancelSurveyReason<T = unknown> = { cancelSurveyReason: T }
export type CancelSurveyResult<T = unknown> = { cancelSurveyResult: T }
export type Canceled<T = unknown> = { canceled: T }
export type Card<T = unknown> = { card: T }
export type CardId<T = unknown> = { cardId: T }
export type CardIds<T = unknown> = { cardIds: T }
export type Cards<T = unknown> = { cards: T }
export type Cascade<T = unknown> = { cascade: T }
export type Categories<T = unknown> = { categories: T }
export type Category<T = unknown> = { category: T }
export type CategoryId<T = unknown> = { categoryId: T }
export type CategoryIds<T = unknown> = { categoryIds: T }
export type CategoryName<T = unknown> = { categoryName: T }
export type Cert<T = unknown> = { cert: T }
export type Certificate<T = unknown> = { certificate: T }
export type CertificateId<T = unknown> = { certificateId: T }
export type CertificateIds<T = unknown> = { certificateIds: T }
export type Certificates<T = unknown> = { certificates: T }
export type Channel<T = unknown> = { channel: T }
export type ChannelId<T = unknown> = { channelId: T }
export type ChannelIds<T = unknown> = { channelIds: T }
export type ChannelName<T = unknown> = { channelName: T }
export type Channels<T = unknown> = { channels: T }
export type ChargedAt<T = unknown> = { chargedAt: T }
export type Chunk<T = unknown> = { chunk: T }
export type ChunkId<T = unknown> = { chunkId: T }
export type ChunkIds<T = unknown> = { chunkIds: T }
export type ChunkSize<T = unknown> = { chunkSize: T }
export type Chunks<T = unknown> = { chunks: T }
export type City<T = unknown> = { city: T }
export type Class<T = unknown> = { class: T }
export type ClassId<T = unknown> = { classId: T }
export type ClassIds<T = unknown> = { classIds: T }
export type Classes<T = unknown> = { classes: T }
export type ClickId<T = unknown> = { clickId: T }
export type ClickIds<T = unknown> = { clickIds: T }
export type Clicks<T = unknown> = { clicks: T }
export type Client<T = unknown> = { client: T }
export type ClientId<T = unknown> = { clientId: T }
export type ClientIds<T = unknown> = { clientIds: T }
export type ClientIpAddress<T = unknown> = { clientIpAddress: T }
export type ClientUserAgent<T = unknown> = { clientUserAgent: T }
export type Clients<T = unknown> = { clients: T }
export type CloseConnectionTimeout<T = unknown> = { closeConnectionTimeout: T }
export type Cluster<T = unknown> = { cluster: T }
export type ClusterId<T = unknown> = { clusterId: T }
export type ClusterIds<T = unknown> = { clusterIds: T }
export type ClusterMode<T = unknown> = { clusterMode: T }
export type Clusters<T = unknown> = { clusters: T }
export type Code<T = unknown> = { code: T }
export type Codes<T = unknown> = { codes: T }
export type Collection<T = unknown> = { collection: T }
export type CollectionId<T = unknown> = { collectionId: T }
export type CollectionIds<T = unknown> = { collectionIds: T }
export type CollectionName<T = unknown> = { collectionName: T }
export type Collections<T = unknown> = { collections: T }
export type Color<T = unknown> = { color: T }
export type Colors<T = unknown> = { colors: T }
export type Column<T = unknown> = { column: T }
export type ColumnId<T = unknown> = { columnId: T }
export type ColumnIds<T = unknown> = { columnIds: T }
export type ColumnName<T = unknown> = { columnName: T }
export type Columns<T = unknown> = { columns: T }
export type Comment<T = unknown> = { comment: T }
export type CommentId<T = unknown> = { commentId: T }
export type CommentIds<T = unknown> = { commentIds: T }
export type Comments<T = unknown> = { comments: T }
export type Common<T = unknown> = { common: T }
export type CompletedAt<T = unknown> = { completedAt: T }
export type Compressed<T = unknown> = { compressed: T }
export type Config<T = unknown> = { config: T }
export type ConfigId<T = unknown> = { configId: T }
export type ConfigIds<T = unknown> = { configIds: T }
export type ConfigName<T = unknown> = { configName: T }
export type ConfigPath<T = unknown> = { configPath: T }
export type ConfigUrl<T = unknown> = { configUrl: T }
export type Configs<T = unknown> = { configs: T }
export type Constant<T = unknown> = { constant: T }
export type Constraint<T = unknown> = { constraint: T }
export type Constraints<T = unknown> = { constraints: T }
export type Constructor<T = unknown> = { constructor: T }
export type Consumer<T = unknown> = { consumer: T }
export type ConsumerId<T = unknown> = { consumerId: T }
export type ConsumerIds<T = unknown> = { consumerIds: T }
export type Consumers<T = unknown> = { consumers: T }
export type ConsumptionState<T = unknown> = { consumptionState: T }
export type Content<T = unknown> = { content: T }
export type ContentId<T = unknown> = { contentId: T }
export type ContentIds<T = unknown> = { contentIds: T }
export type Contents<T = unknown> = { contents: T }
export type Context<T = unknown> = { context: T }
export type Controller<T = unknown> = { controller: T }
export type Controllers<T = unknown> = { controllers: T }
export type Conversion<T = unknown> = { conversion: T }
export type ConversionDomain<T = unknown> = { conversionDomain: T }
export type Cookie<T = unknown> = { cookie: T }
export type CookieId<T = unknown> = { cookieId: T }
export type CookieIds<T = unknown> = { cookieIds: T }
export type CookieKey<T = unknown> = { cookieKey: T }
export type CookieKeys<T = unknown> = { cookieKeys: T }
export type CookieName<T = unknown> = { cookieName: T }
export type CookieNames<T = unknown> = { cookieNames: T }
export type Cookies<T = unknown> = { cookies: T }
export type Cors<T = unknown> = { cors: T }
export type Cost<T = unknown> = { cost: T }
export type Costs<T = unknown> = { costs: T }
export type Count<T = unknown> = { count: T }
export type Countries<T = unknown> = { countries: T }
export type Country<T = unknown> = { country: T }
export type CountryCode<T = unknown> = { countryCode: T }
export type Create<T = unknown> = { create: T }
export type CreatedAt<T = unknown> = { createdAt: T }
export type Creative<T = unknown> = { creative: T }
export type CreativeFeaturesSpec<T = unknown> = { creativeFeaturesSpec: T }
export type CreativeId<T = unknown> = { creativeId: T }
export type CreativeIds<T = unknown> = { creativeIds: T }
export type CreativeName<T = unknown> = { creativeName: T }
export type Creatives<T = unknown> = { creatives: T }
export type Credentials<T = unknown> = { credentials: T }
export type Csv<T = unknown> = { csv: T }
export type Currencies<T = unknown> = { currencies: T }
export type Currency<T = unknown> = { currency: T }
export type CurrencyCode<T = unknown> = { currencyCode: T }
export type Cursor<T = unknown> = { cursor: T }
export type CustomData<T = unknown> = { customData: T }
export type CustomEventType<T = unknown> = { customEventType: T }
export type Customer<T = unknown> = { customer: T }
export type CustomerAccountId<T = unknown> = { customerAccountId: T }
export type CustomerEmail<T = unknown> = { customerEmail: T }
export type CustomerId<T = unknown> = { customerId: T }
export type CustomerIds<T = unknown> = { customerIds: T }
export type Customers<T = unknown> = { customers: T }
export type DailyBudget<T = unknown> = { dailyBudget: T }
export type Data<T = unknown> = { data: T }
export type DataLevel<T = unknown> = { dataLevel: T }
export type Database<T = unknown> = { database: T }
export type DatabaseHost<T = unknown> = { databaseHost: T }
export type DatabaseName<T = unknown> = { databaseName: T }
export type DatabasePassword<T = unknown> = { databasePassword: T }
export type DatabasePort<T = unknown> = { databasePort: T }
export type DatabaseUrl<T = unknown> = { databaseUrl: T }
export type DatabaseUser<T = unknown> = { databaseUser: T }
export type Databases<T = unknown> = { databases: T }
export type Date<T = unknown> = { date: T }
export type DateRange<T = unknown> = { dateRange: T }
export type DateStart<T = unknown> = { dateStart: T }
export type DateStop<T = unknown> = { dateStop: T }
export type DateUtc<T = unknown> = { dateUtc: T }
export type Dates<T = unknown> = { dates: T }
export type Day<T = unknown> = { day: T }
export type Days<T = unknown> = { days: T }
export type Db<T = unknown> = { db: T }
export type DbHost<T = unknown> = { dbHost: T }
export type DbName<T = unknown> = { dbName: T }
export type DbPassword<T = unknown> = { dbPassword: T }
export type DbPort<T = unknown> = { dbPort: T }
export type DbUrl<T = unknown> = { dbUrl: T }
export type DbUser<T = unknown> = { dbUser: T }
export type Dbs<T = unknown> = { dbs: T }
export type DeadLetter<T = unknown> = { deadLetter: T }
export type DeadLetters<T = unknown> = { deadLetters: T }
export type DeadLettersUrl<T = unknown> = { deadLettersUrl: T }
export type Debug<T = unknown> = { debug: T }
export type Decrement<T = unknown> = { decrement: T }
export type Default<T = unknown> = { default: T }
export type DefaultId<T = unknown> = { defaultId: T }
export type DefaultIds<T = unknown> = { defaultIds: T }
export type Defaults<T = unknown> = { defaults: T }
export type DegreesOfFreedomSpec<T = unknown> = { degreesOfFreedomSpec: T }
export type Delay<T = unknown> = { delay: T }
export type DelayMs<T = unknown> = { delayMs: T }
export type DelaySec<T = unknown> = { delaySec: T }
export type Delete<T = unknown> = { delete: T }
export type DeletedAt<T = unknown> = { deletedAt: T }
export type Dependencies<T = unknown> = { dependencies: T }
export type Depends<T = unknown> = { depends: T }
export type DependsOn<T = unknown> = { dependsOn: T }
export type Depth<T = unknown> = { depth: T }
export type Description<T = unknown> = { description: T }
export type DescriptionId<T = unknown> = { descriptionId: T }
export type DescriptionIds<T = unknown> = { descriptionIds: T }
export type Descriptions<T = unknown> = { descriptions: T }
export type Desktop<T = unknown> = { desktop: T }
export type DestinationType<T = unknown> = { destinationType: T }
export type Detail<T = unknown> = { detail: T }
export type DetailId<T = unknown> = { detailId: T }
export type DetailIds<T = unknown> = { detailIds: T }
export type Details<T = unknown> = { details: T }
export type Dev<T = unknown> = { dev: T }
export type DevKey<T = unknown> = { devKey: T }
export type Developer<T = unknown> = { developer: T }
export type DeveloperId<T = unknown> = { developerId: T }
export type DeveloperIds<T = unknown> = { developerIds: T }
export type DeveloperPayload<T = unknown> = { developerPayload: T }
export type Developers<T = unknown> = { developers: T }
export type Device<T = unknown> = { device: T }
export type DeviceId<T = unknown> = { deviceId: T }
export type DeviceIds<T = unknown> = { deviceIds: T }
export type DevicePlatforms<T = unknown> = { devicePlatforms: T }
export type Devices<T = unknown> = { devices: T }
export type Dict<T = unknown> = { dict: T }
export type Dictionaries<T = unknown> = { dictionaries: T }
export type Dictionary<T = unknown> = { dictionary: T }
export type Dimension<T = unknown> = { dimension: T }
export type Dimensions<T = unknown> = { dimensions: T }
export type Directive<T = unknown> = { directive: T }
export type DirectiveId<T = unknown> = { directiveId: T }
export type DirectiveIds<T = unknown> = { directiveIds: T }
export type DirectiveName<T = unknown> = { directiveName: T }
export type Directives<T = unknown> = { directives: T }
export type Directories<T = unknown> = { directories: T }
export type Directory<T = unknown> = { directory: T }
export type DirectoryName<T = unknown> = { directoryName: T }
export type DirectoryPath<T = unknown> = { directoryPath: T }
export type Disabled<T = unknown> = { disabled: T }
export type Discount<T = unknown> = { discount: T }
export type DiscountId<T = unknown> = { discountId: T }
export type DiscountIds<T = unknown> = { discountIds: T }
export type Discounts<T = unknown> = { discounts: T }
export type Display<T = unknown> = { display: T }
export type Docs<T = unknown> = { docs: T }
export type Document<T = unknown> = { document: T }
export type DocumentId<T = unknown> = { documentId: T }
export type DocumentIds<T = unknown> = { documentIds: T }
export type Documents<T = unknown> = { documents: T }
export type Domain<T = unknown> = { domain: T }
export type DomainId<T = unknown> = { domainId: T }
export type DomainIds<T = unknown> = { domainIds: T }
export type DomainName<T = unknown> = { domainName: T }
export type DomainUrl<T = unknown> = { domainUrl: T }
export type Domains<T = unknown> = { domains: T }
export type DsaBeneficiary<T = unknown> = { dsaBeneficiary: T }
export type DsaPayor<T = unknown> = { dsaPayor: T }
export type Dto<T = unknown> = { dto: T }
export type Dtos<T = unknown> = { dtos: T }
export type Duplicate<T = unknown> = { duplicate: T }
export type DuplicateId<T = unknown> = { duplicateId: T }
export type DuplicateIds<T = unknown> = { duplicateIds: T }
export type DuplicateName<T = unknown> = { duplicateName: T }
export type Duplicates<T = unknown> = { duplicates: T }
export type Duration<T = unknown> = { duration: T }
export type DurationMs<T = unknown> = { durationMs: T }
export type DurationSec<T = unknown> = { durationSec: T }
export type Dynamic<T = unknown> = { dynamic: T }
export type Dynamics<T = unknown> = { dynamics: T }
export type Element<T = unknown> = { element: T }
export type ElementId<T = unknown> = { elementId: T }
export type ElementIds<T = unknown> = { elementIds: T }
export type ElementName<T = unknown> = { elementName: T }
export type Elements<T = unknown> = { elements: T }
export type Email<T = unknown> = { email: T }
export type EmailAddress<T = unknown> = { emailAddress: T }
export type Employee<T = unknown> = { employee: T }
export type EmployeeId<T = unknown> = { employeeId: T }
export type EmployeeIds<T = unknown> = { employeeIds: T }
export type Employees<T = unknown> = { employees: T }
export type Employer<T = unknown> = { employer: T }
export type EmployerId<T = unknown> = { employerId: T }
export type EmployerIds<T = unknown> = { employerIds: T }
export type Employers<T = unknown> = { employers: T }
export type Empty<T = unknown> = { empty: T }
export type Enabled<T = unknown> = { enabled: T }
export type Encoded<T = unknown> = { encoded: T }
export type Encoding<T = unknown> = { encoding: T }
export type EndDate<T = unknown> = { endDate: T }
export type EndOffset<T = unknown> = { endOffset: T }
export type EndTime<T = unknown> = { endTime: T }
export type Endpoint<T = unknown> = { endpoint: T }
export type Endpoints<T = unknown> = { endpoints: T }
export type EnrollStatus<T = unknown> = { enrollStatus: T }
export type Entities<T = unknown> = { entities: T }
export type Entity<T = unknown> = { entity: T }
export type EntityId<T = unknown> = { entityId: T }
export type EntityIds<T = unknown> = { entityIds: T }
export type Entries<T = unknown> = { entries: T }
export type Entry<T = unknown> = { entry: T }
export type EntryId<T = unknown> = { entryId: T }
export type EntryIds<T = unknown> = { entryIds: T }
export type Enum<T = unknown> = { enum: T }
export type Env<T = unknown> = { env: T }
export type EnvExamplePath<T = unknown> = { envExamplePath: T }
export type EnvFilePath<T = unknown> = { envFilePath: T }
export type EnvKey<T = unknown> = { envKey: T }
export type EnvKeys<T = unknown> = { envKeys: T }
export type EnvPath<T = unknown> = { envPath: T }
export type Envar<T = unknown> = { envar: T }
export type EnvarKey<T = unknown> = { envarKey: T }
export type EnvarKeys<T = unknown> = { envarKeys: T }
export type Envars<T = unknown> = { envars: T }
export type Equals<T = unknown> = { equals: T }
export type Error<T = unknown> = { error: T }
export type Errors<T = unknown> = { errors: T }
export type Event<T = unknown> = { event: T }
export type EventId<T = unknown> = { eventId: T }
export type EventIds<T = unknown> = { eventIds: T }
export type EventName<T = unknown> = { eventName: T }
export type EventProperties<T = unknown> = { eventProperties: T }
export type EventProperty<T = unknown> = { eventProperty: T }
export type EventTime<T = unknown> = { eventTime: T }
export type EventTimeMs<T = unknown> = { eventTimeMs: T }
export type EventTimeSec<T = unknown> = { eventTimeSec: T }
export type EventType<T = unknown> = { eventType: T }
export type Events<T = unknown> = { events: T }
export type Exact<T = unknown> = { exact: T }
export type Example<T = unknown> = { example: T }
export type ExampleId<T = unknown> = { exampleId: T }
export type ExampleIds<T = unknown> = { exampleIds: T }
export type ExamplePath<T = unknown> = { examplePath: T }
export type ExampleUrl<T = unknown> = { exampleUrl: T }
export type Examples<T = unknown> = { examples: T }
export type Exclude<T = unknown> = { exclude: T }
export type ExcludePath<T = unknown> = { excludePath: T }
export type ExcludePaths<T = unknown> = { excludePaths: T }
export type Exists<T = unknown> = { exists: T }
export type ExpireAt<T = unknown> = { expireAt: T }
export type ExpireTimeMs<T = unknown> = { expireTimeMs: T }
export type Expired<T = unknown> = { expired: T }
export type ExpiredToken<T = unknown> = { expiredToken: T }
export type ExpiredTokens<T = unknown> = { expiredTokens: T }
export type Expires<T = unknown> = { expires: T }
export type Export<T = unknown> = { export: T }
export type Exports<T = unknown> = { exports: T }
export type ExposedHeaders<T = unknown> = { exposedHeaders: T }
export type Extension<T = unknown> = { extension: T }
export type Extensions<T = unknown> = { extensions: T }
export type External<T = unknown> = { external: T }
export type ExternalAccountId<T = unknown> = { externalAccountId: T }
export type ExternalId<T = unknown> = { externalId: T }
export type ExternalIds<T = unknown> = { externalIds: T }
export type Externals<T = unknown> = { externals: T }
export type FBC<T = unknown> = { fbc: T }
export type FBP<T = unknown> = { fbp: T }
export type Facebook<T = unknown> = { facebook: T }
export type FacebookPositions<T = unknown> = { facebookPositions: T }
export type Factory<T = unknown> = { factory: T }
export type Fail<T = unknown> = { fail: T }
export type Failed<T = unknown> = { failed: T }
export type Fails<T = unknown> = { fails: T }
export type Failure<T = unknown> = { failure: T }
export type FamilyName<T = unknown> = { familyName: T }
export type Feature<T = unknown> = { feature: T }
export type FeatureId<T = unknown> = { featureId: T }
export type FeatureIds<T = unknown> = { featureIds: T }
export type FeatureName<T = unknown> = { featureName: T }
export type Features<T = unknown> = { features: T }
export type Field<T = unknown> = { field: T }
export type FieldId<T = unknown> = { fieldId: T }
export type FieldIds<T = unknown> = { fieldIds: T }
export type FieldName<T = unknown> = { fieldName: T }
export type Fields<T = unknown> = { fields: T }
export type Fifo<T = unknown> = { fifo: T }
export type File<T = unknown> = { file: T }
export type FileHash<T = unknown> = { fileHash: T }
export type FileId<T = unknown> = { fileId: T }
export type FileIds<T = unknown> = { fileIds: T }
export type FileName<T = unknown> = { fileName: T }
export type FilePath<T = unknown> = { filePath: T }
export type FileSize<T = unknown> = { fileSize: T }
export type Files<T = unknown> = { files: T }
export type Filter<T = unknown> = { filter: T }
export type FilterId<T = unknown> = { filterId: T }
export type FilterIds<T = unknown> = { filterIds: T }
export type Filters<T = unknown> = { filters: T }
export type FinishedAt<T = unknown> = { finishedAt: T }
export type FirstName<T = unknown> = { firstName: T }
export type Folder<T = unknown> = { folder: T }
export type FolderId<T = unknown> = { folderId: T }
export type FolderIds<T = unknown> = { folderIds: T }
export type FolderPath<T = unknown> = { folderPath: T }
export type Folders<T = unknown> = { folders: T }
export type Font<T = unknown> = { font: T }
export type FontFamily<T = unknown> = { fontFamily: T }
export type FontId<T = unknown> = { fontId: T }
export type FontIds<T = unknown> = { fontIds: T }
export type FontName<T = unknown> = { fontName: T }
export type FontPath<T = unknown> = { fontPath: T }
export type FontUrl<T = unknown> = { fontUrl: T }
export type Fonts<T = unknown> = { fonts: T }
export type Force<T = unknown> = { force: T }
export type Form<T = unknown> = { form: T }
export type FormId<T = unknown> = { formId: T }
export type FormIds<T = unknown> = { formIds: T }
export type Format<T = unknown> = { format: T }
export type Formats<T = unknown> = { formats: T }
export type Forms<T = unknown> = { forms: T }
export type FromDate<T = unknown> = { fromDate: T }
export type FromTime<T = unknown> = { fromTime: T }
export type FromTimeMs<T = unknown> = { fromTimeMs: T }
export type FromTimeSec<T = unknown> = { fromTimeSec: T }
export type FullName<T = unknown> = { fullName: T }
export type FunnelLink<T = unknown> = { funnelLink: T }
export type FunnelName<T = unknown> = { funnelName: T }
export type FunnelUrl<T = unknown> = { funnelUrl: T }
export type GID<T = unknown> = { gid: T }
export type GUID<T = unknown> = { guid: T }
export type Game<T = unknown> = { game: T }
export type GameId<T = unknown> = { gameId: T }
export type GameIds<T = unknown> = { gameIds: T }
export type Games<T = unknown> = { games: T }
export type Gender<T = unknown> = { gender: T }
export type Genders<T = unknown> = { genders: T }
export type GeoLocations<T = unknown> = { geoLocations: T }
export type Git<T = unknown> = { git: T }
export type Gitignore<T = unknown> = { gitignore: T }
export type GivenName<T = unknown> = { givenName: T }
export type Google<T = unknown> = { google: T }
export type Group<T = unknown> = { group: T }
export type GroupId<T = unknown> = { groupId: T }
export type GroupIds<T = unknown> = { groupIds: T }
export type GroupName<T = unknown> = { groupName: T }
export type Groups<T = unknown> = { groups: T }
export type Hash<T = unknown> = { hash: T }
export type Header<T = unknown> = { header: T }
export type HeaderKey<T = unknown> = { headerKey: T }
export type HeaderKeys<T = unknown> = { headerKeys: T }
export type HeaderValue<T = unknown> = { headerValue: T }
export type HeaderValues<T = unknown> = { headerValues: T }
export type Headers<T = unknown> = { headers: T }
export type HeadersTimeout<T = unknown> = { headersTimeout: T }
export type Height<T = unknown> = { height: T }
export type Hidden<T = unknown> = { hidden: T }
export type Home<T = unknown> = { home: T }
export type Homepage<T = unknown> = { homepage: T }
export type Hook<T = unknown> = { hook: T }
export type HookId<T = unknown> = { hookId: T }
export type Hooks<T = unknown> = { hooks: T }
export type Host<T = unknown> = { host: T }
export type Hosts<T = unknown> = { hosts: T }
export type Hour<T = unknown> = { hour: T }
export type Hours<T = unknown> = { hours: T }
export type Html<T = unknown> = { html: T }
export type HttpCode<T = unknown> = { httpCode: T }
export type HttpCodes<T = unknown> = { httpCodes: T }
export type HttpOnly<T = unknown> = { httpOnly: T }
export type HttpOptions<T = unknown> = { httpOptions: T }
export type HttpStatus<T = unknown> = { httpStatus: T }
export type ID<T = unknown> = { id: T }
export type IDFA<T = unknown> = { idfa: T }
export type IDFV<T = unknown> = { idfv: T }
export type IOS<T = unknown> = { ios: T }
export type Icon<T = unknown> = { icon: T }
export type IconId<T = unknown> = { iconId: T }
export type IconIds<T = unknown> = { iconIds: T }
export type IconPath<T = unknown> = { iconPath: T }
export type IconUrl<T = unknown> = { iconUrl: T }
export type Icons<T = unknown> = { icons: T }
export type Image<T = unknown> = { image: T }
export type ImageHash<T = unknown> = { imageHash: T }
export type ImageId<T = unknown> = { imageId: T }
export type ImageIds<T = unknown> = { imageIds: T }
export type ImageName<T = unknown> = { imageName: T }
export type ImagePath<T = unknown> = { imagePath: T }
export type ImageUrl<T = unknown> = { imageUrl: T }
export type Images<T = unknown> = { images: T }
export type Img<T = unknown> = { img: T }
export type ImgId<T = unknown> = { imgId: T }
export type ImgIds<T = unknown> = { imgIds: T }
export type ImgName<T = unknown> = { imgName: T }
export type ImgPath<T = unknown> = { imgPath: T }
export type ImgUrl<T = unknown> = { imgUrl: T }
export type Imgs<T = unknown> = { imgs: T }
export type Immutable<T = unknown> = { immutable: T }
export type Import<T = unknown> = { import: T }
export type Imports<T = unknown> = { imports: T }
export type Impression<T = unknown> = { impression: T }
export type Impressions<T = unknown> = { impressions: T }
export type ImprovementAreas<T = unknown> = { improvementAreas: T }
export type InappsOnly<T = unknown> = { inappsOnly: T }
export type Include<T = unknown> = { include: T }
export type IncludeId<T = unknown> = { includeId: T }
export type IncludeIds<T = unknown> = { includeIds: T }
export type IncludePath<T = unknown> = { includePath: T }
export type IncludePaths<T = unknown> = { includePaths: T }
export type Includes<T = unknown> = { includes: T }
export type Increment<T = unknown> = { increment: T }
export type Index<T = unknown> = { index: T }
export type Info<T = unknown> = { info: T }
export type Inject<T = unknown> = { inject: T }
export type Insert<T = unknown> = { insert: T }
export type Insights<T = unknown> = { insights: T }
export type InstagramActorId<T = unknown> = { instagramActorId: T }
export type InstagramPositions<T = unknown> = { instagramPositions: T }
export type Installs<T = unknown> = { installs: T }
export type Internal<T = unknown> = { internal: T }
export type InternalId<T = unknown> = { internalId: T }
export type InternalIds<T = unknown> = { internalIds: T }
export type Internals<T = unknown> = { internals: T }
export type Interval<T = unknown> = { interval: T }
export type IntervalMs<T = unknown> = { intervalMs: T }
export type IntervalSec<T = unknown> = { intervalSec: T }
export type IntroductoryPriceInfo<T = unknown> = { introductoryPriceInfo: T }
export type InvoiceBillingPeriodEndedAt<T = unknown> = { invoiceBillingPeriodEndedAt: T }
export type Invoice<T = unknown> = { invoice: T }
export type InvoiceAmount<T = unknown> = { invoiceAmount: T }
export type InvoiceBillingPeriodStartedAt<T = unknown> = { invoiceBillingPeriodStartedAt: T }
export type InvoiceCreatedAt<T = unknown> = { invoiceCreatedAt: T }
export type InvoiceId<T = unknown> = { invoiceId: T }
export type InvoiceIds<T = unknown> = { invoiceIds: T }
export type InvoiceStatus<T = unknown> = { invoiceStatus: T }
export type InvoiceSubscriptionTermNumber<T = unknown> = { invoiceSubscriptionTermNumber: T }
export type InvoiceUpdatedAt<T = unknown> = { invoiceUpdatedAt: T }
export type Ip<T = unknown> = { ip: T }
export type IpAddress<T = unknown> = { ipAddress: T }
export type IpV4<T = unknown> = { ipV4: T }
export type IpV6<T = unknown> = { ipV6: T }
export type Is<T = unknown> = { is: T }
export type IsDebug<T = unknown> = { isDebug: T }
export type IsDirty<T = unknown> = { isDirty: T }
export type IsDynamicCreative<T = unknown> = { isDynamicCreative: T }
export type IsEnable<T = unknown> = { isEnable: T }
export type IsNullable<T = unknown> = { isNullable: T }
export type IsPreferred<T = unknown> = { isPreferred: T }
export type IsPrivate<T = unknown> = { isPrivate: T }
export type IsPrivateEmail<T = unknown> = { isPrivateEmail: T }
export type IsProduction<T = unknown> = { isProduction: T }
export type IsTrial<T = unknown> = { isTrial: T }
export type IsUsed<T = unknown> = { isUsed: T }
export type IsValid<T = unknown> = { isValid: T }
export type Iso<T = unknown> = { iso: T }
export type Iss<T = unknown> = { iss: T }
export type Issue<T = unknown> = { issue: T }
export type IssueId<T = unknown> = { issueId: T }
export type IssueIds<T = unknown> = { issueIds: T }
export type Issuer<T = unknown> = { issuer: T }
export type Issues<T = unknown> = { issues: T }
export type Item<T = unknown> = { item: T }
export type ItemId<T = unknown> = { itemId: T }
export type ItemIds<T = unknown> = { itemIds: T }
export type ItemName<T = unknown> = { itemName: T }
export type Items<T = unknown> = { items: T }
export type Job<T = unknown> = { job: T }
export type JobId<T = unknown> = { jobId: T }
export type JobIds<T = unknown> = { jobIds: T }
export type Jobs<T = unknown> = { jobs: T }
export type Json<T = unknown> = { json: T }
export type KID<T = unknown> = { kid: T }
export type KeepAliveTimeout<T = unknown> = { keepAliveTimeout: T }
export type Key<T = unknown> = { key: T }
export type KeyId<T = unknown> = { keyId: T }
export type KeyIds<T = unknown> = { keyIds: T }
export type KeyName<T = unknown> = { keyName: T }
export type KeyPath<T = unknown> = { keyPath: T }
export type Keys<T = unknown> = { keys: T }
export type Keyword<T = unknown> = { keyword: T }
export type Keywords<T = unknown> = { keywords: T }
export type Kind<T = unknown> = { kind: T }
export type Label<T = unknown> = { label: T }
export type Language<T = unknown> = { language: T }
export type Languages<T = unknown> = { languages: T }
export type LastName<T = unknown> = { lastName: T }
export type Layer<T = unknown> = { layer: T }
export type Layers<T = unknown> = { layers: T }
export type Left<T = unknown> = { left: T }
export type Length<T = unknown> = { length: T }
export type Letter<T = unknown> = { letter: T }
export type LetterId<T = unknown> = { letterId: T }
export type LetterIds<T = unknown> = { letterIds: T }
export type Letters<T = unknown> = { letters: T }
export type Level<T = unknown> = { level: T }
export type LevelId<T = unknown> = { levelId: T }
export type LevelIds<T = unknown> = { levelIds: T }
export type Levels<T = unknown> = { levels: T }
export type License<T = unknown> = { license: T }
export type Lifetime<T = unknown> = { lifetime: T }
export type Lifo<T = unknown> = { lifo: T }
export type Limit<T = unknown> = { limit: T }
export type Limited<T = unknown> = { limited: T }
export type Limits<T = unknown> = { limits: T }
export type Link<T = unknown> = { link: T }
export type LinkCaption<T = unknown> = { linkCaption: T }
export type LinkData<T = unknown> = { linkData: T }
export type LinkedPurchaseToken<T = unknown> = { linkedPurchaseToken: T }
export type Links<T = unknown> = { links: T }
export type List<T = unknown> = { list: T }
export type ListId<T = unknown> = { listId: T }
export type ListIds<T = unknown> = { listIds: T }
export type Listener<T = unknown> = { listener: T }
export type ListenerId<T = unknown> = { listenerId: T }
export type ListenerIds<T = unknown> = { listenerIds: T }
export type Listeners<T = unknown> = { listeners: T }
export type Lists<T = unknown> = { lists: T }
export type Load<T = unknown> = { load: T }
export type Local<T = unknown> = { local: T }
export type LocalEnv<T = unknown> = { localEnv: T }
export type LocalOffset<T = unknown> = { localOffset: T }
export type Locale<T = unknown> = { locale: T }
export type LocaleId<T = unknown> = { localeId: T }
export type LocaleIds<T = unknown> = { localeIds: T }
export type Locales<T = unknown> = { locales: T }
export type Localhost<T = unknown> = { localhost: T }
export type Localization<T = unknown> = { localization: T }
export type LocalizationId<T = unknown> = { localizationId: T }
export type LocalizationIds<T = unknown> = { localizationIds: T }
export type LocalizationPath<T = unknown> = { localizationPath: T }
export type LocalizationUrl<T = unknown> = { localizationUrl: T }
export type Localizations<T = unknown> = { localizations: T }
export type Location<T = unknown> = { location: T }
export type LocationId<T = unknown> = { locationId: T }
export type LocationIds<T = unknown> = { locationIds: T }
export type LocationName<T = unknown> = { locationName: T }
export type LocationTypes<T = unknown> = { locationTypes: T }
export type Locations<T = unknown> = { locations: T }
export type Log<T = unknown> = { log: T }
export type LogGroup<T = unknown> = { logGroup: T }
export type LogGroups<T = unknown> = { logGroups: T }
export type LogLevel<T = unknown> = { logLevel: T }
export type LogLevels<T = unknown> = { logLevels: T }
export type LogPath<T = unknown> = { logPath: T }
export type LogPaths<T = unknown> = { logPaths: T }
export type Logged<T = unknown> = { logged: T }
export type Logger<T = unknown> = { logger: T }
export type Logging<T = unknown> = { logging: T }
export type Login<T = unknown> = { login: T }
export type Logs<T = unknown> = { logs: T }
export type LtvCurrency<T = unknown> = { ltvCurrency: T }
export type LtvValue<T = unknown> = { ltvValue: T }
export type Main<T = unknown> = { main: T }
export type Margin<T = unknown> = { margin: T }
export type MarginBottom<T = unknown> = { marginBottom: T }
export type MarginLeft<T = unknown> = { marginLeft: T }
export type MarginRight<T = unknown> = { marginRight: T }
export type Marked<T = unknown> = { marked: T }
export type Mask<T = unknown> = { mask: T }
export type Masks<T = unknown> = { masks: T }
export type Master<T = unknown> = { master: T }
export type MasterId<T = unknown> = { masterId: T }
export type MasterIds<T = unknown> = { masterIds: T }
export type Masters<T = unknown> = { masters: T }
export type Material<T = unknown> = { material: T }
export type MaterialId<T = unknown> = { materialId: T }
export type MaterialIds<T = unknown> = { materialIds: T }
export type Materials<T = unknown> = { materials: T }
export type Matrix<T = unknown> = { matrix: T }
export type Max<T = unknown> = { max: T }
export type MaxAge<T = unknown> = { maxAge: T }
export type MaxLength<T = unknown> = { maxLength: T }
export type MaxRecords<T = unknown> = { maxRecords: T }
export type Merchant<T = unknown> = { merchant: T }
export type MerchantId<T = unknown> = { merchantId: T }
export type MerchantIds<T = unknown> = { merchantIds: T }
export type Merchants<T = unknown> = { merchants: T }
export type Message<T = unknown> = { message: T }
export type MessageId<T = unknown> = { messageId: T }
export type MessageIds<T = unknown> = { messageIds: T }
export type Messages<T = unknown> = { messages: T }
export type MessengerPositions<T = unknown> = { messengerPositions: T }
export type Meta<T = unknown> = { meta: T }
export type Metadata<T = unknown> = { metadata: T }
export type MetadataGroup<T = unknown> = { metadataGroup: T }
export type Method<T = unknown> = { method: T }
export type Methods<T = unknown> = { methods: T }
export type Metric<T = unknown> = { metric: T }
export type MetricId<T = unknown> = { metricId: T }
export type MetricIds<T = unknown> = { metricIds: T }
export type Metrics<T = unknown> = { metrics: T }
export type Middleware<T = unknown> = { middleware: T }
export type Migration<T = unknown> = { migration: T }
export type Migrations<T = unknown> = { migrations: T }
export type Milliseconds<T = unknown> = { milliseconds: T }
export type MimeType<T = unknown> = { mimeType: T }
export type Min<T = unknown> = { min: T }
export type MinAge<T = unknown> = { minAge: T }
export type MinLength<T = unknown> = { minLength: T }
export type Minutes<T = unknown> = { minutes: T }
export type Missing<T = unknown> = { missing: T }
export type MissingId<T = unknown> = { missingId: T }
export type MissingIds<T = unknown> = { missingIds: T }
export type MissingName<T = unknown> = { missingName: T }
export type Missings<T = unknown> = { missings: T }
export type Mode<T = unknown> = { mode: T }
export type Model<T = unknown> = { model: T }
export type ModelId<T = unknown> = { modelId: T }
export type ModelIds<T = unknown> = { modelIds: T }
export type ModelName<T = unknown> = { modelName: T }
export type Models<T = unknown> = { models: T }
export type Modes<T = unknown> = { modes: T }
export type Module<T = unknown> = { module: T }
export type Modules<T = unknown> = { modules: T }
export type Months<T = unknown> = { months: T }
export type Multiplier<T = unknown> = { multiplier: T }
export type Mutable<T = unknown> = { mutable: T }
export type Name<T = unknown> = { name: T }
export type Namespace<T = unknown> = { namespace: T }
export type NamespaceId<T = unknown> = { namespaceId: T }
export type NamespaceIds<T = unknown> = { namespaceIds: T }
export type Namespaces<T = unknown> = { namespaces: T }
export type Next<T = unknown> = { next: T }
export type NextDate<T = unknown> = { nextDate: T }
export type NextPageUrl<T = unknown> = { nextPageUrl: T }
export type Node<T = unknown> = { node: T }
export type NodeId<T = unknown> = { nodeId: T }
export type NodeIds<T = unknown> = { nodeIds: T }
export type Nodes<T = unknown> = { nodes: T }
export type Not<T = unknown> = { not: T }
export type Note<T = unknown> = { note: T }
export type NoteId<T = unknown> = { noteId: T }
export type NoteIds<T = unknown> = { noteIds: T }
export type Notes<T = unknown> = { notes: T }
export type Notification<T = unknown> = { notification: T }
export type NotificationId<T = unknown> = { notificationId: T }
export type NotificationIds<T = unknown> = { notificationIds: T }
export type NotificationType<T = unknown> = { notificationType: T }
export type Notifications<T = unknown> = { notifications: T }
export type Nullable<T = unknown> = { nullable: T }
export type OS<T = unknown> = { os: T }
export type ObfuscatedExternalAccountId<T = unknown> = { obfuscatedExternalAccountId: T }
export type ObfuscatedExternalProfileId<T = unknown> = { obfuscatedExternalProfileId: T }
export type Object<T = unknown> = { object: T }
export type ObjectId<T = unknown> = { objectId: T }
export type ObjectIds<T = unknown> = { objectIds: T }
export type ObjectStoreUrl<T = unknown> = { objectStoreUrl: T }
export type ObjectStorySpec<T = unknown> = { objectStorySpec: T }
export type ObjectType<T = unknown> = { objectType: T }
export type Objective<T = unknown> = { objective: T }
export type ObjectiveType<T = unknown> = { objectiveType: T }
export type Objects<T = unknown> = { objects: T }
export type Offer<T = unknown> = { offer: T }
export type OfferId<T = unknown> = { offerId: T }
export type OfferIds<T = unknown> = { offerIds: T }
export type Offers<T = unknown> = { offers: T }
export type Offset<T = unknown> = { offset: T }
export type OffsetX<T = unknown> = { offsetX: T }
export type OffsetY<T = unknown> = { offsetY: T }
export type OffsetZ<T = unknown> = { offsetZ: T }
export type Offsets<T = unknown> = { offsets: T }
export type OnCreate<T = unknown> = { onCreate: T }
export type OnDelete<T = unknown> = { onDelete: T }
export type OnUpdate<T = unknown> = { onUpdate: T }
export type Operation<T = unknown> = { operation: T }
export type OperationId<T = unknown> = { operationId: T }
export type OperationIds<T = unknown> = { operationIds: T }
export type OperationType<T = unknown> = { operationType: T }
export type Operations<T = unknown> = { operations: T }
export type OptimizationGoal<T = unknown> = { optimizationGoal: T }
export type Option<T = unknown> = { option: T }
export type Options<T = unknown> = { options: T }
export type Or<T = unknown> = { or: T }
export type Order<T = unknown> = { order: T }
export type OrderAmount<T = unknown> = { orderAmount: T }
export type OrderCurrency<T = unknown> = { orderCurrency: T }
export type OrderDescription<T = unknown> = { orderDescription: T }
export type OrderId<T = unknown> = { orderId: T }
export type OrderIds<T = unknown> = { orderIds: T }
export type OrderMetadata<T = unknown> = { orderMetadata: T }
export type OrderStatus<T = unknown> = { orderStatus: T }
export type Ordered<T = unknown> = { ordered: T }
export type Orders<T = unknown> = { orders: T }
export type Origin<T = unknown> = { origin: T }
export type OriginId<T = unknown> = { originId: T }
export type OriginIds<T = unknown> = { originIds: T }
export type OriginOrderId<T = unknown> = { originOrderId: T }
export type OriginalProductId<T = unknown> = { originalProductId: T }
export type Origins<T = unknown> = { origins: T }
export type Owner<T = unknown> = { owner: T }
export type OwnerId<T = unknown> = { ownerId: T }
export type OwnerIds<T = unknown> = { ownerIds: T }
export type OwnerName<T = unknown> = { ownerName: T }
export type Owners<T = unknown> = { owners: T }
export type PID<T = unknown> = { pid: T }
export type PIN<T = unknown> = { pin: T }
export type PUK<T = unknown> = { puk: T }
export type Package<T = unknown> = { package: T }
export type PackageId<T = unknown> = { packageId: T }
export type PackageIds<T = unknown> = { packageIds: T }
export type PackageName<T = unknown> = { packageName: T }
export type Packages<T = unknown> = { packages: T }
export type Padding<T = unknown> = { padding: T }
export type PaddingBottom<T = unknown> = { paddingBottom: T }
export type PaddingLeft<T = unknown> = { paddingLeft: T }
export type PaddingRight<T = unknown> = { paddingRight: T }
export type Page<T = unknown> = { page: T }
export type PageId<T = unknown> = { pageId: T }
export type PageIds<T = unknown> = { pageIds: T }
export type PageInfo<T = unknown> = { pageInfo: T }
export type PageSize<T = unknown> = { pageSize: T }
export type PageUrl<T = unknown> = { pageUrl: T }
export type Pagination<T = unknown> = { pagination: T }
export type Paging<T = unknown> = { paging: T }
export type Param<T = unknown> = { param: T }
export type Params<T = unknown> = { params: T }
export type Part<T = unknown> = { part: T }
export type PartId<T = unknown> = { partId: T }
export type PartIds<T = unknown> = { partIds: T }
export type Parts<T = unknown> = { parts: T }
export type Password<T = unknown> = { password: T }
export type Path<T = unknown> = { path: T }
export type Paths<T = unknown> = { paths: T }
export type Pause<T = unknown> = { pause: T }
export type Paused<T = unknown> = { paused: T }
export type PausedAt<T = unknown> = { pausedAt: T }
export type PausedFrom<T = unknown> = { pausedFrom: T }
export type PausedTo<T = unknown> = { pausedTo: T }
export type PayForm<T = unknown> = { payForm: T }
export type Payer<T = unknown> = { payer: T }
export type PayerId<T = unknown> = { payerId: T }
export type PayerIds<T = unknown> = { payerIds: T }
export type Payers<T = unknown> = { payers: T }
export type Payload<T = unknown> = { payload: T }
export type Payment<T = unknown> = { payment: T }
export type PaymentCurrency<T = unknown> = { paymentCurrency: T }
export type PaymentDescription<T = unknown> = { paymentDescription: T }
export type PaymentId<T = unknown> = { paymentId: T }
export type PaymentIds<T = unknown> = { paymentIds: T }
export type PaymentMethod<T = unknown> = { paymentMethod: T }
export type PaymentNumber<T = unknown> = { paymentNumber: T }
export type PaymentState<T = unknown> = { paymentState: T }
export type PaymentStatus<T = unknown> = { paymentStatus: T }
export type PaymentType<T = unknown> = { paymentType: T }
export type Payments<T = unknown> = { payments: T }
export type PaymentsNumber<T = unknown> = { paymentsNumber: T }
export type Permission<T = unknown> = { permission: T }
export type PermissionId<T = unknown> = { permissionId: T }
export type PermissionIds<T = unknown> = { permissionIds: T }
export type Permissions<T = unknown> = { permissions: T }
export type PhoneNumber<T = unknown> = { phoneNumber: T }
export type PixelCode<T = unknown> = { pixelCode: T }
export type PixelEvent<T = unknown> = { pixelEvent: T }
export type PixelEvents<T = unknown> = { pixelEvents: T }
export type PixelId<T = unknown> = { pixelId: T }
export type Placement<T = unknown> = { placement: T }
export type PlacementId<T = unknown> = { placementId: T }
export type PlacementIds<T = unknown> = { placementIds: T }
export type Placements<T = unknown> = { placements: T }
export type Platform<T = unknown> = { platform: T }
export type PlatformId<T = unknown> = { platformId: T }
export type PlatformIds<T = unknown> = { platformIds: T }
export type PlatformName<T = unknown> = { platformName: T }
export type Platforms<T = unknown> = { platforms: T }
export type Player<T = unknown> = { player: T }
export type PlayerId<T = unknown> = { playerId: T }
export type PlayerIds<T = unknown> = { playerIds: T }
export type Players<T = unknown> = { players: T }
export type Point<T = unknown> = { point: T }
export type PointId<T = unknown> = { pointId: T }
export type PointIds<T = unknown> = { pointIds: T }
export type Pointer<T = unknown> = { pointer: T }
export type Points<T = unknown> = { points: T }
export type Port<T = unknown> = { port: T }
export type Position<T = unknown> = { position: T }
export type PositionX<T = unknown> = { positionX: T }
export type PositionY<T = unknown> = { positionY: T }
export type PositionZ<T = unknown> = { positionZ: T }
export type Positions<T = unknown> = { positions: T }
export type Post<T = unknown> = { post: T }
export type PostId<T = unknown> = { postId: T }
export type PostIds<T = unknown> = { postIds: T }
export type PostalCode<T = unknown> = { postalCode: T }
export type Posts<T = unknown> = { posts: T }
export type Preferences<T = unknown> = { preferences: T }
export type Prefix<T = unknown> = { prefix: T }
export type Price<T = unknown> = { price: T }
export type PriceAmountMicros<T = unknown> = { priceAmountMicros: T }
export type PriceChange<T = unknown> = { priceChange: T }
export type PriceCurrencyCode<T = unknown> = { priceCurrencyCode: T }
export type Prices<T = unknown> = { prices: T }
export type Primary<T = unknown> = { primary: T }
export type Priority<T = unknown> = { priority: T }
export type Private<T = unknown> = { private: T }
export type PrivateEmail<T = unknown> = { privateEmail: T }
export type PrivateKey<T = unknown> = { privateKey: T }
export type Process<T = unknown> = { process: T }
export type ProcessId<T = unknown> = { processId: T }
export type ProcessIds<T = unknown> = { processIds: T }
export type ProcessName<T = unknown> = { processName: T }
export type Processed<T = unknown> = { processed: T }
export type Processes<T = unknown> = { processes: T }
export type Processor<T = unknown> = { processor: T }
export type Prod<T = unknown> = { prod: T }
export type Product<T = unknown> = { product: T }
export type ProductAmount<T = unknown> = { productAmount: T }
export type ProductCurrency<T = unknown> = { productCurrency: T }
export type ProductId<T = unknown> = { productId: T }
export type ProductIds<T = unknown> = { productIds: T }
export type ProductName<T = unknown> = { productName: T }
export type ProductPaymentAction<T = unknown> = { productPaymentAction: T }
export type ProductTrial<T = unknown> = { productTrial: T }
export type ProductTrialAmount<T = unknown> = { productTrialAmount: T }
export type ProductTrialCurrency<T = unknown> = { productTrialCurrency: T }
export type ProductTrialPeriod<T = unknown> = { productTrialPeriod: T }
export type Production<T = unknown> = { production: T }
export type Products<T = unknown> = { products: T }
export type Profile<T = unknown> = { profile: T }
export type ProfileId<T = unknown> = { profileId: T }
export type ProfileIds<T = unknown> = { profileIds: T }
export type ProfileName<T = unknown> = { profileName: T }
export type Profiles<T = unknown> = { profiles: T }
export type Project<T = unknown> = { project: T }
export type ProjectId<T = unknown> = { projectId: T }
export type ProjectIds<T = unknown> = { projectIds: T }
export type Projects<T = unknown> = { projects: T }
export type PromotedObject<T = unknown> = { promotedObject: T }
export type PromotionCode<T = unknown> = { promotionCode: T }
export type PromotionType<T = unknown> = { promotionType: T }
export type Properties<T = unknown> = { properties: T }
export type Property<T = unknown> = { property: T }
export type PropertyId<T = unknown> = { propertyId: T }
export type PropertyIds<T = unknown> = { propertyIds: T }
export type Props<T = unknown> = { props: T }
export type Provider<T = unknown> = { provider: T }
export type Providers<T = unknown> = { providers: T }
export type Public<T = unknown> = { public: T }
export type PublicEmail<T = unknown> = { publicEmail: T }
export type PublicKey<T = unknown> = { publicKey: T }
export type PublicPath<T = unknown> = { publicPath: T }
export type Publication<T = unknown> = { publication: T }
export type PublicationId<T = unknown> = { publicationId: T }
export type PublicationIds<T = unknown> = { publicationIds: T }
export type Publications<T = unknown> = { publications: T }
export type PublishTime<T = unknown> = { publishTime: T }
export type PublishTimeMs<T = unknown> = { publishTimeMs: T }
export type PublishTimeSec<T = unknown> = { publishTimeSec: T }
export type Published<T = unknown> = { published: T }
export type PublishedAt<T = unknown> = { publishedAt: T }
export type Publisher<T = unknown> = { publisher: T }
export type PublisherId<T = unknown> = { publisherId: T }
export type PublisherIds<T = unknown> = { publisherIds: T }
export type PublisherName<T = unknown> = { publisherName: T }
export type PublisherPlatforms<T = unknown> = { publisherPlatforms: T }
export type Publishers<T = unknown> = { publishers: T }
export type Purchase<T = unknown> = { purchase: T }
export type PurchaseDate<T = unknown> = { purchaseDate: T }
export type PurchaseId<T = unknown> = { purchaseId: T }
export type PurchaseIds<T = unknown> = { purchaseIds: T }
export type PurchaseName<T = unknown> = { purchaseName: T }
export type PurchaseState<T = unknown> = { purchaseState: T }
export type PurchaseTimeMs<T = unknown> = { purchaseTimeMs: T }
export type PurchaseToken<T = unknown> = { purchaseToken: T }
export type PurchaseType<T = unknown> = { purchaseType: T }
export type Purchases<T = unknown> = { purchases: T }
export type Quantity<T = unknown> = { quantity: T }
export type Queries<T = unknown> = { queries: T }
export type Query<T = unknown> = { query: T }
export type Question<T = unknown> = { question: T }
export type QuestionId<T = unknown> = { questionId: T }
export type QuestionIds<T = unknown> = { questionIds: T }
export type Questions<T = unknown> = { questions: T }
export type Queue<T = unknown> = { queue: T }
export type QueueId<T = unknown> = { queueId: T }
export type QueueIds<T = unknown> = { queueIds: T }
export type QueueName<T = unknown> = { queueName: T }
export type QueueUrl<T = unknown> = { queueUrl: T }
export type Queues<T = unknown> = { queues: T }
export type Radius<T = unknown> = { radius: T }
export type Range<T = unknown> = { range: T }
export type Ranges<T = unknown> = { ranges: T }
export type Rating<T = unknown> = { rating: T }
export type Ratio<T = unknown> = { ratio: T }
export type Raw<T = unknown> = { raw: T }
export type RawBody<T = unknown> = { rawBody: T }
export type ReSave<T = unknown> = { reSave: T }
export type Reason<T = unknown> = { reason: T }
export type ReasonId<T = unknown> = { reasonId: T }
export type ReasonIds<T = unknown> = { reasonIds: T }
export type Reasons<T = unknown> = { reasons: T }
export type Receipt<T = unknown> = { receipt: T }
export type ReceiptHandle<T = unknown> = { receiptHandle: T }
export type ReceiptId<T = unknown> = { receiptId: T }
export type ReceiptIds<T = unknown> = { receiptIds: T }
export type Receipts<T = unknown> = { receipts: T }
export type Record<T = unknown> = { record: T }
export type RecordId<T = unknown> = { recordId: T }
export type RecordIds<T = unknown> = { recordIds: T }
export type RecordName<T = unknown> = { recordName: T }
export type RecordType<T = unknown> = { recordType: T }
export type Records<T = unknown> = { records: T }
export type Redis<T = unknown> = { redis: T }
export type RedisHost<T = unknown> = { redisHost: T }
export type RedisPassword<T = unknown> = { redisPassword: T }
export type RedisPort<T = unknown> = { redisPort: T }
export type RedisUrl<T = unknown> = { redisUrl: T }
export type RedisUser<T = unknown> = { redisUser: T }
export type Ref<T = unknown> = { ref: T }
export type Reference<T = unknown> = { reference: T }
export type References<T = unknown> = { references: T }
export type Referrer<T = unknown> = { referrer: T }
export type RefreshToken<T = unknown> = { refreshToken: T }
export type RefundCurrency<T = unknown> = { refundCurrency: T }
export type RefundReason<T = unknown> = { refundReason: T }
export type RefundReasonCode<T = unknown> = { refundReasonCode: T }
export type RefundedAmount<T = unknown> = { refundedAmount: T }
export type RefundedAt<T = unknown> = { refundedAt: T }
export type Region<T = unknown> = { region: T }
export type RegionCode<T = unknown> = { regionCode: T }
export type Regions<T = unknown> = { regions: T }
export type Relation<T = unknown> = { relation: T }
export type RelationId<T = unknown> = { relationId: T }
export type RelationIds<T = unknown> = { relationIds: T }
export type Relations<T = unknown> = { relations: T }
export type RelativeUrl<T = unknown> = { relativeUrl: T }
export type Remote<T = unknown> = { remote: T }
export type Remove<T = unknown> = { remove: T }
export type RenewalNumber<T = unknown> = { renewalNumber: T }
export type Replica<T = unknown> = { replica: T }
export type ReplicaId<T = unknown> = { replicaId: T }
export type ReplicaIds<T = unknown> = { replicaIds: T }
export type ReplicaName<T = unknown> = { replicaName: T }
export type ReplicaUrl<T = unknown> = { replicaUrl: T }
export type Replicas<T = unknown> = { replicas: T }
export type Replication<T = unknown> = { replication: T }
export type ReplicationId<T = unknown> = { replicationId: T }
export type ReplicationIds<T = unknown> = { replicationIds: T }
export type Replications<T = unknown> = { replications: T }
export type Report<T = unknown> = { report: T }
export type ReportId<T = unknown> = { reportId: T }
export type ReportIds<T = unknown> = { reportIds: T }
export type ReportType<T = unknown> = { reportType: T }
export type Reports<T = unknown> = { reports: T }
export type Repositories<T = unknown> = { repositories: T }
export type Repository<T = unknown> = { repository: T }
export type RepositoryUrl<T = unknown> = { repositoryUrl: T }
export type Req<T = unknown> = { req: T }
export type Request<T = unknown> = { request: T }
export type RequestBody<T = unknown> = { requestBody: T }
export type RequestId<T = unknown> = { requestId: T }
export type RequestIds<T = unknown> = { requestIds: T }
export type Requests<T = unknown> = { requests: T }
export type Res<T = unknown> = { res: T }
export type Resource<T = unknown> = { resource: T }
export type ResourceId<T = unknown> = { resourceId: T }
export type ResourceIds<T = unknown> = { resourceIds: T }
export type ResourceName<T = unknown> = { resourceName: T }
export type ResourcePath<T = unknown> = { resourcePath: T }
export type ResourceUrl<T = unknown> = { resourceUrl: T }
export type Resources<T = unknown> = { resources: T }
export type Response<T = unknown> = { response: T }
export type ResponseBody<T = unknown> = { responseBody: T }
export type ResponseId<T = unknown> = { responseId: T }
export type ResponseIds<T = unknown> = { responseIds: T }
export type Responses<T = unknown> = { responses: T }
export type Result<T = unknown> = { result: T }
export type ResultId<T = unknown> = { resultId: T }
export type ResultIds<T = unknown> = { resultIds: T }
export type Results<T = unknown> = { results: T }
export type Retry<T = unknown> = { retry: T }
export type RetryCount<T = unknown> = { tryCount: T }
export type Review<T = unknown> = { review: T }
export type ReviewId<T = unknown> = { reviewId: T }
export type ReviewIds<T = unknown> = { reviewIds: T }
export type Reviews<T = unknown> = { reviews: T }
export type Right<T = unknown> = { right: T }
export type Role<T = unknown> = { role: T }
export type RoleId<T = unknown> = { roleId: T }
export type RoleIds<T = unknown> = { roleIds: T }
export type RoleName<T = unknown> = { roleName: T }
export type Roles<T = unknown> = { roles: T }
export type Rolling<T = unknown> = { rolling: T }
export type Rotation<T = unknown> = { rotation: T }
export type RotationX<T = unknown> = { rotationX: T }
export type RotationY<T = unknown> = { rotationY: T }
export type RotationZ<T = unknown> = { rotationZ: T }
export type Rotations<T = unknown> = { rotations: T }
export type Route<T = unknown> = { route: T }
export type Routes<T = unknown> = { routes: T }
export type Row<T = unknown> = { row: T }
export type RowId<T = unknown> = { rowId: T }
export type RowIds<T = unknown> = { rowIds: T }
export type RowIndex<T = unknown> = { rowIndex: T }
export type Rows<T = unknown> = { rows: T }
export type SETID<T = unknown> = { setid: T }
export type SSL<T = unknown> = { ssl: T }
export type Salt<T = unknown> = { salt: T }
export type SameSite<T = unknown> = { sameSite: T }
export type SaveUninitialized<T = unknown> = { saveUninitialized: T }
export type Scale<T = unknown> = { scale: T }
export type ScaleX<T = unknown> = { scaleX: T }
export type ScaleY<T = unknown> = { scaleY: T }
export type ScaleZ<T = unknown> = { scaleZ: T }
export type Scales<T = unknown> = { scales: T }
export type Scenario<T = unknown> = { scenario: T }
export type ScenarioId<T = unknown> = { scenarioId: T }
export type ScenarioIds<T = unknown> = { scenarioIds: T }
export type Scenarios<T = unknown> = { scenarios: T }
export type Schedule<T = unknown> = { schedule: T }
export type Scheduled<T = unknown> = { scheduled: T }
export type Scheduler<T = unknown> = { scheduler: T }
export type Schema<T = unknown> = { schema: T }
export type SchemaId<T = unknown> = { schemaId: T }
export type SchemaIds<T = unknown> = { schemaIds: T }
export type SchemaName<T = unknown> = { schemaName: T }
export type Schemas<T = unknown> = { schemas: T }
export type Scope<T = unknown> = { scope: T }
export type Scopes<T = unknown> = { scopes: T }
export type Screen<T = unknown> = { screen: T }
export type Screenshot<T = unknown> = { screenshot: T }
export type ScreenshotId<T = unknown> = { screenshotId: T }
export type ScreenshotIds<T = unknown> = { screenshotIds: T }
export type ScreenshotName<T = unknown> = { screenshotName: T }
export type ScreenshotPath<T = unknown> = { screenshotPath: T }
export type ScreenshotUrl<T = unknown> = { screenshotUrl: T }
export type Screenshots<T = unknown> = { screenshots: T }
export type Sdk<T = unknown> = { sdk: T }
export type Secondary<T = unknown> = { secondary: T }
export type Seconds<T = unknown> = { seconds: T }
export type Secret<T = unknown> = { secret: T }
export type SecretKey<T = unknown> = { secretKey: T }
export type Secure<T = unknown> = { secure: T }
export type Select<T = unknown> = { select: T }
export type Selected<T = unknown> = { selected: T }
export type Selector<T = unknown> = { selector: T }
export type Self<T = unknown> = { self: T }
export type Sender<T = unknown> = { sender: T }
export type SenderId<T = unknown> = { senderId: T }
export type SenderIds<T = unknown> = { senderIds: T }
export type SenderName<T = unknown> = { senderName: T }
export type Senders<T = unknown> = { senders: T }
export type Sent<T = unknown> = { sent: T }
export type Separator<T = unknown> = { separator: T }
export type Sequence<T = unknown> = { sequence: T }
export type SequenceId<T = unknown> = { sequenceId: T }
export type SequenceIds<T = unknown> = { sequenceIds: T }
export type Sequences<T = unknown> = { sequences: T }
export type Server<T = unknown> = { server: T }
export type ServerHost<T = unknown> = { serverHost: T }
export type ServerPort<T = unknown> = { serverPort: T }
export type ServerUrl<T = unknown> = { serverUrl: T }
export type Service<T = unknown> = { service: T }
export type ServiceId<T = unknown> = { serviceId: T }
export type ServiceIds<T = unknown> = { serviceIds: T }
export type ServiceName<T = unknown> = { serviceName: T }
export type ServicePath<T = unknown> = { servicePath: T }
export type ServiceType<T = unknown> = { serviceType: T }
export type ServiceUrl<T = unknown> = { serviceUrl: T }
export type Services<T = unknown> = { services: T }
export type Session<T = unknown> = { session: T }
export type SessionId<T = unknown> = { sessionId: T }
export type SessionIds<T = unknown> = { sessionIds: T }
export type Sessions<T = unknown> = { sessions: T }
export type Set<T = unknown> = { set: T }
export type SetId<T = unknown> = { setId: T }
export type SetIds<T = unknown> = { setIds: T }
export type Sets<T = unknown> = { sets: T }
export type Settings<T = unknown> = { settings: T }
export type Setup<T = unknown> = { setup: T }
export type SetupId<T = unknown> = { setupId: T }
export type SetupIds<T = unknown> = { setupIds: T }
export type Setups<T = unknown> = { setups: T }
export type Sheet<T = unknown> = { sheet: T }
export type SheetId<T = unknown> = { sheetId: T }
export type SheetIds<T = unknown> = { sheetIds: T }
export type SheetName<T = unknown> = { sheetName: T }
export type Sheets<T = unknown> = { sheets: T }
export type ShutdownDelay<T = unknown> = { shutdownDelay: T }
export type Signature<T = unknown> = { signature: T }
export type Since<T = unknown> = { since: T }
export type Size<T = unknown> = { size: T }
export type SkadnetworkAttribution<T = unknown> = { isSkadnetworkAttribution: T }
export type Skip<T = unknown> = { skip: T }
export type Slack<T = unknown> = { slack: T }
export type Slave<T = unknown> = { slave: T }
export type SlaveId<T = unknown> = { slaveId: T }
export type SlaveIds<T = unknown> = { slaveIds: T }
export type Slaves<T = unknown> = { slaves: T }
export type SmartPromotionType<T = unknown> = { smartPromotionType: T }
export type Snapshot<T = unknown> = { snapshot: T }
export type SnapshotId<T = unknown> = { snapshotId: T }
export type SnapshotIds<T = unknown> = { snapshotIds: T }
export type SnapshotUrl<T = unknown> = { snapshotUrl: T }
export type Snapshots<T = unknown> = { snapshots: T }
export type Sort<T = unknown> = { sort: T }
export type Source<T = unknown> = { source: T }
export type SpecialAdCategories<T = unknown> = { specialAdCategories: T }
export type Spend<T = unknown> = { spend: T }
export type Spends<T = unknown> = { spends: T }
export type Stage<T = unknown> = { stage: T }
export type StandardEnhancements<T = unknown> = { standardEnhancements: T }
export type StartDate<T = unknown> = { startDate: T }
export type StartOffset<T = unknown> = { startOffset: T }
export type StartTime<T = unknown> = { startTime: T }
export type StartTimeMs<T = unknown> = { startTimeMs: T }
export type StartedAt<T = unknown> = { startedAt: T }
export type State<T = unknown> = { state: T }
export type States<T = unknown> = { states: T }
export type Stats<T = unknown> = { stats: T }
export type Status<T = unknown> = { status: T }
export type Storage<T = unknown> = { storage: T }
export type StorageId<T = unknown> = { storageId: T }
export type StorageIds<T = unknown> = { storageIds: T }
export type StorageName<T = unknown> = { storageName: T }
export type StoragePath<T = unknown> = { storagePath: T }
export type StorageUrl<T = unknown> = { storageUrl: T }
export type Store<T = unknown> = { store: T }
export type StoreId<T = unknown> = { storeId: T }
export type StoreIds<T = unknown> = { storeIds: T }
export type StoreName<T = unknown> = { storeName: T }
export type Strategies<T = unknown> = { strategies: T }
export type Strategy<T = unknown> = { strategy: T }
export type StrategyId<T = unknown> = { strategyId: T }
export type StrategyIds<T = unknown> = { strategyIds: T }
export type StrategyName<T = unknown> = { strategyName: T }
export type Stream<T = unknown> = { stream: T }
export type StreamId<T = unknown> = { streamId: T }
export type StreamIds<T = unknown> = { streamIds: T }
export type StreamName<T = unknown> = { streamName: T }
export type Streams<T = unknown> = { streams: T }
export type SubNextChargeAt<T = unknown> = { subNextChargeAt: T }
export type Subject<T = unknown> = { subject: T }
export type SubjectId<T = unknown> = { subjectId: T }
export type SubjectIds<T = unknown> = { subjectIds: T }
export type Subjects<T = unknown> = { subjects: T }
export type Subscriber<T = unknown> = { subscriber: T }
export type SubscriberId<T = unknown> = { subscriberId: T }
export type SubscriberIds<T = unknown> = { subscriberIds: T }
export type Subscribers<T = unknown> = { subscribers: T }
export type Subscription<T = unknown> = { subscription: T }
export type SubscriptionExpiredAt<T = unknown> = { subscriptionExpiredAt: T }
export type SubscriptionId<T = unknown> = { subscriptionId: T }
export type SubscriptionIds<T = unknown> = { subscriptionIds: T }
export type SubscriptionNextChargeAt<T = unknown> = { subscriptionNextChargeAt: T }
export type SubscriptionPaymentType<T = unknown> = { subscriptionPaymentType: T }
export type SubscriptionStartedAt<T = unknown> = { subscriptionStartedAt: T }
export type SubscriptionStatus<T = unknown> = { subscriptionStatus: T }
export type SubscriptionTrial<T = unknown> = { subscriptionTrial: T }
export type SubscriptionUpdatedAt<T = unknown> = { subscriptionUpdatedAt: T }
export type Subscriptions<T = unknown> = { subscriptions: T }
export type Success<T = unknown> = { success: T }
export type Sum<T = unknown> = { sum: T }
export type Summary<T = unknown> = { summary: T }
export type Synchronize<T = unknown> = { synchronize: T }
export type Table<T = unknown> = { table: T }
export type TableId<T = unknown> = { tableId: T }
export type TableIds<T = unknown> = { tableIds: T }
export type TableName<T = unknown> = { tableName: T }
export type Tables<T = unknown> = { tables: T }
export type Tag<T = unknown> = { tag: T }
export type TagId<T = unknown> = { tagId: T }
export type TagIds<T = unknown> = { tagIds: T }
export type Tags<T = unknown> = { tags: T }
export type Take<T = unknown> = { take: T }
export type Target<T = unknown> = { target: T }
export type TargetId<T = unknown> = { targetId: T }
export type TargetIds<T = unknown> = { targetIds: T }
export type Targeting<T = unknown> = { targeting: T }
export type Targets<T = unknown> = { targets: T }
export type Task<T = unknown> = { task: T }
export type TaskId<T = unknown> = { taskId: T }
export type TaskIds<T = unknown> = { taskIds: T }
export type Tasks<T = unknown> = { tasks: T }
export type Taxes<T = unknown> = { taxes: T }
export type Template<T = unknown> = { template: T }
export type TemplateId<T = unknown> = { templateId: T }
export type TemplateIds<T = unknown> = { templateIds: T }
export type TemplateName<T = unknown> = { templateName: T }
export type TemplatePath<T = unknown> = { templatePath: T }
export type TemplateUrl<T = unknown> = { templateUrl: T }
export type Templates<T = unknown> = { templates: T }
export type Territories<T = unknown> = { territories: T }
export type Territory<T = unknown> = { territory: T }
export type TestNotification<T = unknown> = { testNotification: T }
export type Text<T = unknown> = { text: T }
export type TextSize<T = unknown> = { textSize: T }
export type Throttle<T = unknown> = { throttle: T }
export type ThrottleMs<T = unknown> = { throttleMs: T }
export type ThrottleSec<T = unknown> = { throttleSec: T }
export type Ticket<T = unknown> = { ticket: T }
export type TicketId<T = unknown> = { ticketId: T }
export type TicketIds<T = unknown> = { ticketIds: T }
export type Tickets<T = unknown> = { tickets: T }
export type Tiktok<T = unknown> = { tiktok: T }
export type Time<T = unknown> = { time: T }
export type TimeAccountTz<T = unknown> = { timeAccountTz: T }
export type TimeRange<T = unknown> = { timeRange: T }
export type TimeUtc<T = unknown> = { timeUtc: T }
export type Timeout<T = unknown> = { timeout: T }
export type TimeoutMs<T = unknown> = { timeoutMs: T }
export type TimeoutSec<T = unknown> = { timeoutSec: T }
export type Timer<T = unknown> = { timer: T }
export type Timestamp<T = unknown> = { timestamp: T }
export type TimestampUtc<T = unknown> = { timestampUtc: T }
export type Timezone<T = unknown> = { timezone: T }
export type TimezoneOffset<T = unknown> = { timezoneOffset: T }
export type Title<T = unknown> = { title: T }
export type Tmp<T = unknown> = { tmp: T }
export type TmpPath<T = unknown> = { tmpPath: T }
export type ToDate<T = unknown> = { toDate: T }
export type ToTime<T = unknown> = { toTime: T }
export type ToTimeMs<T = unknown> = { toTimeMs: T }
export type ToTimeSec<T = unknown> = { toTimeSec: T }
export type Token<T = unknown> = { token: T }
export type TokenId<T = unknown> = { tokenId: T }
export type TokenIds<T = unknown> = { tokenIds: T }
export type TokenType<T = unknown> = { tokenType: T }
export type Tokens<T = unknown> = { tokens: T }
export type Tool<T = unknown> = { tool: T }
export type ToolId<T = unknown> = { toolId: T }
export type ToolIds<T = unknown> = { toolIds: T }
export type Tools<T = unknown> = { tools: T }
export type Top<T = unknown> = { top: T }
export type Topic<T = unknown> = { topic: T }
export type TopicId<T = unknown> = { topicId: T }
export type TopicIds<T = unknown> = { topicIds: T }
export type TopicName<T = unknown> = { topicName: T }
export type Topics<T = unknown> = { topics: T }
export type TotalClicks<T = unknown> = { totalClicks: T }
export type TotalCount<T = unknown> = { totalCount: T }
export type TotalImpressions<T = unknown> = { totalImpressions: T }
export type TotalInstalls<T = unknown> = { totalInstalls: T }
export type TotalNumber<T = unknown> = { totalNumber: T }
export type TotalSpend<T = unknown> = { totalSpend: T }
export type Town<T = unknown> = { town: T }
export type Transaction<T = unknown> = { transaction: T }
export type TransactionId<T = unknown> = { transactionId: T }
export type TransactionIds<T = unknown> = { transactionIds: T }
export type TransactionToken<T = unknown> = { transactionToken: T }
export type Transactions<T = unknown> = { transactions: T }
export type Transformer<T = unknown> = { transformer: T }
export type Trial<T = unknown> = { trial: T }
export type Ttl<T = unknown> = { ttl: T }
export type TtlMs<T = unknown> = { ttlMs: T }
export type TtlSec<T = unknown> = { ttlSec: T }
export type Type<T = unknown> = { type: T }
export type TypeId<T = unknown> = { typeId: T }
export type TypeIds<T = unknown> = { typeIds: T }
export type Types<T = unknown> = { types: T }
export type UUID<T = unknown> = { uuid: T }
export type Unique<T = unknown> = { unique: T }
export type UniqueId<T = unknown> = { uniqueId: T }
export type UniqueIds<T = unknown> = { uniqueIds: T }
export type Uniques<T = unknown> = { uniques: T }
export type Unit<T = unknown> = { unit: T }
export type UnitId<T = unknown> = { unitId: T }
export type UnitIds<T = unknown> = { unitIds: T }
export type UnitName<T = unknown> = { unitName: T }
export type Units<T = unknown> = { units: T }
export type Unlimited<T = unknown> = { unlimited: T }
export type Until<T = unknown> = { until: T }
export type Update<T = unknown> = { update: T }
export type UpdatedAt<T = unknown> = { updatedAt: T }
export type UploadSessionId<T = unknown> = { uploadSessionId: T }
export type Uri<T = unknown> = { uri: T }
export type Url<T = unknown> = { url: T }
export type UrlTags<T = unknown> = { urlTags: T }
export type Use<T = unknown> = { use: T }
export type UseCase<T = unknown> = { useCase: T }
export type UseDefault<T = unknown> = { useDefault: T }
export type User<T = unknown> = { user: T }
export type UserAgent<T = unknown> = { userAgent: T }
export type UserCancelTimeMs<T = unknown> = { userCancelTimeMs: T }
export type UserData<T = unknown> = { userData: T }
export type UserDevice<T = unknown> = { userDevice: T }
export type UserId<T = unknown> = { userId: T }
export type UserIds<T = unknown> = { userIds: T }
export type UserInputCancelReason<T = unknown> = { userInputCancelReason: T }
export type UserName<T = unknown> = { userName: T }
export type UserOs<T = unknown> = { userOs: T }
export type UserPassword<T = unknown> = { userPassword: T }
export type UserProperties<T = unknown> = { userProperties: T }
export type Username<T = unknown> = { username: T }
export type Users<T = unknown> = { users: T }
export type Utc<T = unknown> = { utc: T }
export type Valid<T = unknown> = { valid: T }
export type Validate<T = unknown> = { validate: T }
export type Validated<T = unknown> = { validated: T }
export type Validation<T = unknown> = { validation: T }
export type Value<T = unknown> = { value: T }
export type Values<T = unknown> = { values: T }
export type Variation<T = unknown> = { variation: T }
export type Variations<T = unknown> = { variations: T }
export type Vars<T = unknown> = { vars: T }
export type Vector<T = unknown> = { vector: T }
export type VendorId<T = unknown> = { vendorId: T }
export type VendorIds<T = unknown> = { vendorIds: T }
export type Verbose<T = unknown> = { verbose: T }
export type Version<T = unknown> = { version: T }
export type Video<T = unknown> = { video: T }
export type VideoData<T = unknown> = { videoData: T }
export type VideoId<T = unknown> = { videoId: T }
export type VideoIds<T = unknown> = { videoIds: T }
export type VideoName<T = unknown> = { videoName: T }
export type VideoUrl<T = unknown> = { videoUrl: T }
export type Videos<T = unknown> = { videos: T }
export type View<T = unknown> = { view: T }
export type ViewId<T = unknown> = { viewId: T }
export type ViewIds<T = unknown> = { viewIds: T }
export type Views<T = unknown> = { views: T }
export type Visitor<T = unknown> = { visitor: T }
export type VisitorId<T = unknown> = { visitorId: T }
export type VisitorIds<T = unknown> = { visitorIds: T }
export type Visitors<T = unknown> = { visitors: T }
export type Warning<T = unknown> = { warning: T }
export type Web<T = unknown> = { web: T }
export type WebCancellation<T = unknown> = { webCancellation: T }
export type WebCancellations<T = unknown> = { webCancellations: T }
export type WebCustomer<T = unknown> = { webCustomer: T }
export type WebCustomerEmail<T = unknown> = { webCustomerEmail: T }
export type WebCustomerId<T = unknown> = { webCustomerId: T }
export type WebCustomerIds<T = unknown> = { webCustomerIds: T }
export type WebCustomerName<T = unknown> = { webCustomerName: T }
export type WebTransaction<T = unknown> = { webTransaction: T }
export type WebTransactionId<T = unknown> = { webTransactionId: T }
export type WebTransactionIds<T = unknown> = { webTransactionIds: T }
export type WebTransactions<T = unknown> = { webTransactions: T }
export type Webhook<T = unknown> = { webhook: T }
export type WebhookUrl<T = unknown> = { webhookUrl: T }
export type Webhooks<T = unknown> = { webhooks: T }
export type Week<T = unknown> = { week: T }
export type Weeks<T = unknown> = { weeks: T }
export type Weight<T = unknown> = { weight: T }
export type Where<T = unknown> = { where: T }
export type Whitelist<T = unknown> = { whitelist: T }
export type Width<T = unknown> = { width: T }
export type Workspace<T = unknown> = { workspace: T }
export type WorkspaceId<T = unknown> = { workspaceId: T }
export type WorkspaceIds<T = unknown> = { workspaceIds: T }
export type Workspaces<T = unknown> = { workspaces: T }
export type Wrapper<T = unknown> = { wrapper: T }
export type X<T = unknown> = { x: T }
export type Y<T = unknown> = { y: T }
export type Year<T = unknown> = { year: T }
export type Years<T = unknown> = { years: T }
export type Z<T = unknown> = { z: T }
export type ZIndex<T = unknown> = { zIndex: T }
export type Zip<T = unknown> = { zip: T }
export type ZipCode<T = unknown> = { zipCode: T }
export type Ziped<T = unknown> = { ziped: T }